// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newAccountWebHooksCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "account-web-hooks",
		Short: "Automatisierungen verwalten",
	}
	cmd.AddCommand(
		newAccountWebHooksCreateCmd(app),
		newAccountWebHooksDeleteCmd(app),
		newAccountWebHooksDisableCmd(app),
		newAccountWebHooksEnableCmd(app),
		newAccountWebHooksGetCmd(app),
		newAccountWebHooksListCmd(app),
		newAccountWebHooksPatchCmd(app),
		newAccountWebHooksUpdateCmd(app),
	)
	return cmd
}

func newAccountWebHooksCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Automatisierung erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/web_hooks"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("event") {
				body["event"] = v0
			}
			if cmd.Flags().Changed("hook") {
				body["hook"] = v1
			}
			if cmd.Flags().Changed("target") {
				body["target"] = v2
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "event", "", "")
	f.StringVar(&v1, "hook", "", "")
	f.StringVar(&v2, "target", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountWebHooksDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Automatisierung löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/web_hooks/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountWebHooksDisableCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "disable <id>",
		Short: "Automatisierung deaktivieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/web_hooks/{id}/disable"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountWebHooksEnableCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "enable <id>",
		Short: "Automatisierung aktivieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/web_hooks/{id}/enable"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountWebHooksGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Automatisierung abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/web_hooks/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountWebHooksListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 int
	var q2 int
	var q3 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Automatisierungen auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/web_hooks"
			q := url.Values{}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q3))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q1, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q2, "per-page", 0, "Page size.")
	f.StringVar(&q3, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newAccountWebHooksPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Automatisierung teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/web_hooks/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("hook") {
				body["hook"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "hook", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountWebHooksUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Automatisierung aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/web_hooks/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("hook") {
				body["hook"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "hook", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
