// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newAccountCustomPropertiesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "account-custom-properties",
		Short: "Eigene Felder verwalten",
	}
	cmd.AddCommand(
		newAccountCustomPropertiesCreateCmd(app),
		newAccountCustomPropertiesDeleteCmd(app),
		newAccountCustomPropertiesGetCmd(app),
		newAccountCustomPropertiesListCmd(app),
		newAccountCustomPropertiesPatchCmd(app),
		newAccountCustomPropertiesUpdateCmd(app),
	)
	return cmd
}

func newAccountCustomPropertiesCreateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 string
	var v3 string
	var v4 string
	var v5 bool
	var v6 string
	var v7 string
	var v8 bool
	var v9 bool
	var v10 bool
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Eigenes Feld erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/custom_properties"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("api-only") {
				body["api_only"] = v0
			}
			if cmd.Flags().Changed("entity") {
				body["entity"] = v1
			}
			if cmd.Flags().Changed("id") {
				body["id"] = v2
			}
			if cmd.Flags().Changed("kind") {
				body["kind"] = v3
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v4
			}
			if cmd.Flags().Changed("notification-enabled") {
				body["notification_enabled"] = v5
			}
			if cmd.Flags().Changed("placeholder") {
				body["placeholder"] = v6
			}
			if cmd.Flags().Changed("placeholder-alt") {
				body["placeholder_alt"] = v7
			}
			if cmd.Flags().Changed("print-on-invoice") {
				body["print_on_invoice"] = v8
			}
			if cmd.Flags().Changed("print-on-offer") {
				body["print_on_offer"] = v9
			}
			if cmd.Flags().Changed("print-on-timesheet") {
				body["print_on_timesheet"] = v10
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "api-only", false, "")
	f.StringVar(&v1, "entity", "", "")
	f.StringVar(&v2, "id", "", "")
	f.StringVar(&v3, "kind", "", "")
	f.StringVar(&v4, "name", "", "")
	f.BoolVar(&v5, "notification-enabled", false, "")
	f.StringVar(&v6, "placeholder", "", "")
	f.StringVar(&v7, "placeholder-alt", "", "")
	f.BoolVar(&v8, "print-on-invoice", false, "")
	f.BoolVar(&v9, "print-on-offer", false, "")
	f.BoolVar(&v10, "print-on-timesheet", false, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountCustomPropertiesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Eigenes Feld löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/custom_properties/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountCustomPropertiesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Eigenes Feld abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/custom_properties/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountCustomPropertiesListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 int
	var q3 int
	var q4 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Eigene Felder auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/custom_properties"
			q := url.Values{}
			if cmd.Flags().Changed("entity") {
				q.Set("entity", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q4))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "entity", "", "")
	f.StringVar(&q1, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q2, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q3, "per-page", 0, "Page size.")
	f.StringVar(&q4, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newAccountCustomPropertiesPatchCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 string
	var v3 string
	var v4 string
	var v5 bool
	var v6 string
	var v7 string
	var v8 bool
	var v9 bool
	var v10 bool
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Eigenes Feld teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/custom_properties/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("api-only") {
				body["api_only"] = v0
			}
			if cmd.Flags().Changed("entity") {
				body["entity"] = v1
			}
			if cmd.Flags().Changed("id") {
				body["id"] = v2
			}
			if cmd.Flags().Changed("kind") {
				body["kind"] = v3
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v4
			}
			if cmd.Flags().Changed("notification-enabled") {
				body["notification_enabled"] = v5
			}
			if cmd.Flags().Changed("placeholder") {
				body["placeholder"] = v6
			}
			if cmd.Flags().Changed("placeholder-alt") {
				body["placeholder_alt"] = v7
			}
			if cmd.Flags().Changed("print-on-invoice") {
				body["print_on_invoice"] = v8
			}
			if cmd.Flags().Changed("print-on-offer") {
				body["print_on_offer"] = v9
			}
			if cmd.Flags().Changed("print-on-timesheet") {
				body["print_on_timesheet"] = v10
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "api-only", false, "")
	f.StringVar(&v1, "entity", "", "")
	f.StringVar(&v2, "id", "", "")
	f.StringVar(&v3, "kind", "", "")
	f.StringVar(&v4, "name", "", "")
	f.BoolVar(&v5, "notification-enabled", false, "")
	f.StringVar(&v6, "placeholder", "", "")
	f.StringVar(&v7, "placeholder-alt", "", "")
	f.BoolVar(&v8, "print-on-invoice", false, "")
	f.BoolVar(&v9, "print-on-offer", false, "")
	f.BoolVar(&v10, "print-on-timesheet", false, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountCustomPropertiesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 string
	var v3 string
	var v4 string
	var v5 bool
	var v6 string
	var v7 string
	var v8 bool
	var v9 bool
	var v10 bool
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Eigenes Feld aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/custom_properties/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("api-only") {
				body["api_only"] = v0
			}
			if cmd.Flags().Changed("entity") {
				body["entity"] = v1
			}
			if cmd.Flags().Changed("id") {
				body["id"] = v2
			}
			if cmd.Flags().Changed("kind") {
				body["kind"] = v3
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v4
			}
			if cmd.Flags().Changed("notification-enabled") {
				body["notification_enabled"] = v5
			}
			if cmd.Flags().Changed("placeholder") {
				body["placeholder"] = v6
			}
			if cmd.Flags().Changed("placeholder-alt") {
				body["placeholder_alt"] = v7
			}
			if cmd.Flags().Changed("print-on-invoice") {
				body["print_on_invoice"] = v8
			}
			if cmd.Flags().Changed("print-on-offer") {
				body["print_on_offer"] = v9
			}
			if cmd.Flags().Changed("print-on-timesheet") {
				body["print_on_timesheet"] = v10
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "api-only", false, "")
	f.StringVar(&v1, "entity", "", "")
	f.StringVar(&v2, "id", "", "")
	f.StringVar(&v3, "kind", "", "")
	f.StringVar(&v4, "name", "", "")
	f.BoolVar(&v5, "notification-enabled", false, "")
	f.StringVar(&v6, "placeholder", "", "")
	f.StringVar(&v7, "placeholder-alt", "", "")
	f.BoolVar(&v8, "print-on-invoice", false, "")
	f.BoolVar(&v9, "print-on-offer", false, "")
	f.BoolVar(&v10, "print-on-timesheet", false, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
