// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newAccountExpenseTemplatesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "account-expense-templates",
		Short: "Standard-Zusatzleistungen verwalten",
	}
	cmd.AddCommand(
		newAccountExpenseTemplatesCreateCmd(app),
		newAccountExpenseTemplatesDeleteCmd(app),
		newAccountExpenseTemplatesGetCmd(app),
		newAccountExpenseTemplatesListCmd(app),
		newAccountExpenseTemplatesPatchCmd(app),
		newAccountExpenseTemplatesUpdateCmd(app),
	)
	return cmd
}

func newAccountExpenseTemplatesCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 int
	var v2 string
	var v3 string
	var v4 float64
	var v5 float64
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Standard-Zusatzleistung erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/expense_templates"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v0
			}
			if cmd.Flags().Changed("revenue-category-id") {
				body["revenue_category_id"] = v1
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v2
			}
			if cmd.Flags().Changed("unit") {
				body["unit"] = v3
			}
			if cmd.Flags().Changed("unit-cost") {
				body["unit_cost"] = v4
			}
			if cmd.Flags().Changed("unit-price") {
				body["unit_price"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "description", "", "")
	f.IntVar(&v1, "revenue-category-id", 0, "")
	f.StringVar(&v2, "title", "", "")
	f.StringVar(&v3, "unit", "", "")
	f.Float64Var(&v4, "unit-cost", 0, "")
	f.Float64Var(&v5, "unit-price", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountExpenseTemplatesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Standard-Zusatzleistung löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/expense_templates/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountExpenseTemplatesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Standard-Zusatzleistung abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/expense_templates/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountExpenseTemplatesListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 int
	var q2 int
	var q3 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Standard-Zusatzleistungen auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/expense_templates"
			q := url.Values{}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q3))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q1, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q2, "per-page", 0, "Page size.")
	f.StringVar(&q3, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newAccountExpenseTemplatesPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 int
	var v2 string
	var v3 string
	var v4 float64
	var v5 float64
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Standard-Zusatzleistung teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/expense_templates/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v0
			}
			if cmd.Flags().Changed("revenue-category-id") {
				body["revenue_category_id"] = v1
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v2
			}
			if cmd.Flags().Changed("unit") {
				body["unit"] = v3
			}
			if cmd.Flags().Changed("unit-cost") {
				body["unit_cost"] = v4
			}
			if cmd.Flags().Changed("unit-price") {
				body["unit_price"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "description", "", "")
	f.IntVar(&v1, "revenue-category-id", 0, "")
	f.StringVar(&v2, "title", "", "")
	f.StringVar(&v3, "unit", "", "")
	f.Float64Var(&v4, "unit-cost", 0, "")
	f.Float64Var(&v5, "unit-price", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountExpenseTemplatesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 int
	var v2 string
	var v3 string
	var v4 float64
	var v5 float64
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Standard-Zusatzleistung aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/expense_templates/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v0
			}
			if cmd.Flags().Changed("revenue-category-id") {
				body["revenue_category_id"] = v1
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v2
			}
			if cmd.Flags().Changed("unit") {
				body["unit"] = v3
			}
			if cmd.Flags().Changed("unit-cost") {
				body["unit_cost"] = v4
			}
			if cmd.Flags().Changed("unit-price") {
				body["unit_price"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "description", "", "")
	f.IntVar(&v1, "revenue-category-id", 0, "")
	f.StringVar(&v2, "title", "", "")
	f.StringVar(&v3, "unit", "", "")
	f.Float64Var(&v4, "unit-cost", 0, "")
	f.Float64Var(&v5, "unit-price", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
