// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newAccountCatalogServicesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "account-catalog-services",
		Short: "Leistungskataloge verwalten",
	}
	cmd.AddCommand(
		newAccountCatalogServicesCreateCmd(app),
		newAccountCatalogServicesDeleteCmd(app),
		newAccountCatalogServicesGetCmd(app),
		newAccountCatalogServicesItemsCreateCmd(app),
		newAccountCatalogServicesItemsDeleteCmd(app),
		newAccountCatalogServicesItemsGetCmd(app),
		newAccountCatalogServicesItemsPatchCmd(app),
		newAccountCatalogServicesItemsUpdateCmd(app),
		newAccountCatalogServicesListCmd(app),
		newAccountCatalogServicesPatchCmd(app),
		newAccountCatalogServicesUpdateCmd(app),
	)
	return cmd
}

func newAccountCatalogServicesCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Leistungskatalog erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/catalog_services"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "title", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountCatalogServicesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Leistungskatalog löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/catalog_services/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountCatalogServicesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Leistungskatalog abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/catalog_services/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountCatalogServicesItemsCreateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 bool
	var v3 int
	var v4 float64
	var v5 bool
	var v6 bool
	var v7 string
	var v8 float64
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 float64
	var v14 float64
	var data string
	cmd := &cobra.Command{
		Use:   "items-create <catalog-service-id>",
		Short: "Leistungskatalog-Position erstellen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/catalog_services/{catalog_service_id}/items"
			path = strings.Replace(path, "{catalog_service_id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("additional") {
				body["additional"] = v0
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v1
			}
			if cmd.Flags().Changed("destroyed") {
				body["destroyed"] = v2
			}
			if cmd.Flags().Changed("id") {
				body["id"] = v3
			}
			if cmd.Flags().Changed("net-total") {
				body["net_total"] = v4
			}
			if cmd.Flags().Changed("optional") {
				body["optional"] = v5
			}
			if cmd.Flags().Changed("part") {
				body["part"] = v6
			}
			if cmd.Flags().Changed("position-group-display") {
				body["position_group_display"] = v7
			}
			if cmd.Flags().Changed("quantity") {
				body["quantity"] = v8
			}
			if cmd.Flags().Changed("subtotal-type") {
				body["subtotal_type"] = v9
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v10
			}
			if cmd.Flags().Changed("type") {
				body["type"] = v11
			}
			if cmd.Flags().Changed("unit") {
				body["unit"] = v12
			}
			if cmd.Flags().Changed("unit-cost") {
				body["unit_cost"] = v13
			}
			if cmd.Flags().Changed("unit-price") {
				body["unit_price"] = v14
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "additional", false, "")
	f.StringVar(&v1, "description", "", "")
	f.BoolVar(&v2, "destroyed", false, "")
	f.IntVar(&v3, "id", 0, "")
	f.Float64Var(&v4, "net-total", 0, "")
	f.BoolVar(&v5, "optional", false, "")
	f.BoolVar(&v6, "part", false, "")
	f.StringVar(&v7, "position-group-display", "", "")
	f.Float64Var(&v8, "quantity", 0, "")
	f.StringVar(&v9, "subtotal-type", "", "")
	f.StringVar(&v10, "title", "", "")
	f.StringVar(&v11, "type", "", "")
	f.StringVar(&v12, "unit", "", "")
	f.Float64Var(&v13, "unit-cost", 0, "")
	f.Float64Var(&v14, "unit-price", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountCatalogServicesItemsDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "items-delete <catalog-service-id> <id>",
		Short: "Leistungskatalog-Position löschen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/catalog_services/{catalog_service_id}/items/{id}"
			path = strings.Replace(path, "{catalog_service_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountCatalogServicesItemsGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "items-get <catalog-service-id> <id>",
		Short: "Leistungskatalog-Position abrufen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/catalog_services/{catalog_service_id}/items/{id}"
			path = strings.Replace(path, "{catalog_service_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountCatalogServicesItemsPatchCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 bool
	var v3 int
	var v4 float64
	var v5 bool
	var v6 bool
	var v7 string
	var v8 float64
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 float64
	var v14 float64
	var data string
	cmd := &cobra.Command{
		Use:   "items-patch <catalog-service-id> <id>",
		Short: "Leistungskatalog-Position teilweise aktualisieren",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/catalog_services/{catalog_service_id}/items/{id}"
			path = strings.Replace(path, "{catalog_service_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("additional") {
				body["additional"] = v0
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v1
			}
			if cmd.Flags().Changed("destroyed") {
				body["destroyed"] = v2
			}
			if cmd.Flags().Changed("id") {
				body["id"] = v3
			}
			if cmd.Flags().Changed("net-total") {
				body["net_total"] = v4
			}
			if cmd.Flags().Changed("optional") {
				body["optional"] = v5
			}
			if cmd.Flags().Changed("part") {
				body["part"] = v6
			}
			if cmd.Flags().Changed("position-group-display") {
				body["position_group_display"] = v7
			}
			if cmd.Flags().Changed("quantity") {
				body["quantity"] = v8
			}
			if cmd.Flags().Changed("subtotal-type") {
				body["subtotal_type"] = v9
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v10
			}
			if cmd.Flags().Changed("type") {
				body["type"] = v11
			}
			if cmd.Flags().Changed("unit") {
				body["unit"] = v12
			}
			if cmd.Flags().Changed("unit-cost") {
				body["unit_cost"] = v13
			}
			if cmd.Flags().Changed("unit-price") {
				body["unit_price"] = v14
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "additional", false, "")
	f.StringVar(&v1, "description", "", "")
	f.BoolVar(&v2, "destroyed", false, "")
	f.IntVar(&v3, "id", 0, "")
	f.Float64Var(&v4, "net-total", 0, "")
	f.BoolVar(&v5, "optional", false, "")
	f.BoolVar(&v6, "part", false, "")
	f.StringVar(&v7, "position-group-display", "", "")
	f.Float64Var(&v8, "quantity", 0, "")
	f.StringVar(&v9, "subtotal-type", "", "")
	f.StringVar(&v10, "title", "", "")
	f.StringVar(&v11, "type", "", "")
	f.StringVar(&v12, "unit", "", "")
	f.Float64Var(&v13, "unit-cost", 0, "")
	f.Float64Var(&v14, "unit-price", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountCatalogServicesItemsUpdateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 bool
	var v3 int
	var v4 float64
	var v5 bool
	var v6 bool
	var v7 string
	var v8 float64
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 float64
	var v14 float64
	var data string
	cmd := &cobra.Command{
		Use:   "items-update <catalog-service-id> <id>",
		Short: "Leistungskatalog-Position aktualisieren",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/catalog_services/{catalog_service_id}/items/{id}"
			path = strings.Replace(path, "{catalog_service_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("additional") {
				body["additional"] = v0
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v1
			}
			if cmd.Flags().Changed("destroyed") {
				body["destroyed"] = v2
			}
			if cmd.Flags().Changed("id") {
				body["id"] = v3
			}
			if cmd.Flags().Changed("net-total") {
				body["net_total"] = v4
			}
			if cmd.Flags().Changed("optional") {
				body["optional"] = v5
			}
			if cmd.Flags().Changed("part") {
				body["part"] = v6
			}
			if cmd.Flags().Changed("position-group-display") {
				body["position_group_display"] = v7
			}
			if cmd.Flags().Changed("quantity") {
				body["quantity"] = v8
			}
			if cmd.Flags().Changed("subtotal-type") {
				body["subtotal_type"] = v9
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v10
			}
			if cmd.Flags().Changed("type") {
				body["type"] = v11
			}
			if cmd.Flags().Changed("unit") {
				body["unit"] = v12
			}
			if cmd.Flags().Changed("unit-cost") {
				body["unit_cost"] = v13
			}
			if cmd.Flags().Changed("unit-price") {
				body["unit_price"] = v14
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "additional", false, "")
	f.StringVar(&v1, "description", "", "")
	f.BoolVar(&v2, "destroyed", false, "")
	f.IntVar(&v3, "id", 0, "")
	f.Float64Var(&v4, "net-total", 0, "")
	f.BoolVar(&v5, "optional", false, "")
	f.BoolVar(&v6, "part", false, "")
	f.StringVar(&v7, "position-group-display", "", "")
	f.Float64Var(&v8, "quantity", 0, "")
	f.StringVar(&v9, "subtotal-type", "", "")
	f.StringVar(&v10, "title", "", "")
	f.StringVar(&v11, "type", "", "")
	f.StringVar(&v12, "unit", "", "")
	f.Float64Var(&v13, "unit-cost", 0, "")
	f.Float64Var(&v14, "unit-price", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountCatalogServicesListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 int
	var q2 int
	var q3 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Leistungskataloge auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/catalog_services"
			q := url.Values{}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q3))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q1, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q2, "per-page", 0, "Page size.")
	f.StringVar(&q3, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newAccountCatalogServicesPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Leistungskatalog teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/catalog_services/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "title", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountCatalogServicesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Leistungskatalog aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/catalog_services/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "title", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
