// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newAccountRatesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "account-rates",
		Short: "Stundensätze verwalten",
	}
	cmd.AddCommand(
		newAccountRatesFixedCostsListCmd(app),
		newAccountRatesHourlyRatesListCmd(app),
		newAccountRatesInternalHourlyRatesGetCmd(app),
		newAccountRatesInternalHourlyRatesPatchCmd(app),
		newAccountRatesInternalHourlyRatesUpdateCmd(app),
	)
	return cmd
}

func newAccountRatesFixedCostsListCmd(app *cli.App) *cobra.Command {
	var q0 int
	var q1 int
	cmd := &cobra.Command{
		Use:   "fixed-costs-list",
		Short: "Fixkosten auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/fixed_costs"
			q := url.Values{}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("year") {
				q.Set("year", fmt.Sprint(q1))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q1, "year", 0, "Optional year filter for monthly cost entries.")
	return cmd
}

func newAccountRatesHourlyRatesListCmd(app *cli.App) *cobra.Command {
	var q0 int
	var q1 bool
	cmd := &cobra.Command{
		Use:   "hourly-rates-list",
		Short: "Stundensätze auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/hourly_rates"
			q := url.Values{}
			if cmd.Flags().Changed("company-id") {
				q.Set("company_id", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("include-archived-users") {
				q.Set("include_archived_users", fmt.Sprint(q1))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "company-id", 0, "Optional company ID. Returns company-specific defaults when available.")
	f.BoolVar(&q1, "include-archived-users", false, "Include archived users in the `users` section.")
	return cmd
}

func newAccountRatesInternalHourlyRatesGetCmd(app *cli.App) *cobra.Command {
	var q0 bool
	var q1 int
	var q2 string
	cmd := &cobra.Command{
		Use:   "internal-hourly-rates-get",
		Short: "Interne Stundensätze abrufen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/internal_hourly_rates"
			q := url.Values{}
			if cmd.Flags().Changed("include-archived") {
				q.Set("include_archived", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("unit-id") {
				q.Set("unit_id", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("years") {
				q.Set("years", fmt.Sprint(q2))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&q0, "include-archived", false, "Include archived users in response.")
	f.IntVar(&q1, "unit-id", 0, "Optional unit filter.")
	f.StringVar(&q2, "years", "", "Comma-separated years, for example `2024,2025`. Defaults to current year.")
	return cmd
}

func newAccountRatesInternalHourlyRatesPatchCmd(app *cli.App) *cobra.Command {
	var v0 int
	var data string
	cmd := &cobra.Command{
		Use:   "internal-hourly-rates-patch",
		Short: "Interne Stundensätze teilweise aktualisieren",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/internal_hourly_rates"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("year") {
				body["year"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&v0, "year", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountRatesInternalHourlyRatesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 int
	var data string
	cmd := &cobra.Command{
		Use:   "internal-hourly-rates-update",
		Short: "Interne Stundensätze aktualisieren",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/internal_hourly_rates"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("year") {
				body["year"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&v0, "year", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
