// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newAccountTaskTemplatesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "account-task-templates",
		Short: "Standardleistungen verwalten",
	}
	cmd.AddCommand(
		newAccountTaskTemplatesCreateCmd(app),
		newAccountTaskTemplatesDeleteCmd(app),
		newAccountTaskTemplatesGetCmd(app),
		newAccountTaskTemplatesListCmd(app),
		newAccountTaskTemplatesPatchCmd(app),
		newAccountTaskTemplatesUpdateCmd(app),
	)
	return cmd
}

func newAccountTaskTemplatesCreateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 int
	var v3 string
	var v4 bool
	var v5 int
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Standardleistung erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/task_templates"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v1
			}
			if cmd.Flags().Changed("index") {
				body["index"] = v2
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v3
			}
			if cmd.Flags().Changed("project-default") {
				body["project_default"] = v4
			}
			if cmd.Flags().Changed("revenue-category-id") {
				body["revenue_category_id"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "")
	f.StringVar(&v1, "description", "", "")
	f.IntVar(&v2, "index", 0, "")
	f.StringVar(&v3, "name", "", "")
	f.BoolVar(&v4, "project-default", false, "")
	f.IntVar(&v5, "revenue-category-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountTaskTemplatesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Standardleistung löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/task_templates/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountTaskTemplatesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Standardleistung abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/task_templates/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newAccountTaskTemplatesListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 int
	var q2 int
	var q3 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Standardleistungen auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/task_templates"
			q := url.Values{}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q3))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q1, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q2, "per-page", 0, "Page size.")
	f.StringVar(&q3, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newAccountTaskTemplatesPatchCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 int
	var v3 string
	var v4 bool
	var v5 int
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Standardleistung teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/task_templates/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v1
			}
			if cmd.Flags().Changed("index") {
				body["index"] = v2
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v3
			}
			if cmd.Flags().Changed("project-default") {
				body["project_default"] = v4
			}
			if cmd.Flags().Changed("revenue-category-id") {
				body["revenue_category_id"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "")
	f.StringVar(&v1, "description", "", "")
	f.IntVar(&v2, "index", 0, "")
	f.StringVar(&v3, "name", "", "")
	f.BoolVar(&v4, "project-default", false, "")
	f.IntVar(&v5, "revenue-category-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newAccountTaskTemplatesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 int
	var v3 string
	var v4 bool
	var v5 int
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Standardleistung aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/account/task_templates/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v1
			}
			if cmd.Flags().Changed("index") {
				body["index"] = v2
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v3
			}
			if cmd.Flags().Changed("project-default") {
				body["project_default"] = v4
			}
			if cmd.Flags().Changed("revenue-category-id") {
				body["revenue_category_id"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "")
	f.StringVar(&v1, "description", "", "")
	f.IntVar(&v2, "index", 0, "")
	f.StringVar(&v3, "name", "", "")
	f.BoolVar(&v4, "project-default", false, "")
	f.IntVar(&v5, "revenue-category-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
