// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newActivitiesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "activities",
		Short: "Zeiteinträge verwalten",
	}
	cmd.AddCommand(
		newActivitiesBulkCreateCmd(app),
		newActivitiesCreateCmd(app),
		newActivitiesDeleteCmd(app),
		newActivitiesDisregardCmd(app),
		newActivitiesGetCmd(app),
		newActivitiesListCmd(app),
		newActivitiesPatchCmd(app),
		newActivitiesStartTimerCmd(app),
		newActivitiesStopTimerCmd(app),
		newActivitiesUpdateCmd(app),
		newActivitiesUpdateBillableSecondsCmd(app),
	)
	return cmd
}

func newActivitiesBulkCreateCmd(app *cli.App) *cobra.Command {
	var data string
	cmd := &cobra.Command{
		Use:   "bulk-create",
		Short: "Zeiteinträge als Stapel erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/activities/bulk"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newActivitiesCreateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 int
	var v2 string
	var v3 string
	var v4 float64
	var v5 int
	var v6 string
	var v7 string
	var v8 string
	var v9 int
	var v10 bool
	var v11 string
	var v12 int
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Zeiteintrag erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/activities"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v1
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v2
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v3
			}
			if cmd.Flags().Changed("hours") {
				body["hours"] = v4
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v5
			}
			if cmd.Flags().Changed("remote-id") {
				body["remote_id"] = v6
			}
			if cmd.Flags().Changed("remote-service") {
				body["remote_service"] = v7
			}
			if cmd.Flags().Changed("remote-url") {
				body["remote_url"] = v8
			}
			if cmd.Flags().Changed("seconds") {
				body["seconds"] = v9
			}
			if cmd.Flags().Changed("stop-timer") {
				body["stop_timer"] = v10
			}
			if cmd.Flags().Changed("tag") {
				body["tag"] = v11
			}
			if cmd.Flags().Changed("task-id") {
				body["task_id"] = v12
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "Whether the activity is billable.")
	f.IntVar(&v1, "company-id", 0, "Optional company/customer ID shortcut.")
	f.StringVar(&v2, "date", "", "Activity date.")
	f.StringVar(&v3, "description", "", "Free-text activity description.")
	f.Float64Var(&v4, "hours", 0, "Deprecated duration field, converted to seconds.")
	f.IntVar(&v5, "project-id", 0, "Project ID (mapped internally to assignment).")
	f.StringVar(&v6, "remote-id", "", "External identifier of linked remote item.")
	f.StringVar(&v7, "remote-service", "", "External source system identifier.")
	f.StringVar(&v8, "remote-url", "", "URL to related external item.")
	f.IntVar(&v9, "seconds", 0, "Duration in seconds.")
	f.BoolVar(&v10, "stop-timer", false, "If true, stops any running timer before applying the update. This allows updating `seconds` even when a timer is running.")
	f.StringVar(&v11, "tag", "", "Optional activity tag label.")
	f.IntVar(&v12, "task-id", 0, "Task/service ID.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newActivitiesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Zeiteintrag löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/activities/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newActivitiesDisregardCmd(app *cli.App) *cobra.Command {
	var v0 int
	var v1 int
	var v2 int
	var v3 string
	var data string
	cmd := &cobra.Command{
		Use:   "disregard",
		Short: "Zeiteinträge von der Verrechnung ausnehmen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/activities/disregard"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v0
			}
			if cmd.Flags().Changed("customer-id") {
				body["customer_id"] = v1
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v2
			}
			if cmd.Flags().Changed("reason") {
				body["reason"] = v3
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&v0, "company-id", 0, "Customer/company ID used for disregard context.")
	f.IntVar(&v1, "customer-id", 0, "Deprecated alias for `company_id`.")
	f.IntVar(&v2, "project-id", 0, "Optional project scope.")
	f.StringVar(&v3, "reason", "", "Reason shown in history/audit context.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newActivitiesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Zeiteintrag abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/activities/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newActivitiesListCmd(app *cli.App) *cobra.Command {
	var q0 bool
	var q1 bool
	var q2 int
	var q3 string
	var q4 string
	var q5 int
	var q6 int
	var q7 int
	var q8 string
	var q9 int
	var q10 string
	var q11 string
	var q12 string
	var q13 int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Zeiteinträge auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/activities"
			q := url.Values{}
			if cmd.Flags().Changed("billable") {
				q.Set("billable", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("billed") {
				q.Set("billed", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("company-id") {
				q.Set("company_id", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("from") {
				q.Set("from", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("project-id") {
				q.Set("project_id", fmt.Sprint(q7))
			}
			if cmd.Flags().Changed("sort-by") {
				q.Set("sort_by", fmt.Sprint(q8))
			}
			if cmd.Flags().Changed("task-id") {
				q.Set("task_id", fmt.Sprint(q9))
			}
			if cmd.Flags().Changed("term") {
				q.Set("term", fmt.Sprint(q10))
			}
			if cmd.Flags().Changed("to") {
				q.Set("to", fmt.Sprint(q11))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q12))
			}
			if cmd.Flags().Changed("user-id") {
				q.Set("user_id", fmt.Sprint(q13))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&q0, "billable", false, "")
	f.BoolVar(&q1, "billed", false, "")
	f.IntVar(&q2, "company-id", 0, "")
	f.StringVar(&q3, "from", "", "Start date filter. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q4, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q5, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q6, "per-page", 0, "Page size.")
	f.IntVar(&q7, "project-id", 0, "")
	f.StringVar(&q8, "sort-by", "", "Field and optional direction, e.g. `title desc`.")
	f.IntVar(&q9, "task-id", 0, "")
	f.StringVar(&q10, "term", "", "")
	f.StringVar(&q11, "to", "", "End date filter. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q12, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	f.IntVar(&q13, "user-id", 0, "")
	return cmd
}

func newActivitiesPatchCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 int
	var v2 string
	var v3 string
	var v4 float64
	var v5 int
	var v6 string
	var v7 string
	var v8 string
	var v9 int
	var v10 bool
	var v11 string
	var v12 int
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Zeiteintrag teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/activities/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v1
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v2
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v3
			}
			if cmd.Flags().Changed("hours") {
				body["hours"] = v4
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v5
			}
			if cmd.Flags().Changed("remote-id") {
				body["remote_id"] = v6
			}
			if cmd.Flags().Changed("remote-service") {
				body["remote_service"] = v7
			}
			if cmd.Flags().Changed("remote-url") {
				body["remote_url"] = v8
			}
			if cmd.Flags().Changed("seconds") {
				body["seconds"] = v9
			}
			if cmd.Flags().Changed("stop-timer") {
				body["stop_timer"] = v10
			}
			if cmd.Flags().Changed("tag") {
				body["tag"] = v11
			}
			if cmd.Flags().Changed("task-id") {
				body["task_id"] = v12
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "Whether the activity is billable.")
	f.IntVar(&v1, "company-id", 0, "Optional company/customer ID shortcut.")
	f.StringVar(&v2, "date", "", "Activity date.")
	f.StringVar(&v3, "description", "", "Free-text activity description.")
	f.Float64Var(&v4, "hours", 0, "Deprecated duration field, converted to seconds.")
	f.IntVar(&v5, "project-id", 0, "Project ID (mapped internally to assignment).")
	f.StringVar(&v6, "remote-id", "", "External identifier of linked remote item.")
	f.StringVar(&v7, "remote-service", "", "External source system identifier.")
	f.StringVar(&v8, "remote-url", "", "URL to related external item.")
	f.IntVar(&v9, "seconds", 0, "Duration in seconds.")
	f.BoolVar(&v10, "stop-timer", false, "If true, stops any running timer before applying the update. This allows updating `seconds` even when a timer is running.")
	f.StringVar(&v11, "tag", "", "Optional activity tag label.")
	f.IntVar(&v12, "task-id", 0, "Task/service ID.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newActivitiesStartTimerCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "start-timer <id>",
		Short: "Zeiterfassungs-Timer starten",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/activities/{id}/start_timer"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
			})
		},
	}
	return cmd
}

func newActivitiesStopTimerCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "stop-timer <id>",
		Short: "Zeiterfassungs-Timer stoppen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/activities/{id}/stop_timer"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
			})
		},
	}
	return cmd
}

func newActivitiesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 int
	var v2 string
	var v3 string
	var v4 float64
	var v5 int
	var v6 string
	var v7 string
	var v8 string
	var v9 int
	var v10 bool
	var v11 string
	var v12 int
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Zeiteintrag aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/activities/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v1
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v2
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v3
			}
			if cmd.Flags().Changed("hours") {
				body["hours"] = v4
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v5
			}
			if cmd.Flags().Changed("remote-id") {
				body["remote_id"] = v6
			}
			if cmd.Flags().Changed("remote-service") {
				body["remote_service"] = v7
			}
			if cmd.Flags().Changed("remote-url") {
				body["remote_url"] = v8
			}
			if cmd.Flags().Changed("seconds") {
				body["seconds"] = v9
			}
			if cmd.Flags().Changed("stop-timer") {
				body["stop_timer"] = v10
			}
			if cmd.Flags().Changed("tag") {
				body["tag"] = v11
			}
			if cmd.Flags().Changed("task-id") {
				body["task_id"] = v12
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "Whether the activity is billable.")
	f.IntVar(&v1, "company-id", 0, "Optional company/customer ID shortcut.")
	f.StringVar(&v2, "date", "", "Activity date.")
	f.StringVar(&v3, "description", "", "Free-text activity description.")
	f.Float64Var(&v4, "hours", 0, "Deprecated duration field, converted to seconds.")
	f.IntVar(&v5, "project-id", 0, "Project ID (mapped internally to assignment).")
	f.StringVar(&v6, "remote-id", "", "External identifier of linked remote item.")
	f.StringVar(&v7, "remote-service", "", "External source system identifier.")
	f.StringVar(&v8, "remote-url", "", "URL to related external item.")
	f.IntVar(&v9, "seconds", 0, "Duration in seconds.")
	f.BoolVar(&v10, "stop-timer", false, "If true, stops any running timer before applying the update. This allows updating `seconds` even when a timer is running.")
	f.StringVar(&v11, "tag", "", "Optional activity tag label.")
	f.IntVar(&v12, "task-id", 0, "Task/service ID.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newActivitiesUpdateBillableSecondsCmd(app *cli.App) *cobra.Command {
	var v0 int
	var data string
	cmd := &cobra.Command{
		Use:   "update-billable-seconds <id>",
		Short: "Verrechenbare Sekunden des Zeiteintrags aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/activities/{id}/billable_seconds"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("seconds") {
				body["seconds"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&v0, "seconds", 0, "Billable seconds (may differ from worked_seconds).")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
