// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newCommentsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "comments",
		Short: "Kommentare verwalten",
	}
	cmd.AddCommand(
		newCommentsBulkCreateCmd(app),
		newCommentsCreateCmd(app),
		newCommentsDeleteCmd(app),
		newCommentsGetCmd(app),
		newCommentsListCmd(app),
		newCommentsPatchCmd(app),
		newCommentsUpdateCmd(app),
	)
	return cmd
}

func newCommentsBulkCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var data string
	cmd := &cobra.Command{
		Use:   "bulk-create",
		Short: "Kommentare als Stapel erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/comments/bulk"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("commentable-type") {
				body["commentable_type"] = v0
			}
			if cmd.Flags().Changed("created-at") {
				body["created_at"] = v1
			}
			if cmd.Flags().Changed("text") {
				body["text"] = v2
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "commentable-type", "", "")
	f.StringVar(&v1, "created-at", "", "")
	f.StringVar(&v2, "text", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newCommentsCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 int
	var v3 string
	var v4 string
	var v5 string
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Kommentar erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/comments"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("attachment-content") {
				body["attachment_content"] = v0
			}
			if cmd.Flags().Changed("attachment-filename") {
				body["attachment_filename"] = v1
			}
			if cmd.Flags().Changed("commentable-id") {
				body["commentable_id"] = v2
			}
			if cmd.Flags().Changed("commentable-type") {
				body["commentable_type"] = v3
			}
			if cmd.Flags().Changed("created-at") {
				body["created_at"] = v4
			}
			if cmd.Flags().Changed("text") {
				body["text"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "attachment-content", "", "")
	f.StringVar(&v1, "attachment-filename", "", "")
	f.IntVar(&v2, "commentable-id", 0, "")
	f.StringVar(&v3, "commentable-type", "", "Public target type (for example `Project`, `Invoice`, `Purchase`).")
	f.StringVar(&v4, "created-at", "", "")
	f.StringVar(&v5, "text", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newCommentsDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Kommentar löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/comments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newCommentsGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Kommentar abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/comments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newCommentsListCmd(app *cli.App) *cobra.Command {
	var q0 int
	var q1 string
	var q2 string
	var q3 bool
	var q4 int
	var q5 int
	var q6 string
	var q7 int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Kommentare auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/comments"
			q := url.Values{}
			if cmd.Flags().Changed("commentable-id") {
				q.Set("commentable_id", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("commentable-type") {
				q.Set("commentable_type", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("manual") {
				q.Set("manual", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("user-id") {
				q.Set("user_id", fmt.Sprint(q7))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "commentable-id", 0, "")
	f.StringVar(&q1, "commentable-type", "", "Comment target type (for example `Project`, `Invoice`, `Purchase`).")
	f.StringVar(&q2, "ids", "", "Comma-separated IDs.")
	f.BoolVar(&q3, "manual", false, "")
	f.IntVar(&q4, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q5, "per-page", 0, "Page size.")
	f.StringVar(&q6, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	f.IntVar(&q7, "user-id", 0, "")
	return cmd
}

func newCommentsPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 int
	var v3 string
	var v4 string
	var v5 string
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Kommentar teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/comments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("attachment-content") {
				body["attachment_content"] = v0
			}
			if cmd.Flags().Changed("attachment-filename") {
				body["attachment_filename"] = v1
			}
			if cmd.Flags().Changed("commentable-id") {
				body["commentable_id"] = v2
			}
			if cmd.Flags().Changed("commentable-type") {
				body["commentable_type"] = v3
			}
			if cmd.Flags().Changed("created-at") {
				body["created_at"] = v4
			}
			if cmd.Flags().Changed("text") {
				body["text"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "attachment-content", "", "")
	f.StringVar(&v1, "attachment-filename", "", "")
	f.IntVar(&v2, "commentable-id", 0, "")
	f.StringVar(&v3, "commentable-type", "", "Public target type (for example `Project`, `Invoice`, `Purchase`).")
	f.StringVar(&v4, "created-at", "", "")
	f.StringVar(&v5, "text", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newCommentsUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 int
	var v3 string
	var v4 string
	var v5 string
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Kommentar aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/comments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("attachment-content") {
				body["attachment_content"] = v0
			}
			if cmd.Flags().Changed("attachment-filename") {
				body["attachment_filename"] = v1
			}
			if cmd.Flags().Changed("commentable-id") {
				body["commentable_id"] = v2
			}
			if cmd.Flags().Changed("commentable-type") {
				body["commentable_type"] = v3
			}
			if cmd.Flags().Changed("created-at") {
				body["created_at"] = v4
			}
			if cmd.Flags().Changed("text") {
				body["text"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "attachment-content", "", "")
	f.StringVar(&v1, "attachment-filename", "", "")
	f.IntVar(&v2, "commentable-id", 0, "")
	f.StringVar(&v3, "commentable-type", "", "Public target type (for example `Project`, `Invoice`, `Purchase`).")
	f.StringVar(&v4, "created-at", "", "")
	f.StringVar(&v5, "text", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
