// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
)

// AddCommands registers all generated group commands on the root command.
func AddCommands(root *cobra.Command, app *cli.App) {
	root.AddCommand(
		newAccountCatalogServicesCmd(app),
		newAccountCustomPropertiesCmd(app),
		newAccountExpenseTemplatesCmd(app),
		newAccountRatesCmd(app),
		newAccountTaskTemplatesCmd(app),
		newAccountWebHooksCmd(app),
		newActivitiesCmd(app),
		newCommentsCmd(app),
		newCompaniesCmd(app),
		newContactsCmd(app),
		newContractsCmd(app),
		newDealCategoriesCmd(app),
		newDealsCmd(app),
		newExpensesCmd(app),
		newInvoiceAttachmentsCmd(app),
		newInvoiceBookkeepingExportsCmd(app),
		newInvoicePaymentsCmd(app),
		newInvoiceRemindersCmd(app),
		newInvoicesCmd(app),
		newLetterPapersCmd(app),
		newOfferAttachmentsCmd(app),
		newOfferCustomerApprovalCmd(app),
		newOffersCmd(app),
		newPlanningEntriesCmd(app),
		newProfileCmd(app),
		newProjectGroupsCmd(app),
		newProjectPaymentSchedulesCmd(app),
		newProjectsCmd(app),
		newPurchaseBookkeepingExportsCmd(app),
		newPurchaseBudgetsCmd(app),
		newPurchaseCategoriesCmd(app),
		newPurchaseDraftsCmd(app),
		newPurchaseOrdersCmd(app),
		newPurchasePaymentsCmd(app),
		newPurchasesCmd(app),
		newReceiptsCmd(app),
		newRecurringExpensesCmd(app),
		newReportsCmd(app),
		newSchedulesCmd(app),
		newSessionCmd(app),
		newTaggingsCmd(app),
		newTagsCmd(app),
		newTasksCmd(app),
		newUnitsCmd(app),
		newUserEmploymentsCmd(app),
		newUserHolidaysCmd(app),
		newUserPresencesCmd(app),
		newUserRolesCmd(app),
		newUserWorkTimeAdjustmentsCmd(app),
		newUsersCmd(app),
		newVatCodePurchasesCmd(app),
		newVatCodeSalesCmd(app),
	)
}
