// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newCompaniesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "companies",
		Short: "Firmen verwalten",
	}
	cmd.AddCommand(
		newCompaniesArchiveCmd(app),
		newCompaniesCreateCmd(app),
		newCompaniesDeleteCmd(app),
		newCompaniesGetCmd(app),
		newCompaniesListCmd(app),
		newCompaniesPatchCmd(app),
		newCompaniesUnarchiveCmd(app),
		newCompaniesUpdateCmd(app),
	)
	return cmd
}

func newCompaniesArchiveCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "archive <id>",
		Short: "Firma archivieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/companies/{id}/archive"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
			})
		},
	}
	return cmd
}

func newCompaniesCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var v3 string
	var v4 string
	var v5 string
	var v6 string
	var v7 string
	var v8 string
	var v9 float64
	var v10 int
	var v11 string
	var v12 int
	var v13 string
	var v14 string
	var v15 string
	var v16 string
	var v17 string
	var v18 string
	var v19 string
	var v20 int
	var v21 string
	var v22 string
	var v23 string
	var v24 float64
	var v25 int
	var v26 string
	var v27 int
	var v28 string
	var v29 string
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Firma erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/companies"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("address") {
				body["address"] = v0
			}
			if cmd.Flags().Changed("alternative-correspondence-language") {
				body["alternative_correspondence_language"] = v1
			}
			if cmd.Flags().Changed("bank-bic") {
				body["bank_bic"] = v2
			}
			if cmd.Flags().Changed("bank-owner") {
				body["bank_owner"] = v3
			}
			if cmd.Flags().Changed("billing-email-cc") {
				body["billing_email_cc"] = v4
			}
			if cmd.Flags().Changed("billing-notes") {
				body["billing_notes"] = v5
			}
			if cmd.Flags().Changed("country-code") {
				body["country_code"] = v6
			}
			if cmd.Flags().Changed("credit-number") {
				body["credit_number"] = v7
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v8
			}
			if cmd.Flags().Changed("customer-tax") {
				body["customer_tax"] = v9
			}
			if cmd.Flags().Changed("customer-vat-code-id") {
				body["customer_vat_code_id"] = v10
			}
			if cmd.Flags().Changed("debit-number") {
				body["debit_number"] = v11
			}
			if cmd.Flags().Changed("default-invoice-due-days") {
				body["default_invoice_due_days"] = v12
			}
			if cmd.Flags().Changed("default-payment-means") {
				body["default_payment_means"] = v13
			}
			if cmd.Flags().Changed("email") {
				body["email"] = v14
			}
			if cmd.Flags().Changed("fax") {
				body["fax"] = v15
			}
			if cmd.Flags().Changed("footer") {
				body["footer"] = v16
			}
			if cmd.Flags().Changed("iban") {
				body["iban"] = v17
			}
			if cmd.Flags().Changed("identifier") {
				body["identifier"] = v18
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v19
			}
			if cmd.Flags().Changed("invoice-due-days") {
				body["invoice_due_days"] = v20
			}
			if cmd.Flags().Changed("invoice-format") {
				body["invoice_format"] = v21
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v22
			}
			if cmd.Flags().Changed("phone") {
				body["phone"] = v23
			}
			if cmd.Flags().Changed("supplier-tax") {
				body["supplier_tax"] = v24
			}
			if cmd.Flags().Changed("supplier-vat-code-id") {
				body["supplier_vat_code_id"] = v25
			}
			if cmd.Flags().Changed("type") {
				body["type"] = v26
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v27
			}
			if cmd.Flags().Changed("vat-identifier") {
				body["vat_identifier"] = v28
			}
			if cmd.Flags().Changed("website") {
				body["website"] = v29
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "address", "", "")
	f.StringVar(&v1, "alternative-correspondence-language", "", "")
	f.StringVar(&v2, "bank-bic", "", "")
	f.StringVar(&v3, "bank-owner", "", "")
	f.StringVar(&v4, "billing-email-cc", "", "")
	f.StringVar(&v5, "billing-notes", "", "")
	f.StringVar(&v6, "country-code", "", "")
	f.StringVar(&v7, "credit-number", "", "")
	f.StringVar(&v8, "currency", "", "")
	f.Float64Var(&v9, "customer-tax", 0, "Deprecated VAT shortcut for customer records.")
	f.IntVar(&v10, "customer-vat-code-id", 0, "")
	f.StringVar(&v11, "debit-number", "", "")
	f.IntVar(&v12, "default-invoice-due-days", 0, "")
	f.StringVar(&v13, "default-payment-means", "", "")
	f.StringVar(&v14, "email", "", "")
	f.StringVar(&v15, "fax", "", "")
	f.StringVar(&v16, "footer", "", "")
	f.StringVar(&v17, "iban", "", "")
	f.StringVar(&v18, "identifier", "", "")
	f.StringVar(&v19, "info", "", "")
	f.IntVar(&v20, "invoice-due-days", 0, "")
	f.StringVar(&v21, "invoice-format", "", "")
	f.StringVar(&v22, "name", "", "")
	f.StringVar(&v23, "phone", "", "")
	f.Float64Var(&v24, "supplier-tax", 0, "Deprecated VAT shortcut for supplier records.")
	f.IntVar(&v25, "supplier-vat-code-id", 0, "")
	f.StringVar(&v26, "type", "", "")
	f.IntVar(&v27, "user-id", 0, "")
	f.StringVar(&v28, "vat-identifier", "", "")
	f.StringVar(&v29, "website", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newCompaniesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Firma löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/companies/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newCompaniesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Firma abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/companies/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newCompaniesListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 string
	var q3 bool
	var q4 int
	var q5 int
	var q6 string
	var q7 string
	var q8 string
	var q9 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Firmen auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/companies"
			q := url.Values{}
			if cmd.Flags().Changed("custom-properties") {
				q.Set("custom_properties", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("identifier") {
				q.Set("identifier", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("include-archived") {
				q.Set("include_archived", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("tags") {
				q.Set("tags", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("term") {
				q.Set("term", fmt.Sprint(q7))
			}
			if cmd.Flags().Changed("type") {
				q.Set("type", fmt.Sprint(q8))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q9))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "custom-properties", "", "Filter by custom field values.")
	f.StringVar(&q1, "identifier", "", "")
	f.StringVar(&q2, "ids", "", "Comma-separated IDs.")
	f.BoolVar(&q3, "include-archived", false, "")
	f.IntVar(&q4, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q5, "per-page", 0, "Page size.")
	f.StringVar(&q6, "tags", "", "Comma-separated list of tag names.")
	f.StringVar(&q7, "term", "", "")
	f.StringVar(&q8, "type", "", "")
	f.StringVar(&q9, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newCompaniesPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var v3 string
	var v4 string
	var v5 string
	var v6 string
	var v7 string
	var v8 string
	var v9 float64
	var v10 int
	var v11 string
	var v12 int
	var v13 string
	var v14 string
	var v15 string
	var v16 string
	var v17 string
	var v18 string
	var v19 string
	var v20 int
	var v21 string
	var v22 string
	var v23 string
	var v24 float64
	var v25 int
	var v26 string
	var v27 int
	var v28 string
	var v29 string
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Firma teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/companies/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("address") {
				body["address"] = v0
			}
			if cmd.Flags().Changed("alternative-correspondence-language") {
				body["alternative_correspondence_language"] = v1
			}
			if cmd.Flags().Changed("bank-bic") {
				body["bank_bic"] = v2
			}
			if cmd.Flags().Changed("bank-owner") {
				body["bank_owner"] = v3
			}
			if cmd.Flags().Changed("billing-email-cc") {
				body["billing_email_cc"] = v4
			}
			if cmd.Flags().Changed("billing-notes") {
				body["billing_notes"] = v5
			}
			if cmd.Flags().Changed("country-code") {
				body["country_code"] = v6
			}
			if cmd.Flags().Changed("credit-number") {
				body["credit_number"] = v7
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v8
			}
			if cmd.Flags().Changed("customer-tax") {
				body["customer_tax"] = v9
			}
			if cmd.Flags().Changed("customer-vat-code-id") {
				body["customer_vat_code_id"] = v10
			}
			if cmd.Flags().Changed("debit-number") {
				body["debit_number"] = v11
			}
			if cmd.Flags().Changed("default-invoice-due-days") {
				body["default_invoice_due_days"] = v12
			}
			if cmd.Flags().Changed("default-payment-means") {
				body["default_payment_means"] = v13
			}
			if cmd.Flags().Changed("email") {
				body["email"] = v14
			}
			if cmd.Flags().Changed("fax") {
				body["fax"] = v15
			}
			if cmd.Flags().Changed("footer") {
				body["footer"] = v16
			}
			if cmd.Flags().Changed("iban") {
				body["iban"] = v17
			}
			if cmd.Flags().Changed("identifier") {
				body["identifier"] = v18
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v19
			}
			if cmd.Flags().Changed("invoice-due-days") {
				body["invoice_due_days"] = v20
			}
			if cmd.Flags().Changed("invoice-format") {
				body["invoice_format"] = v21
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v22
			}
			if cmd.Flags().Changed("phone") {
				body["phone"] = v23
			}
			if cmd.Flags().Changed("supplier-tax") {
				body["supplier_tax"] = v24
			}
			if cmd.Flags().Changed("supplier-vat-code-id") {
				body["supplier_vat_code_id"] = v25
			}
			if cmd.Flags().Changed("type") {
				body["type"] = v26
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v27
			}
			if cmd.Flags().Changed("vat-identifier") {
				body["vat_identifier"] = v28
			}
			if cmd.Flags().Changed("website") {
				body["website"] = v29
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "address", "", "")
	f.StringVar(&v1, "alternative-correspondence-language", "", "")
	f.StringVar(&v2, "bank-bic", "", "")
	f.StringVar(&v3, "bank-owner", "", "")
	f.StringVar(&v4, "billing-email-cc", "", "")
	f.StringVar(&v5, "billing-notes", "", "")
	f.StringVar(&v6, "country-code", "", "")
	f.StringVar(&v7, "credit-number", "", "")
	f.StringVar(&v8, "currency", "", "")
	f.Float64Var(&v9, "customer-tax", 0, "Deprecated VAT shortcut for customer records.")
	f.IntVar(&v10, "customer-vat-code-id", 0, "")
	f.StringVar(&v11, "debit-number", "", "")
	f.IntVar(&v12, "default-invoice-due-days", 0, "")
	f.StringVar(&v13, "default-payment-means", "", "")
	f.StringVar(&v14, "email", "", "")
	f.StringVar(&v15, "fax", "", "")
	f.StringVar(&v16, "footer", "", "")
	f.StringVar(&v17, "iban", "", "")
	f.StringVar(&v18, "identifier", "", "")
	f.StringVar(&v19, "info", "", "")
	f.IntVar(&v20, "invoice-due-days", 0, "")
	f.StringVar(&v21, "invoice-format", "", "")
	f.StringVar(&v22, "name", "", "")
	f.StringVar(&v23, "phone", "", "")
	f.Float64Var(&v24, "supplier-tax", 0, "Deprecated VAT shortcut for supplier records.")
	f.IntVar(&v25, "supplier-vat-code-id", 0, "")
	f.StringVar(&v26, "type", "", "")
	f.IntVar(&v27, "user-id", 0, "")
	f.StringVar(&v28, "vat-identifier", "", "")
	f.StringVar(&v29, "website", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newCompaniesUnarchiveCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "unarchive <id>",
		Short: "Firma aus dem Archiv holen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/companies/{id}/unarchive"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
			})
		},
	}
	return cmd
}

func newCompaniesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var v3 string
	var v4 string
	var v5 string
	var v6 string
	var v7 string
	var v8 string
	var v9 float64
	var v10 int
	var v11 string
	var v12 int
	var v13 string
	var v14 string
	var v15 string
	var v16 string
	var v17 string
	var v18 string
	var v19 string
	var v20 int
	var v21 string
	var v22 string
	var v23 string
	var v24 float64
	var v25 int
	var v26 string
	var v27 int
	var v28 string
	var v29 string
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Firma aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/companies/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("address") {
				body["address"] = v0
			}
			if cmd.Flags().Changed("alternative-correspondence-language") {
				body["alternative_correspondence_language"] = v1
			}
			if cmd.Flags().Changed("bank-bic") {
				body["bank_bic"] = v2
			}
			if cmd.Flags().Changed("bank-owner") {
				body["bank_owner"] = v3
			}
			if cmd.Flags().Changed("billing-email-cc") {
				body["billing_email_cc"] = v4
			}
			if cmd.Flags().Changed("billing-notes") {
				body["billing_notes"] = v5
			}
			if cmd.Flags().Changed("country-code") {
				body["country_code"] = v6
			}
			if cmd.Flags().Changed("credit-number") {
				body["credit_number"] = v7
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v8
			}
			if cmd.Flags().Changed("customer-tax") {
				body["customer_tax"] = v9
			}
			if cmd.Flags().Changed("customer-vat-code-id") {
				body["customer_vat_code_id"] = v10
			}
			if cmd.Flags().Changed("debit-number") {
				body["debit_number"] = v11
			}
			if cmd.Flags().Changed("default-invoice-due-days") {
				body["default_invoice_due_days"] = v12
			}
			if cmd.Flags().Changed("default-payment-means") {
				body["default_payment_means"] = v13
			}
			if cmd.Flags().Changed("email") {
				body["email"] = v14
			}
			if cmd.Flags().Changed("fax") {
				body["fax"] = v15
			}
			if cmd.Flags().Changed("footer") {
				body["footer"] = v16
			}
			if cmd.Flags().Changed("iban") {
				body["iban"] = v17
			}
			if cmd.Flags().Changed("identifier") {
				body["identifier"] = v18
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v19
			}
			if cmd.Flags().Changed("invoice-due-days") {
				body["invoice_due_days"] = v20
			}
			if cmd.Flags().Changed("invoice-format") {
				body["invoice_format"] = v21
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v22
			}
			if cmd.Flags().Changed("phone") {
				body["phone"] = v23
			}
			if cmd.Flags().Changed("supplier-tax") {
				body["supplier_tax"] = v24
			}
			if cmd.Flags().Changed("supplier-vat-code-id") {
				body["supplier_vat_code_id"] = v25
			}
			if cmd.Flags().Changed("type") {
				body["type"] = v26
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v27
			}
			if cmd.Flags().Changed("vat-identifier") {
				body["vat_identifier"] = v28
			}
			if cmd.Flags().Changed("website") {
				body["website"] = v29
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "address", "", "")
	f.StringVar(&v1, "alternative-correspondence-language", "", "")
	f.StringVar(&v2, "bank-bic", "", "")
	f.StringVar(&v3, "bank-owner", "", "")
	f.StringVar(&v4, "billing-email-cc", "", "")
	f.StringVar(&v5, "billing-notes", "", "")
	f.StringVar(&v6, "country-code", "", "")
	f.StringVar(&v7, "credit-number", "", "")
	f.StringVar(&v8, "currency", "", "")
	f.Float64Var(&v9, "customer-tax", 0, "Deprecated VAT shortcut for customer records.")
	f.IntVar(&v10, "customer-vat-code-id", 0, "")
	f.StringVar(&v11, "debit-number", "", "")
	f.IntVar(&v12, "default-invoice-due-days", 0, "")
	f.StringVar(&v13, "default-payment-means", "", "")
	f.StringVar(&v14, "email", "", "")
	f.StringVar(&v15, "fax", "", "")
	f.StringVar(&v16, "footer", "", "")
	f.StringVar(&v17, "iban", "", "")
	f.StringVar(&v18, "identifier", "", "")
	f.StringVar(&v19, "info", "", "")
	f.IntVar(&v20, "invoice-due-days", 0, "")
	f.StringVar(&v21, "invoice-format", "", "")
	f.StringVar(&v22, "name", "", "")
	f.StringVar(&v23, "phone", "", "")
	f.Float64Var(&v24, "supplier-tax", 0, "Deprecated VAT shortcut for supplier records.")
	f.IntVar(&v25, "supplier-vat-code-id", 0, "")
	f.StringVar(&v26, "type", "", "")
	f.IntVar(&v27, "user-id", 0, "")
	f.StringVar(&v28, "vat-identifier", "", "")
	f.StringVar(&v29, "website", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
