// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newContactsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "contacts",
		Short: "Kontakte verwalten",
	}
	cmd.AddCommand(
		newContactsCreateCmd(app),
		newContactsDeleteCmd(app),
		newContactsGetCmd(app),
		newContactsListCmd(app),
		newContactsPatchCmd(app),
		newContactsUpdateCmd(app),
	)
	return cmd
}

func newContactsCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 int
	var v3 int
	var v4 string
	var v5 string
	var v6 string
	var v7 string
	var v8 string
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 int
	var v14 string
	var v15 string
	var v16 int
	var v17 string
	var v18 string
	var v19 string
	var v20 string
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Kontakt erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/contacts/people"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("bday") {
				body["bday"] = v0
			}
			if cmd.Flags().Changed("birthday") {
				body["birthday"] = v1
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v2
			}
			if cmd.Flags().Changed("customer-id") {
				body["customer_id"] = v3
			}
			if cmd.Flags().Changed("firstname") {
				body["firstname"] = v4
			}
			if cmd.Flags().Changed("gender") {
				body["gender"] = v5
			}
			if cmd.Flags().Changed("home-address") {
				body["home_address"] = v6
			}
			if cmd.Flags().Changed("home-email") {
				body["home_email"] = v7
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v8
			}
			if cmd.Flags().Changed("job-position") {
				body["job_position"] = v9
			}
			if cmd.Flags().Changed("lastname") {
				body["lastname"] = v10
			}
			if cmd.Flags().Changed("mobile-phone") {
				body["mobile_phone"] = v11
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v12
			}
			if cmd.Flags().Changed("organization-id") {
				body["organization_id"] = v13
			}
			if cmd.Flags().Changed("salutation") {
				body["salutation"] = v14
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v15
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v16
			}
			if cmd.Flags().Changed("work-address") {
				body["work_address"] = v17
			}
			if cmd.Flags().Changed("work-email") {
				body["work_email"] = v18
			}
			if cmd.Flags().Changed("work-fax") {
				body["work_fax"] = v19
			}
			if cmd.Flags().Changed("work-phone") {
				body["work_phone"] = v20
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "bday", "", "")
	f.StringVar(&v1, "birthday", "", "")
	f.IntVar(&v2, "company-id", 0, "")
	f.IntVar(&v3, "customer-id", 0, "")
	f.StringVar(&v4, "firstname", "", "")
	f.StringVar(&v5, "gender", "", "")
	f.StringVar(&v6, "home-address", "", "")
	f.StringVar(&v7, "home-email", "", "")
	f.StringVar(&v8, "info", "", "")
	f.StringVar(&v9, "job-position", "", "")
	f.StringVar(&v10, "lastname", "", "")
	f.StringVar(&v11, "mobile-phone", "", "")
	f.StringVar(&v12, "name", "", "")
	f.IntVar(&v13, "organization-id", 0, "")
	f.StringVar(&v14, "salutation", "", "")
	f.StringVar(&v15, "title", "", "")
	f.IntVar(&v16, "user-id", 0, "")
	f.StringVar(&v17, "work-address", "", "")
	f.StringVar(&v18, "work-email", "", "")
	f.StringVar(&v19, "work-fax", "", "")
	f.StringVar(&v20, "work-phone", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newContactsDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Kontakt löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/contacts/people/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newContactsGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Kontakt abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/contacts/people/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newContactsListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 int
	var q3 int
	var q4 string
	var q5 string
	var q6 string
	var q7 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Kontakte auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/contacts/people"
			q := url.Values{}
			if cmd.Flags().Changed("custom-properties") {
				q.Set("custom_properties", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("phone") {
				q.Set("phone", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("tags") {
				q.Set("tags", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("term") {
				q.Set("term", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q7))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "custom-properties", "", "Filter by custom field values.")
	f.StringVar(&q1, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q2, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q3, "per-page", 0, "Page size.")
	f.StringVar(&q4, "phone", "", "Reverse lookup on work/mobile phone.")
	f.StringVar(&q5, "tags", "", "Comma-separated list of tag names.")
	f.StringVar(&q6, "term", "", "Full text search on name, email and company.")
	f.StringVar(&q7, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newContactsPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 int
	var v3 int
	var v4 string
	var v5 string
	var v6 string
	var v7 string
	var v8 string
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 int
	var v14 string
	var v15 string
	var v16 int
	var v17 string
	var v18 string
	var v19 string
	var v20 string
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Kontakt teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/contacts/people/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("bday") {
				body["bday"] = v0
			}
			if cmd.Flags().Changed("birthday") {
				body["birthday"] = v1
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v2
			}
			if cmd.Flags().Changed("customer-id") {
				body["customer_id"] = v3
			}
			if cmd.Flags().Changed("firstname") {
				body["firstname"] = v4
			}
			if cmd.Flags().Changed("gender") {
				body["gender"] = v5
			}
			if cmd.Flags().Changed("home-address") {
				body["home_address"] = v6
			}
			if cmd.Flags().Changed("home-email") {
				body["home_email"] = v7
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v8
			}
			if cmd.Flags().Changed("job-position") {
				body["job_position"] = v9
			}
			if cmd.Flags().Changed("lastname") {
				body["lastname"] = v10
			}
			if cmd.Flags().Changed("mobile-phone") {
				body["mobile_phone"] = v11
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v12
			}
			if cmd.Flags().Changed("organization-id") {
				body["organization_id"] = v13
			}
			if cmd.Flags().Changed("salutation") {
				body["salutation"] = v14
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v15
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v16
			}
			if cmd.Flags().Changed("work-address") {
				body["work_address"] = v17
			}
			if cmd.Flags().Changed("work-email") {
				body["work_email"] = v18
			}
			if cmd.Flags().Changed("work-fax") {
				body["work_fax"] = v19
			}
			if cmd.Flags().Changed("work-phone") {
				body["work_phone"] = v20
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "bday", "", "")
	f.StringVar(&v1, "birthday", "", "")
	f.IntVar(&v2, "company-id", 0, "")
	f.IntVar(&v3, "customer-id", 0, "")
	f.StringVar(&v4, "firstname", "", "")
	f.StringVar(&v5, "gender", "", "")
	f.StringVar(&v6, "home-address", "", "")
	f.StringVar(&v7, "home-email", "", "")
	f.StringVar(&v8, "info", "", "")
	f.StringVar(&v9, "job-position", "", "")
	f.StringVar(&v10, "lastname", "", "")
	f.StringVar(&v11, "mobile-phone", "", "")
	f.StringVar(&v12, "name", "", "")
	f.IntVar(&v13, "organization-id", 0, "")
	f.StringVar(&v14, "salutation", "", "")
	f.StringVar(&v15, "title", "", "")
	f.IntVar(&v16, "user-id", 0, "")
	f.StringVar(&v17, "work-address", "", "")
	f.StringVar(&v18, "work-email", "", "")
	f.StringVar(&v19, "work-fax", "", "")
	f.StringVar(&v20, "work-phone", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newContactsUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 int
	var v3 int
	var v4 string
	var v5 string
	var v6 string
	var v7 string
	var v8 string
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 int
	var v14 string
	var v15 string
	var v16 int
	var v17 string
	var v18 string
	var v19 string
	var v20 string
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Kontakt aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/contacts/people/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("bday") {
				body["bday"] = v0
			}
			if cmd.Flags().Changed("birthday") {
				body["birthday"] = v1
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v2
			}
			if cmd.Flags().Changed("customer-id") {
				body["customer_id"] = v3
			}
			if cmd.Flags().Changed("firstname") {
				body["firstname"] = v4
			}
			if cmd.Flags().Changed("gender") {
				body["gender"] = v5
			}
			if cmd.Flags().Changed("home-address") {
				body["home_address"] = v6
			}
			if cmd.Flags().Changed("home-email") {
				body["home_email"] = v7
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v8
			}
			if cmd.Flags().Changed("job-position") {
				body["job_position"] = v9
			}
			if cmd.Flags().Changed("lastname") {
				body["lastname"] = v10
			}
			if cmd.Flags().Changed("mobile-phone") {
				body["mobile_phone"] = v11
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v12
			}
			if cmd.Flags().Changed("organization-id") {
				body["organization_id"] = v13
			}
			if cmd.Flags().Changed("salutation") {
				body["salutation"] = v14
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v15
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v16
			}
			if cmd.Flags().Changed("work-address") {
				body["work_address"] = v17
			}
			if cmd.Flags().Changed("work-email") {
				body["work_email"] = v18
			}
			if cmd.Flags().Changed("work-fax") {
				body["work_fax"] = v19
			}
			if cmd.Flags().Changed("work-phone") {
				body["work_phone"] = v20
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "bday", "", "")
	f.StringVar(&v1, "birthday", "", "")
	f.IntVar(&v2, "company-id", 0, "")
	f.IntVar(&v3, "customer-id", 0, "")
	f.StringVar(&v4, "firstname", "", "")
	f.StringVar(&v5, "gender", "", "")
	f.StringVar(&v6, "home-address", "", "")
	f.StringVar(&v7, "home-email", "", "")
	f.StringVar(&v8, "info", "", "")
	f.StringVar(&v9, "job-position", "", "")
	f.StringVar(&v10, "lastname", "", "")
	f.StringVar(&v11, "mobile-phone", "", "")
	f.StringVar(&v12, "name", "", "")
	f.IntVar(&v13, "organization-id", 0, "")
	f.StringVar(&v14, "salutation", "", "")
	f.StringVar(&v15, "title", "", "")
	f.IntVar(&v16, "user-id", 0, "")
	f.StringVar(&v17, "work-address", "", "")
	f.StringVar(&v18, "work-email", "", "")
	f.StringVar(&v19, "work-fax", "", "")
	f.StringVar(&v20, "work-phone", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
