// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newDealsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "deals",
		Short: "Leads verwalten",
	}
	cmd.AddCommand(
		newDealsCreateCmd(app),
		newDealsDeleteCmd(app),
		newDealsGetCmd(app),
		newDealsListCmd(app),
		newDealsPatchCmd(app),
		newDealsUpdateCmd(app),
	)
	return cmd
}

func newDealsCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 int
	var v2 string
	var v3 int
	var v4 int
	var v5 string
	var v6 float64
	var v7 string
	var v8 int
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 int
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Lead erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/deals"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("closed-on") {
				body["closed_on"] = v0
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v1
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v2
			}
			if cmd.Flags().Changed("customer-id") {
				body["customer_id"] = v3
			}
			if cmd.Flags().Changed("deal-category-id") {
				body["deal_category_id"] = v4
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v5
			}
			if cmd.Flags().Changed("money") {
				body["money"] = v6
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v7
			}
			if cmd.Flags().Changed("person-id") {
				body["person_id"] = v8
			}
			if cmd.Flags().Changed("reminder-date") {
				body["reminder_date"] = v9
			}
			if cmd.Flags().Changed("service-period-from") {
				body["service_period_from"] = v10
			}
			if cmd.Flags().Changed("service-period-to") {
				body["service_period_to"] = v11
			}
			if cmd.Flags().Changed("status") {
				body["status"] = v12
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v13
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "closed-on", "", "")
	f.IntVar(&v1, "company-id", 0, "Company/customer ID.")
	f.StringVar(&v2, "currency", "", "")
	f.IntVar(&v3, "customer-id", 0, "Deprecated alias for `company_id`.")
	f.IntVar(&v4, "deal-category-id", 0, "Deal category ID.")
	f.StringVar(&v5, "info", "", "")
	f.Float64Var(&v6, "money", 0, "Deal value in selected currency.")
	f.StringVar(&v7, "name", "", "")
	f.IntVar(&v8, "person-id", 0, "Linked contact person ID.")
	f.StringVar(&v9, "reminder-date", "", "")
	f.StringVar(&v10, "service-period-from", "", "")
	f.StringVar(&v11, "service-period-to", "", "")
	f.StringVar(&v12, "status", "", "")
	f.IntVar(&v13, "user-id", 0, "Responsible user ID.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newDealsDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Lead löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/deals/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newDealsGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Lead abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/deals/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newDealsListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 int
	var q3 string
	var q4 string
	var q5 int
	var q6 int
	var q7 string
	var q8 string
	var q9 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Leads auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/deals"
			q := url.Values{}
			if cmd.Flags().Changed("closed-from") {
				q.Set("closed_from", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("closed-to") {
				q.Set("closed_to", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("company-id") {
				q.Set("company_id", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("custom-properties") {
				q.Set("custom_properties", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("status") {
				q.Set("status", fmt.Sprint(q7))
			}
			if cmd.Flags().Changed("tags") {
				q.Set("tags", fmt.Sprint(q8))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q9))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "closed-from", "", "Closed date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q1, "closed-to", "", "Closed date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.IntVar(&q2, "company-id", 0, "")
	f.StringVar(&q3, "custom-properties", "", "Filter by custom field values.")
	f.StringVar(&q4, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q5, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q6, "per-page", 0, "Page size.")
	f.StringVar(&q7, "status", "", "")
	f.StringVar(&q8, "tags", "", "Comma-separated list of deal tag names.")
	f.StringVar(&q9, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newDealsPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 int
	var v2 string
	var v3 int
	var v4 int
	var v5 string
	var v6 float64
	var v7 string
	var v8 int
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 int
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Lead teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/deals/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("closed-on") {
				body["closed_on"] = v0
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v1
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v2
			}
			if cmd.Flags().Changed("customer-id") {
				body["customer_id"] = v3
			}
			if cmd.Flags().Changed("deal-category-id") {
				body["deal_category_id"] = v4
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v5
			}
			if cmd.Flags().Changed("money") {
				body["money"] = v6
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v7
			}
			if cmd.Flags().Changed("person-id") {
				body["person_id"] = v8
			}
			if cmd.Flags().Changed("reminder-date") {
				body["reminder_date"] = v9
			}
			if cmd.Flags().Changed("service-period-from") {
				body["service_period_from"] = v10
			}
			if cmd.Flags().Changed("service-period-to") {
				body["service_period_to"] = v11
			}
			if cmd.Flags().Changed("status") {
				body["status"] = v12
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v13
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "closed-on", "", "")
	f.IntVar(&v1, "company-id", 0, "Company/customer ID.")
	f.StringVar(&v2, "currency", "", "")
	f.IntVar(&v3, "customer-id", 0, "Deprecated alias for `company_id`.")
	f.IntVar(&v4, "deal-category-id", 0, "Deal category ID.")
	f.StringVar(&v5, "info", "", "")
	f.Float64Var(&v6, "money", 0, "Deal value in selected currency.")
	f.StringVar(&v7, "name", "", "")
	f.IntVar(&v8, "person-id", 0, "Linked contact person ID.")
	f.StringVar(&v9, "reminder-date", "", "")
	f.StringVar(&v10, "service-period-from", "", "")
	f.StringVar(&v11, "service-period-to", "", "")
	f.StringVar(&v12, "status", "", "")
	f.IntVar(&v13, "user-id", 0, "Responsible user ID.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newDealsUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 int
	var v2 string
	var v3 int
	var v4 int
	var v5 string
	var v6 float64
	var v7 string
	var v8 int
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 int
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Lead aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/deals/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("closed-on") {
				body["closed_on"] = v0
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v1
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v2
			}
			if cmd.Flags().Changed("customer-id") {
				body["customer_id"] = v3
			}
			if cmd.Flags().Changed("deal-category-id") {
				body["deal_category_id"] = v4
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v5
			}
			if cmd.Flags().Changed("money") {
				body["money"] = v6
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v7
			}
			if cmd.Flags().Changed("person-id") {
				body["person_id"] = v8
			}
			if cmd.Flags().Changed("reminder-date") {
				body["reminder_date"] = v9
			}
			if cmd.Flags().Changed("service-period-from") {
				body["service_period_from"] = v10
			}
			if cmd.Flags().Changed("service-period-to") {
				body["service_period_to"] = v11
			}
			if cmd.Flags().Changed("status") {
				body["status"] = v12
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v13
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "closed-on", "", "")
	f.IntVar(&v1, "company-id", 0, "Company/customer ID.")
	f.StringVar(&v2, "currency", "", "")
	f.IntVar(&v3, "customer-id", 0, "Deprecated alias for `company_id`.")
	f.IntVar(&v4, "deal-category-id", 0, "Deal category ID.")
	f.StringVar(&v5, "info", "", "")
	f.Float64Var(&v6, "money", 0, "Deal value in selected currency.")
	f.StringVar(&v7, "name", "", "")
	f.IntVar(&v8, "person-id", 0, "Linked contact person ID.")
	f.StringVar(&v9, "reminder-date", "", "")
	f.StringVar(&v10, "service-period-from", "", "")
	f.StringVar(&v11, "service-period-to", "", "")
	f.StringVar(&v12, "status", "", "")
	f.IntVar(&v13, "user-id", 0, "Responsible user ID.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
