// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newDealCategoriesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "deal-categories",
		Short: "Akquise-Stufen verwalten",
	}
	cmd.AddCommand(
		newDealCategoriesCreateCmd(app),
		newDealCategoriesDeleteCmd(app),
		newDealCategoriesGetCmd(app),
		newDealCategoriesListCmd(app),
		newDealCategoriesPatchCmd(app),
		newDealCategoriesUpdateCmd(app),
	)
	return cmd
}

func newDealCategoriesCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 int
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Akquise-Stufe erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/deal_categories"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v0
			}
			if cmd.Flags().Changed("probability") {
				body["probability"] = v1
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "name", "", "")
	f.IntVar(&v1, "probability", 0, "Probability in percent (0-100).")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newDealCategoriesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Akquise-Stufe löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/deal_categories/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newDealCategoriesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Akquise-Stufe abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/deal_categories/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newDealCategoriesListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 int
	var q2 int
	var q3 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Akquise-Stufen auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/deal_categories"
			q := url.Values{}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q3))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q1, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q2, "per-page", 0, "Page size.")
	f.StringVar(&q3, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newDealCategoriesPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 int
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Akquise-Stufe teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/deal_categories/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v0
			}
			if cmd.Flags().Changed("probability") {
				body["probability"] = v1
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "name", "", "")
	f.IntVar(&v1, "probability", 0, "Probability in percent (0-100).")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newDealCategoriesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 int
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Akquise-Stufe aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/deal_categories/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v0
			}
			if cmd.Flags().Changed("probability") {
				body["probability"] = v1
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "name", "", "")
	f.IntVar(&v1, "probability", 0, "Probability in percent (0-100).")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
