// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newExpensesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "expenses",
		Short: "Spesen verwalten",
	}
	cmd.AddCommand(
		newExpensesBulkCreateCmd(app),
		newExpensesCreateCmd(app),
		newExpensesDeleteCmd(app),
		newExpensesDisregardCmd(app),
		newExpensesGetCmd(app),
		newExpensesListCmd(app),
		newExpensesListAllCmd(app),
		newExpensesPatchCmd(app),
		newExpensesUpdateCmd(app),
	)
	return cmd
}

func newExpensesBulkCreateCmd(app *cli.App) *cobra.Command {
	var data string
	cmd := &cobra.Command{
		Use:   "bulk-create <project-id>",
		Short: "Projekt-Spesen als Stapel erstellen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/expenses/bulk"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newExpensesCreateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 bool
	var v2 float64
	var v3 string
	var v4 string
	var v5 string
	var v6 float64
	var v7 bool
	var v8 float64
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 float64
	var v14 float64
	var v15 int
	var data string
	cmd := &cobra.Command{
		Use:   "create <project-id>",
		Short: "Spese erstellen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/expenses"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("budget-relevant") {
				body["budget_relevant"] = v1
			}
			if cmd.Flags().Changed("cost-total-planned") {
				body["cost_total_planned"] = v2
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v3
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v4
			}
			if cmd.Flags().Changed("planned-purchase-date") {
				body["planned_purchase_date"] = v5
			}
			if cmd.Flags().Changed("price") {
				body["price"] = v6
			}
			if cmd.Flags().Changed("purchase-assignment-locked") {
				body["purchase_assignment_locked"] = v7
			}
			if cmd.Flags().Changed("quantity") {
				body["quantity"] = v8
			}
			if cmd.Flags().Changed("service-period-from") {
				body["service_period_from"] = v9
			}
			if cmd.Flags().Changed("service-period-to") {
				body["service_period_to"] = v10
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v11
			}
			if cmd.Flags().Changed("unit") {
				body["unit"] = v12
			}
			if cmd.Flags().Changed("unit-cost") {
				body["unit_cost"] = v13
			}
			if cmd.Flags().Changed("unit-price") {
				body["unit_price"] = v14
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v15
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "Whether this expense can be billed.")
	f.BoolVar(&v1, "budget-relevant", false, "Whether this expense affects project budget.")
	f.Float64Var(&v2, "cost-total-planned", 0, "Planned internal cost total.")
	f.StringVar(&v3, "date", "", "Expense date.")
	f.StringVar(&v4, "description", "", "Expense description text.")
	f.StringVar(&v5, "planned-purchase-date", "", "Planned purchase date (when planned purchases are enabled).")
	f.Float64Var(&v6, "price", 0, "Deprecated total selling price alias.")
	f.BoolVar(&v7, "purchase-assignment-locked", false, "Locks assignment to purchase items.")
	f.Float64Var(&v8, "quantity", 0, "Quantity.")
	f.StringVar(&v9, "service-period-from", "", "Start of service period.")
	f.StringVar(&v10, "service-period-to", "", "End of service period.")
	f.StringVar(&v11, "title", "", "Expense title.")
	f.StringVar(&v12, "unit", "", "Unit label.")
	f.Float64Var(&v13, "unit-cost", 0, "Unit internal cost.")
	f.Float64Var(&v14, "unit-price", 0, "Unit selling price.")
	f.IntVar(&v15, "user-id", 0, "Responsible user ID (must be active on create).")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newExpensesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <project-id> <id>",
		Short: "Spese löschen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/expenses/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newExpensesDisregardCmd(app *cli.App) *cobra.Command {
	var v0 string
	var data string
	cmd := &cobra.Command{
		Use:   "disregard <project-id>",
		Short: "Projekt-Spesen von der Verrechnung ausnehmen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/expenses/disregard"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("reason") {
				body["reason"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "reason", "", "Reason shown in history/audit context.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newExpensesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <project-id> <id>",
		Short: "Spese abrufen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/expenses/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newExpensesListCmd(app *cli.App) *cobra.Command {
	var q0 bool
	var q1 bool
	var q2 bool
	var q3 string
	var q4 int
	var q5 int
	var q6 string
	var q7 int
	cmd := &cobra.Command{
		Use:   "list <project-id>",
		Short: "Spesen auflisten",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/expenses"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			q := url.Values{}
			if cmd.Flags().Changed("billable") {
				q.Set("billable", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("billed") {
				q.Set("billed", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("budget-relevant") {
				q.Set("budget_relevant", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("custom-properties") {
				q.Set("custom_properties", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("user-id") {
				q.Set("user_id", fmt.Sprint(q7))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&q0, "billable", false, "")
	f.BoolVar(&q1, "billed", false, "")
	f.BoolVar(&q2, "budget-relevant", false, "")
	f.StringVar(&q3, "custom-properties", "", "Filter by custom field values.")
	f.IntVar(&q4, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q5, "per-page", 0, "Page size.")
	f.StringVar(&q6, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	f.IntVar(&q7, "user-id", 0, "")
	return cmd
}

func newExpensesListAllCmd(app *cli.App) *cobra.Command {
	var q0 bool
	var q1 bool
	var q2 bool
	var q3 string
	var q4 string
	var q5 string
	var q6 int
	var q7 int
	var q8 string
	var q9 string
	var q10 string
	var q11 int
	cmd := &cobra.Command{
		Use:   "list-all",
		Short: "Spesen über alle Projekte auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/expenses"
			q := url.Values{}
			if cmd.Flags().Changed("billable") {
				q.Set("billable", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("billed") {
				q.Set("billed", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("budget-relevant") {
				q.Set("budget_relevant", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("custom-properties") {
				q.Set("custom_properties", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("from") {
				q.Set("from", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q7))
			}
			if cmd.Flags().Changed("tags") {
				q.Set("tags", fmt.Sprint(q8))
			}
			if cmd.Flags().Changed("to") {
				q.Set("to", fmt.Sprint(q9))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q10))
			}
			if cmd.Flags().Changed("user-id") {
				q.Set("user_id", fmt.Sprint(q11))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&q0, "billable", false, "")
	f.BoolVar(&q1, "billed", false, "")
	f.BoolVar(&q2, "budget-relevant", false, "")
	f.StringVar(&q3, "custom-properties", "", "Filter by custom field values.")
	f.StringVar(&q4, "from", "", "Expense date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q5, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q6, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q7, "per-page", 0, "Page size.")
	f.StringVar(&q8, "tags", "", "Comma-separated project tag names.")
	f.StringVar(&q9, "to", "", "Expense date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q10, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	f.IntVar(&q11, "user-id", 0, "")
	return cmd
}

func newExpensesPatchCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 bool
	var v2 float64
	var v3 string
	var v4 string
	var v5 string
	var v6 float64
	var v7 bool
	var v8 float64
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 float64
	var v14 float64
	var v15 int
	var data string
	cmd := &cobra.Command{
		Use:   "patch <project-id> <id>",
		Short: "Spese teilweise aktualisieren",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/expenses/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("budget-relevant") {
				body["budget_relevant"] = v1
			}
			if cmd.Flags().Changed("cost-total-planned") {
				body["cost_total_planned"] = v2
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v3
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v4
			}
			if cmd.Flags().Changed("planned-purchase-date") {
				body["planned_purchase_date"] = v5
			}
			if cmd.Flags().Changed("price") {
				body["price"] = v6
			}
			if cmd.Flags().Changed("purchase-assignment-locked") {
				body["purchase_assignment_locked"] = v7
			}
			if cmd.Flags().Changed("quantity") {
				body["quantity"] = v8
			}
			if cmd.Flags().Changed("service-period-from") {
				body["service_period_from"] = v9
			}
			if cmd.Flags().Changed("service-period-to") {
				body["service_period_to"] = v10
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v11
			}
			if cmd.Flags().Changed("unit") {
				body["unit"] = v12
			}
			if cmd.Flags().Changed("unit-cost") {
				body["unit_cost"] = v13
			}
			if cmd.Flags().Changed("unit-price") {
				body["unit_price"] = v14
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v15
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "Whether this expense can be billed.")
	f.BoolVar(&v1, "budget-relevant", false, "Whether this expense affects project budget.")
	f.Float64Var(&v2, "cost-total-planned", 0, "Planned internal cost total.")
	f.StringVar(&v3, "date", "", "Expense date.")
	f.StringVar(&v4, "description", "", "Expense description text.")
	f.StringVar(&v5, "planned-purchase-date", "", "Planned purchase date (when planned purchases are enabled).")
	f.Float64Var(&v6, "price", 0, "Deprecated total selling price alias.")
	f.BoolVar(&v7, "purchase-assignment-locked", false, "Locks assignment to purchase items.")
	f.Float64Var(&v8, "quantity", 0, "Quantity.")
	f.StringVar(&v9, "service-period-from", "", "Start of service period.")
	f.StringVar(&v10, "service-period-to", "", "End of service period.")
	f.StringVar(&v11, "title", "", "Expense title.")
	f.StringVar(&v12, "unit", "", "Unit label.")
	f.Float64Var(&v13, "unit-cost", 0, "Unit internal cost.")
	f.Float64Var(&v14, "unit-price", 0, "Unit selling price.")
	f.IntVar(&v15, "user-id", 0, "Responsible user ID (must be active on create).")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newExpensesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 bool
	var v2 float64
	var v3 string
	var v4 string
	var v5 string
	var v6 float64
	var v7 bool
	var v8 float64
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 float64
	var v14 float64
	var v15 int
	var data string
	cmd := &cobra.Command{
		Use:   "update <project-id> <id>",
		Short: "Spese aktualisieren",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/expenses/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("budget-relevant") {
				body["budget_relevant"] = v1
			}
			if cmd.Flags().Changed("cost-total-planned") {
				body["cost_total_planned"] = v2
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v3
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v4
			}
			if cmd.Flags().Changed("planned-purchase-date") {
				body["planned_purchase_date"] = v5
			}
			if cmd.Flags().Changed("price") {
				body["price"] = v6
			}
			if cmd.Flags().Changed("purchase-assignment-locked") {
				body["purchase_assignment_locked"] = v7
			}
			if cmd.Flags().Changed("quantity") {
				body["quantity"] = v8
			}
			if cmd.Flags().Changed("service-period-from") {
				body["service_period_from"] = v9
			}
			if cmd.Flags().Changed("service-period-to") {
				body["service_period_to"] = v10
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v11
			}
			if cmd.Flags().Changed("unit") {
				body["unit"] = v12
			}
			if cmd.Flags().Changed("unit-cost") {
				body["unit_cost"] = v13
			}
			if cmd.Flags().Changed("unit-price") {
				body["unit_price"] = v14
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v15
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "Whether this expense can be billed.")
	f.BoolVar(&v1, "budget-relevant", false, "Whether this expense affects project budget.")
	f.Float64Var(&v2, "cost-total-planned", 0, "Planned internal cost total.")
	f.StringVar(&v3, "date", "", "Expense date.")
	f.StringVar(&v4, "description", "", "Expense description text.")
	f.StringVar(&v5, "planned-purchase-date", "", "Planned purchase date (when planned purchases are enabled).")
	f.Float64Var(&v6, "price", 0, "Deprecated total selling price alias.")
	f.BoolVar(&v7, "purchase-assignment-locked", false, "Locks assignment to purchase items.")
	f.Float64Var(&v8, "quantity", 0, "Quantity.")
	f.StringVar(&v9, "service-period-from", "", "Start of service period.")
	f.StringVar(&v10, "service-period-to", "", "End of service period.")
	f.StringVar(&v11, "title", "", "Expense title.")
	f.StringVar(&v12, "unit", "", "Unit label.")
	f.Float64Var(&v13, "unit-cost", 0, "Unit internal cost.")
	f.Float64Var(&v14, "unit-price", 0, "Unit selling price.")
	f.IntVar(&v15, "user-id", 0, "Responsible user ID (must be active on create).")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
