// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newInvoiceBookkeepingExportsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "invoice-bookkeeping-exports",
		Short: "Buchhaltungsexporte verwalten",
	}
	cmd.AddCommand(
		newInvoiceBookkeepingExportsCreateCmd(app),
		newInvoiceBookkeepingExportsGetCmd(app),
		newInvoiceBookkeepingExportsListCmd(app),
	)
	return cmd
}

func newInvoiceBookkeepingExportsCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 bool
	var v2 bool
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Buchhaltungsexport erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/bookkeeping_exports"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("comment") {
				body["comment"] = v0
			}
			if cmd.Flags().Changed("trigger-submission") {
				body["trigger_submission"] = v1
			}
			if cmd.Flags().Changed("with-direct-online-submission") {
				body["with_direct_online_submission"] = v2
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "comment", "", "")
	f.BoolVar(&v1, "trigger-submission", false, "")
	f.BoolVar(&v2, "with-direct-online-submission", false, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newInvoiceBookkeepingExportsGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Buchhaltungsexport abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/bookkeeping_exports/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newInvoiceBookkeepingExportsListCmd(app *cli.App) *cobra.Command {
	var q0 int
	var q1 int
	var q2 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Buchhaltungsexporte auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/bookkeeping_exports"
			q := url.Values{}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q2))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q1, "per-page", 0, "Page size.")
	f.StringVar(&q2, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}
