// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newInvoicePaymentsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "invoice-payments",
		Short: "Zahlungen verwalten",
	}
	cmd.AddCommand(
		newInvoicePaymentsBulkCreateCmd(app),
		newInvoicePaymentsCreateCmd(app),
		newInvoicePaymentsDeleteCmd(app),
		newInvoicePaymentsGetCmd(app),
		newInvoicePaymentsListCmd(app),
		newInvoicePaymentsPatchCmd(app),
		newInvoicePaymentsUpdateCmd(app),
	)
	return cmd
}

func newInvoicePaymentsBulkCreateCmd(app *cli.App) *cobra.Command {
	var data string
	cmd := &cobra.Command{
		Use:   "bulk-create",
		Short: "Zahlungen als Stapel erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/payments/bulk"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newInvoicePaymentsCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var v3 int
	var v4 float64
	var v5 bool
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Zahlung erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/payments"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v0
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v1
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v2
			}
			if cmd.Flags().Changed("invoice-id") {
				body["invoice_id"] = v3
			}
			if cmd.Flags().Changed("paid-total") {
				body["paid_total"] = v4
			}
			if cmd.Flags().Changed("partially-paid") {
				body["partially_paid"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "currency", "", "")
	f.StringVar(&v1, "date", "", "")
	f.StringVar(&v2, "description", "", "")
	f.IntVar(&v3, "invoice-id", 0, "")
	f.Float64Var(&v4, "paid-total", 0, "")
	f.BoolVar(&v5, "partially-paid", false, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newInvoicePaymentsDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Zahlung löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/payments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newInvoicePaymentsGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Zahlung abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/payments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newInvoicePaymentsListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 string
	var q3 int
	var q4 int
	var q5 int
	var q6 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Zahlungen auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/payments"
			q := url.Values{}
			if cmd.Flags().Changed("date-from") {
				q.Set("date_from", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("date-to") {
				q.Set("date_to", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("invoice-id") {
				q.Set("invoice_id", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q6))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "date-from", "", "Payment date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q1, "date-to", "", "Payment date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q2, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q3, "invoice-id", 0, "")
	f.IntVar(&q4, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q5, "per-page", 0, "Page size.")
	f.StringVar(&q6, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newInvoicePaymentsPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var v3 int
	var v4 float64
	var v5 bool
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Zahlung teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/payments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v0
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v1
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v2
			}
			if cmd.Flags().Changed("invoice-id") {
				body["invoice_id"] = v3
			}
			if cmd.Flags().Changed("paid-total") {
				body["paid_total"] = v4
			}
			if cmd.Flags().Changed("partially-paid") {
				body["partially_paid"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "currency", "", "")
	f.StringVar(&v1, "date", "", "")
	f.StringVar(&v2, "description", "", "")
	f.IntVar(&v3, "invoice-id", 0, "")
	f.Float64Var(&v4, "paid-total", 0, "")
	f.BoolVar(&v5, "partially-paid", false, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newInvoicePaymentsUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var v3 int
	var v4 float64
	var v5 bool
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Zahlung aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/payments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v0
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v1
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v2
			}
			if cmd.Flags().Changed("invoice-id") {
				body["invoice_id"] = v3
			}
			if cmd.Flags().Changed("paid-total") {
				body["paid_total"] = v4
			}
			if cmd.Flags().Changed("partially-paid") {
				body["partially_paid"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "currency", "", "")
	f.StringVar(&v1, "date", "", "")
	f.StringVar(&v2, "description", "", "")
	f.IntVar(&v3, "invoice-id", 0, "")
	f.Float64Var(&v4, "paid-total", 0, "")
	f.BoolVar(&v5, "partially-paid", false, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
