// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newInvoiceAttachmentsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "invoice-attachments",
		Short: "Rechnungsanhänge verwalten",
	}
	cmd.AddCommand(
		newInvoiceAttachmentsCreateCmd(app),
		newInvoiceAttachmentsDeleteCmd(app),
		newInvoiceAttachmentsListCmd(app),
	)
	return cmd
}

func newInvoiceAttachmentsCreateCmd(app *cli.App) *cobra.Command {
	var data string
	cmd := &cobra.Command{
		Use:   "create <invoice-id>",
		Short: "Rechnungsanhang erstellen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/{invoice_id}/attachments"
			path = strings.Replace(path, "{invoice_id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newInvoiceAttachmentsDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <invoice-id> <id>",
		Short: "Rechnungsanhang löschen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/{invoice_id}/attachments/{id}"
			path = strings.Replace(path, "{invoice_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newInvoiceAttachmentsListCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list <invoice-id>",
		Short: "Rechnungsanhänge auflisten",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/{invoice_id}/attachments"
			path = strings.Replace(path, "{invoice_id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}
