// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newInvoicesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "invoices",
		Short: "Rechnungen verwalten",
	}
	cmd.AddCommand(
		newInvoicesCreateCmd(app),
		newInvoicesDeleteCmd(app),
		newInvoicesExpensesListCmd(app),
		newInvoicesGetCmd(app),
		newInvoicesListCmd(app),
		newInvoicesLockedListCmd(app),
		newInvoicesPdfCmd(app),
		newInvoicesSendEmailCmd(app),
		newInvoicesTimesheetGetCmd(app),
		newInvoicesTimesheetPdfCmd(app),
		newInvoicesUpdateStatusCmd(app),
	)
	return cmd
}

func newInvoicesCreateCmd(app *cli.App) *cobra.Command {
	var v0 float64
	var v1 int
	var v2 string
	var v3 string
	var v4 int
	var v5 string
	var v6 int
	var v7 string
	var v8 float64
	var v9 string
	var v10 string
	var v11 string
	var v12 int
	var v13 int
	var v14 int
	var v15 bool
	var v16 int
	var v17 string
	var v18 string
	var v19 string
	var v20 string
	var v21 string
	var v22 float64
	var v23 string
	var v24 bool
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Rechnung erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("cash-discount") {
				body["cash_discount"] = v0
			}
			if cmd.Flags().Changed("cash-discount-days") {
				body["cash_discount_days"] = v1
			}
			if cmd.Flags().Changed("category") {
				body["category"] = v2
			}
			if cmd.Flags().Changed("change-address") {
				body["change_address"] = v3
			}
			if cmd.Flags().Changed("contact-id") {
				body["contact_id"] = v4
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v5
			}
			if cmd.Flags().Changed("customer-id") {
				body["customer_id"] = v6
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v7
			}
			if cmd.Flags().Changed("discount") {
				body["discount"] = v8
			}
			if cmd.Flags().Changed("due-date") {
				body["due_date"] = v9
			}
			if cmd.Flags().Changed("footer") {
				body["footer"] = v10
			}
			if cmd.Flags().Changed("identifier") {
				body["identifier"] = v11
			}
			if cmd.Flags().Changed("internal-contact-id") {
				body["internal_contact_id"] = v12
			}
			if cmd.Flags().Changed("letter-paper-id") {
				body["letter_paper_id"] = v13
			}
			if cmd.Flags().Changed("offer-id") {
				body["offer_id"] = v14
			}
			if cmd.Flags().Changed("print-detail-columns") {
				body["print_detail_columns"] = v15
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v16
			}
			if cmd.Flags().Changed("recipient-address") {
				body["recipient_address"] = v17
			}
			if cmd.Flags().Changed("salutation") {
				body["salutation"] = v18
			}
			if cmd.Flags().Changed("service-period-from") {
				body["service_period_from"] = v19
			}
			if cmd.Flags().Changed("service-period-to") {
				body["service_period_to"] = v20
			}
			if cmd.Flags().Changed("status") {
				body["status"] = v21
			}
			if cmd.Flags().Changed("tax") {
				body["tax"] = v22
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v23
			}
			if cmd.Flags().Changed("without-letter-paper") {
				body["without_letter_paper"] = v24
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.Float64Var(&v0, "cash-discount", 0, "Cash discount percentage.")
	f.IntVar(&v1, "cash-discount-days", 0, "Cash discount validity in days.")
	f.StringVar(&v2, "category", "", "Invoice category.")
	f.StringVar(&v3, "change-address", "", "Replace recipient address from selected source.")
	f.IntVar(&v4, "contact-id", 0, "External contact person ID.")
	f.StringVar(&v5, "currency", "", "Currency code.")
	f.IntVar(&v6, "customer-id", 0, "Customer company ID.")
	f.StringVar(&v7, "date", "", "Invoice date.")
	f.Float64Var(&v8, "discount", 0, "Discount value.")
	f.StringVar(&v9, "due-date", "", "Due date.")
	f.StringVar(&v10, "footer", "", "Footer text. Supports template variables such as `{identifier}`, `{gross_total}`, `{net_total}`, `{user}`, `{me}`, and more.")
	f.StringVar(&v11, "identifier", "", "Optional custom invoice number.")
	f.IntVar(&v12, "internal-contact-id", 0, "Internal contact user ID.")
	f.IntVar(&v13, "letter-paper-id", 0, "Letter paper ID to use for this invoice. When omitted, the account's default invoice letter paper is used. If `without_letter_paper` is set to `true`, this field is ignored. Available letter papers can be fetched via `GET /api/v1/letter_papers`.")
	f.IntVar(&v14, "offer-id", 0, "Optional source offer ID.")
	f.BoolVar(&v15, "print-detail-columns", false, "Include detailed columns in print layouts.")
	f.IntVar(&v16, "project-id", 0, "Optional project ID.")
	f.StringVar(&v17, "recipient-address", "", "Recipient address.")
	f.StringVar(&v18, "salutation", "", "Salutation text. Supports template variables such as `{salutation}`, `{recipient}`, `{company_name}`, `{date}`, `{due_date}`, and more.")
	f.StringVar(&v19, "service-period-from", "", "Service period start. Use together with `service_period_to`.")
	f.StringVar(&v20, "service-period-to", "", "Service period end. Use together with `service_period_from`.")
	f.StringVar(&v21, "status", "", "Initial invoice status.")
	f.Float64Var(&v22, "tax", 0, "VAT/tax percentage.")
	f.StringVar(&v23, "title", "", "Invoice title.")
	f.BoolVar(&v24, "without-letter-paper", false, "When set to `true`, creates the invoice without letter paper (white). This takes precedence over `letter_paper_id`.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newInvoicesDeleteCmd(app *cli.App) *cobra.Command {
	var v0 string
	var data string
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Rechnung löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("reason") {
				body["reason"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "reason", "", "Human-readable deletion reason for audit/history.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newInvoicesExpensesListCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "expenses-list <id>",
		Short: "Rechnungs-Spesen auflisten",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/{id}/expenses"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newInvoicesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Rechnung abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newInvoicesListCmd(app *cli.App) *cobra.Command {
	var q0 int
	var q1 string
	var q2 string
	var q3 string
	var q4 string
	var q5 string
	var q6 bool
	var q7 bool
	var q8 int
	var q9 int
	var q10 int
	var q11 string
	var q12 string
	var q13 string
	var q14 string
	var q15 string
	var q16 string
	var q17 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Rechnungen auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices"
			q := url.Values{}
			if cmd.Flags().Changed("company-id") {
				q.Set("company_id", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("custom-properties") {
				q.Set("custom_properties", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("date-from") {
				q.Set("date_from", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("date-to") {
				q.Set("date_to", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("identifier") {
				q.Set("identifier", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("include-disregarded") {
				q.Set("include_disregarded", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("not-booked") {
				q.Set("not_booked", fmt.Sprint(q7))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q8))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q9))
			}
			if cmd.Flags().Changed("project-id") {
				q.Set("project_id", fmt.Sprint(q10))
			}
			if cmd.Flags().Changed("service-period-from") {
				q.Set("service_period_from", fmt.Sprint(q11))
			}
			if cmd.Flags().Changed("service-period-to") {
				q.Set("service_period_to", fmt.Sprint(q12))
			}
			if cmd.Flags().Changed("sort-by") {
				q.Set("sort_by", fmt.Sprint(q13))
			}
			if cmd.Flags().Changed("status") {
				q.Set("status", fmt.Sprint(q14))
			}
			if cmd.Flags().Changed("tags") {
				q.Set("tags", fmt.Sprint(q15))
			}
			if cmd.Flags().Changed("term") {
				q.Set("term", fmt.Sprint(q16))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q17))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "company-id", 0, "")
	f.StringVar(&q1, "custom-properties", "", "Filter by custom field values.")
	f.StringVar(&q2, "date-from", "", "Invoice date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q3, "date-to", "", "Invoice date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q4, "identifier", "", "")
	f.StringVar(&q5, "ids", "", "Comma-separated IDs.")
	f.BoolVar(&q6, "include-disregarded", false, "")
	f.BoolVar(&q7, "not-booked", false, "")
	f.IntVar(&q8, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q9, "per-page", 0, "Page size.")
	f.IntVar(&q10, "project-id", 0, "")
	f.StringVar(&q11, "service-period-from", "", "Service period start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q12, "service-period-to", "", "Service period end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q13, "sort-by", "", "Field and optional direction, e.g. `title desc`.")
	f.StringVar(&q14, "status", "", "Comma-separated API statuses.")
	f.StringVar(&q15, "tags", "", "Comma-separated list of tag names.")
	f.StringVar(&q16, "term", "", "")
	f.StringVar(&q17, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newInvoicesLockedListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 string
	var q3 int
	var q4 int
	var q5 string
	cmd := &cobra.Command{
		Use:   "locked-list",
		Short: "Gesperrte Rechnungen auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/locked"
			q := url.Values{}
			if cmd.Flags().Changed("date-from") {
				q.Set("date_from", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("date-to") {
				q.Set("date_to", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("identifier") {
				q.Set("identifier", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("status") {
				q.Set("status", fmt.Sprint(q5))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "date-from", "", "Invoice date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q1, "date-to", "", "Invoice date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q2, "identifier", "", "")
	f.IntVar(&q3, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q4, "per-page", 0, "Page size.")
	f.StringVar(&q5, "status", "", "")
	return cmd
}

func newInvoicesPdfCmd(app *cli.App) *cobra.Command {
	var q0 bool
	var q1 int
	cmd := &cobra.Command{
		Use:   "pdf <id>",
		Short: "Rechnungs-PDF herunterladen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/{id}.pdf"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			q := url.Values{}
			if cmd.Flags().Changed("blank") {
				q.Set("blank", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("letter-paper-id") {
				q.Set("letter_paper_id", fmt.Sprint(q1))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&q0, "blank", false, "Return PDF without letter paper.")
	f.IntVar(&q1, "letter-paper-id", 0, "Letter paper ID. Defaults to account default when omitted.")
	return cmd
}

func newInvoicesSendEmailCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var v3 int
	var v4 string
	var v5 string
	var data string
	cmd := &cobra.Command{
		Use:   "send-email <id>",
		Short: "Rechnung per E-Mail senden",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/{id}/send_email"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("emails-bcc") {
				body["emails_bcc"] = v0
			}
			if cmd.Flags().Changed("emails-cc") {
				body["emails_cc"] = v1
			}
			if cmd.Flags().Changed("emails-to") {
				body["emails_to"] = v2
			}
			if cmd.Flags().Changed("letter-paper-id") {
				body["letter_paper_id"] = v3
			}
			if cmd.Flags().Changed("subject") {
				body["subject"] = v4
			}
			if cmd.Flags().Changed("text") {
				body["text"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "emails-bcc", "", "BCC recipients as semicolon-separated list.")
	f.StringVar(&v1, "emails-cc", "", "CC recipients as semicolon-separated list.")
	f.StringVar(&v2, "emails-to", "", "To recipients as semicolon-separated list.")
	f.IntVar(&v3, "letter-paper-id", 0, "Optional letter paper ID used for generated PDF.")
	f.StringVar(&v4, "subject", "", "Email subject.")
	f.StringVar(&v5, "text", "", "Email body text.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newInvoicesTimesheetGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "timesheet-get <id>",
		Short: "Leistungsnachweis der Rechnung abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/{id}/timesheet"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newInvoicesTimesheetPdfCmd(app *cli.App) *cobra.Command {
	var q0 int
	cmd := &cobra.Command{
		Use:   "timesheet-pdf <id>",
		Short: "Leistungsnachweis-PDF der Rechnung herunterladen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/{id}/timesheet.pdf"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			q := url.Values{}
			if cmd.Flags().Changed("letter-paper-id") {
				q.Set("letter_paper_id", fmt.Sprint(q0))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "letter-paper-id", 0, "")
	return cmd
}

func newInvoicesUpdateStatusCmd(app *cli.App) *cobra.Command {
	var v0 string
	var data string
	cmd := &cobra.Command{
		Use:   "update-status <id>",
		Short: "Rechnungsstatus aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoices/{id}/update_status"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("status") {
				body["status"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "status", "", "Target API status.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
