// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newInvoiceRemindersCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "invoice-reminders",
		Short: "Zahlungserinnerungen verwalten",
	}
	cmd.AddCommand(
		newInvoiceRemindersCreateCmd(app),
		newInvoiceRemindersDeleteCmd(app),
		newInvoiceRemindersGetCmd(app),
		newInvoiceRemindersListCmd(app),
		newInvoiceRemindersSendEmailCmd(app),
	)
	return cmd
}

func newInvoiceRemindersCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 float64
	var v3 int
	var v4 string
	var v5 string
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Zahlungserinnerung erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoice_reminders"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v0
			}
			if cmd.Flags().Changed("due-date") {
				body["due_date"] = v1
			}
			if cmd.Flags().Changed("fee") {
				body["fee"] = v2
			}
			if cmd.Flags().Changed("invoice-id") {
				body["invoice_id"] = v3
			}
			if cmd.Flags().Changed("text") {
				body["text"] = v4
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "date", "", "")
	f.StringVar(&v1, "due-date", "", "")
	f.Float64Var(&v2, "fee", 0, "")
	f.IntVar(&v3, "invoice-id", 0, "")
	f.StringVar(&v4, "text", "", "")
	f.StringVar(&v5, "title", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newInvoiceRemindersDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Zahlungserinnerung löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoice_reminders/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newInvoiceRemindersGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Zahlungserinnerung abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoice_reminders/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newInvoiceRemindersListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 string
	var q3 int
	var q4 int
	var q5 int
	var q6 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Zahlungserinnerungen auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoice_reminders"
			q := url.Values{}
			if cmd.Flags().Changed("date-from") {
				q.Set("date_from", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("date-to") {
				q.Set("date_to", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("invoice-id") {
				q.Set("invoice_id", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q6))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "date-from", "", "Reminder date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q1, "date-to", "", "Reminder date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q2, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q3, "invoice-id", 0, "")
	f.IntVar(&q4, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q5, "per-page", 0, "Page size.")
	f.StringVar(&q6, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newInvoiceRemindersSendEmailCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var v3 string
	var v4 string
	var data string
	cmd := &cobra.Command{
		Use:   "send-email <id>",
		Short: "Zahlungserinnerung per E-Mail senden",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/invoice_reminders/{id}/send_email"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("emails-bcc") {
				body["emails_bcc"] = v0
			}
			if cmd.Flags().Changed("emails-cc") {
				body["emails_cc"] = v1
			}
			if cmd.Flags().Changed("emails-to") {
				body["emails_to"] = v2
			}
			if cmd.Flags().Changed("subject") {
				body["subject"] = v3
			}
			if cmd.Flags().Changed("text") {
				body["text"] = v4
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "emails-bcc", "", "Semicolon-separated email list.")
	f.StringVar(&v1, "emails-cc", "", "Semicolon-separated email list.")
	f.StringVar(&v2, "emails-to", "", "Semicolon-separated email list.")
	f.StringVar(&v3, "subject", "", "")
	f.StringVar(&v4, "text", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
