// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newLetterPapersCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "letter-papers",
		Short: "Briefpapiere verwalten",
	}
	cmd.AddCommand(
		newLetterPapersListCmd(app),
	)
	return cmd
}

func newLetterPapersListCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Briefpapiere auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/letter_papers"
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}
