// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newOffersCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "offers",
		Short: "Angebote verwalten",
	}
	cmd.AddCommand(
		newOffersAssignCmd(app),
		newOffersCreateCmd(app),
		newOffersGetCmd(app),
		newOffersListCmd(app),
		newOffersPdfCmd(app),
		newOffersSendEmailCmd(app),
		newOffersUpdateStatusCmd(app),
	)
	return cmd
}

func newOffersAssignCmd(app *cli.App) *cobra.Command {
	var v0 int
	var v1 int
	var v2 int
	var data string
	cmd := &cobra.Command{
		Use:   "assign <id>",
		Short: "Angebot einer Firma/einem Projekt/Deal zuordnen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/offers/{id}/assign"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v0
			}
			if cmd.Flags().Changed("deal-id") {
				body["deal_id"] = v1
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v2
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&v0, "company-id", 0, "")
	f.IntVar(&v1, "deal-id", 0, "")
	f.IntVar(&v2, "project-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newOffersCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 int
	var v2 int
	var v3 string
	var v4 string
	var v5 int
	var v6 float64
	var v7 string
	var v8 string
	var v9 string
	var v10 int
	var v11 bool
	var v12 int
	var v13 string
	var v14 string
	var v15 bool
	var v16 float64
	var v17 string
	var v18 bool
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Angebot erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/offers"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("change-address") {
				body["change_address"] = v0
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v1
			}
			if cmd.Flags().Changed("contact-id") {
				body["contact_id"] = v2
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v3
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v4
			}
			if cmd.Flags().Changed("deal-id") {
				body["deal_id"] = v5
			}
			if cmd.Flags().Changed("discount") {
				body["discount"] = v6
			}
			if cmd.Flags().Changed("due-date") {
				body["due_date"] = v7
			}
			if cmd.Flags().Changed("footer") {
				body["footer"] = v8
			}
			if cmd.Flags().Changed("identifier") {
				body["identifier"] = v9
			}
			if cmd.Flags().Changed("internal-contact-id") {
				body["internal_contact_id"] = v10
			}
			if cmd.Flags().Changed("print-detail-columns") {
				body["print_detail_columns"] = v11
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v12
			}
			if cmd.Flags().Changed("recipient-address") {
				body["recipient_address"] = v13
			}
			if cmd.Flags().Changed("salutation") {
				body["salutation"] = v14
			}
			if cmd.Flags().Changed("table-header-visible") {
				body["table_header_visible"] = v15
			}
			if cmd.Flags().Changed("tax") {
				body["tax"] = v16
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v17
			}
			if cmd.Flags().Changed("totals-section-visible") {
				body["totals_section_visible"] = v18
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "change-address", "", "")
	f.IntVar(&v1, "company-id", 0, "")
	f.IntVar(&v2, "contact-id", 0, "")
	f.StringVar(&v3, "currency", "", "")
	f.StringVar(&v4, "date", "", "")
	f.IntVar(&v5, "deal-id", 0, "")
	f.Float64Var(&v6, "discount", 0, "")
	f.StringVar(&v7, "due-date", "", "")
	f.StringVar(&v8, "footer", "", "")
	f.StringVar(&v9, "identifier", "", "")
	f.IntVar(&v10, "internal-contact-id", 0, "")
	f.BoolVar(&v11, "print-detail-columns", false, "")
	f.IntVar(&v12, "project-id", 0, "")
	f.StringVar(&v13, "recipient-address", "", "")
	f.StringVar(&v14, "salutation", "", "")
	f.BoolVar(&v15, "table-header-visible", false, "")
	f.Float64Var(&v16, "tax", 0, "Must match an active sale VAT code tax in the account.")
	f.StringVar(&v17, "title", "", "")
	f.BoolVar(&v18, "totals-section-visible", false, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newOffersGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Angebot abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/offers/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newOffersListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 string
	var q3 string
	var q4 string
	var q5 string
	var q6 int
	var q7 int
	var q8 string
	var q9 string
	var q10 string
	var q11 string
	var q12 string
	var q13 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Angebote auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/offers"
			q := url.Values{}
			if cmd.Flags().Changed("company-id") {
				q.Set("company_id", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("custom-properties") {
				q.Set("custom_properties", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("deal-id") {
				q.Set("deal_id", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("from") {
				q.Set("from", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("identifier") {
				q.Set("identifier", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q7))
			}
			if cmd.Flags().Changed("project-id") {
				q.Set("project_id", fmt.Sprint(q8))
			}
			if cmd.Flags().Changed("sort-by") {
				q.Set("sort_by", fmt.Sprint(q9))
			}
			if cmd.Flags().Changed("status") {
				q.Set("status", fmt.Sprint(q10))
			}
			if cmd.Flags().Changed("tags") {
				q.Set("tags", fmt.Sprint(q11))
			}
			if cmd.Flags().Changed("to") {
				q.Set("to", fmt.Sprint(q12))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q13))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "company-id", "", "Single ID or comma-separated list.")
	f.StringVar(&q1, "custom-properties", "", "Filter by custom field values.")
	f.StringVar(&q2, "deal-id", "", "Single ID or comma-separated list.")
	f.StringVar(&q3, "from", "", "Offer date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q4, "identifier", "", "")
	f.StringVar(&q5, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q6, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q7, "per-page", 0, "Page size.")
	f.StringVar(&q8, "project-id", "", "Single ID or comma-separated list.")
	f.StringVar(&q9, "sort-by", "", "Field and optional direction, e.g. `title desc`.")
	f.StringVar(&q10, "status", "", "")
	f.StringVar(&q11, "tags", "", "Comma-separated list of tag names.")
	f.StringVar(&q12, "to", "", "Offer date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q13, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newOffersPdfCmd(app *cli.App) *cobra.Command {
	var q0 int
	cmd := &cobra.Command{
		Use:   "pdf <id>",
		Short: "Angebots-PDF herunterladen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/offers/{id}.pdf"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			q := url.Values{}
			if cmd.Flags().Changed("letter-paper-id") {
				q.Set("letter_paper_id", fmt.Sprint(q0))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "letter-paper-id", 0, "Letter paper ID. Defaults to account default when omitted.")
	return cmd
}

func newOffersSendEmailCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var v3 int
	var v4 string
	var v5 string
	var data string
	cmd := &cobra.Command{
		Use:   "send-email <id>",
		Short: "Angebot per E-Mail senden",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/offers/{id}/send_email"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("emails-bcc") {
				body["emails_bcc"] = v0
			}
			if cmd.Flags().Changed("emails-cc") {
				body["emails_cc"] = v1
			}
			if cmd.Flags().Changed("emails-to") {
				body["emails_to"] = v2
			}
			if cmd.Flags().Changed("letter-paper-id") {
				body["letter_paper_id"] = v3
			}
			if cmd.Flags().Changed("subject") {
				body["subject"] = v4
			}
			if cmd.Flags().Changed("text") {
				body["text"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "emails-bcc", "", "Semicolon-separated email list.")
	f.StringVar(&v1, "emails-cc", "", "Semicolon-separated email list.")
	f.StringVar(&v2, "emails-to", "", "Semicolon-separated email list.")
	f.IntVar(&v3, "letter-paper-id", 0, "")
	f.StringVar(&v4, "subject", "", "")
	f.StringVar(&v5, "text", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newOffersUpdateStatusCmd(app *cli.App) *cobra.Command {
	var v0 string
	var data string
	cmd := &cobra.Command{
		Use:   "update-status <id>",
		Short: "Angebotsstatus aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/offers/{id}/update_status"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("status") {
				body["status"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "status", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
