// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newOfferCustomerApprovalCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "offer-customer-approval",
		Short: "Angebotsbestätigungen verwalten",
	}
	cmd.AddCommand(
		newOfferCustomerApprovalActivateCmd(app),
		newOfferCustomerApprovalDeactivateCmd(app),
		newOfferCustomerApprovalGetCmd(app),
	)
	return cmd
}

func newOfferCustomerApprovalActivateCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "activate <offer-id>",
		Short: "Kundenfreigabe aktivieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/offers/{offer_id}/customer_approval/activate"
			path = strings.Replace(path, "{offer_id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
			})
		},
	}
	return cmd
}

func newOfferCustomerApprovalDeactivateCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "deactivate <offer-id>",
		Short: "Kundenfreigabe deaktivieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/offers/{offer_id}/customer_approval/deactivate"
			path = strings.Replace(path, "{offer_id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
			})
		},
	}
	return cmd
}

func newOfferCustomerApprovalGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <offer-id>",
		Short: "Angebotsbestätigung abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/offers/{offer_id}/customer_approval"
			path = strings.Replace(path, "{offer_id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}
