// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newOfferAttachmentsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "offer-attachments",
		Short: "Angebotsanhänge verwalten",
	}
	cmd.AddCommand(
		newOfferAttachmentsCreateCmd(app),
		newOfferAttachmentsDeleteCmd(app),
		newOfferAttachmentsListCmd(app),
	)
	return cmd
}

func newOfferAttachmentsCreateCmd(app *cli.App) *cobra.Command {
	var data string
	cmd := &cobra.Command{
		Use:   "create <offer-id>",
		Short: "Angebotsanhang erstellen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/offers/{offer_id}/attachments"
			path = strings.Replace(path, "{offer_id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newOfferAttachmentsDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <offer-id> <id>",
		Short: "Angebotsanhang löschen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/offers/{offer_id}/attachments/{id}"
			path = strings.Replace(path, "{offer_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newOfferAttachmentsListCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list <offer-id>",
		Short: "Angebotsanhänge auflisten",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/offers/{offer_id}/attachments"
			path = strings.Replace(path, "{offer_id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}
