// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newPlanningEntriesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "planning-entries",
		Short: "Planungseinträge verwalten",
	}
	cmd.AddCommand(
		newPlanningEntriesCreateCmd(app),
		newPlanningEntriesDeleteCmd(app),
		newPlanningEntriesGetCmd(app),
		newPlanningEntriesListCmd(app),
		newPlanningEntriesPatchCmd(app),
		newPlanningEntriesUpdateCmd(app),
	)
	return cmd
}

func newPlanningEntriesCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 int
	var v3 string
	var v4 float64
	var v5 int
	var v6 string
	var v7 string
	var v8 int
	var v9 bool
	var v10 string
	var v11 int
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Planungseintrag erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/planning_entries"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("color") {
				body["color"] = v0
			}
			if cmd.Flags().Changed("comment") {
				body["comment"] = v1
			}
			if cmd.Flags().Changed("deal-id") {
				body["deal_id"] = v2
			}
			if cmd.Flags().Changed("ends-on") {
				body["ends_on"] = v3
			}
			if cmd.Flags().Changed("hours-per-day") {
				body["hours_per_day"] = v4
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v5
			}
			if cmd.Flags().Changed("starts-on") {
				body["starts_on"] = v6
			}
			if cmd.Flags().Changed("symbol") {
				body["symbol"] = v7
			}
			if cmd.Flags().Changed("task-id") {
				body["task_id"] = v8
			}
			if cmd.Flags().Changed("tentative") {
				body["tentative"] = v9
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v10
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v11
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "color", "", "")
	f.StringVar(&v1, "comment", "", "")
	f.IntVar(&v2, "deal-id", 0, "")
	f.StringVar(&v3, "ends-on", "", "")
	f.Float64Var(&v4, "hours-per-day", 0, "")
	f.IntVar(&v5, "project-id", 0, "")
	f.StringVar(&v6, "starts-on", "", "")
	f.StringVar(&v7, "symbol", "", "")
	f.IntVar(&v8, "task-id", 0, "")
	f.BoolVar(&v9, "tentative", false, "")
	f.StringVar(&v10, "title", "", "")
	f.IntVar(&v11, "user-id", 0, "Optional and only accepted when caller can modify user assignment.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newPlanningEntriesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Planungseintrag löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/planning_entries/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newPlanningEntriesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Planungseintrag abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/planning_entries/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newPlanningEntriesListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 int
	var q3 int
	var q4 string
	var q5 string
	var q6 string
	var q7 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Planungseinträge auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/planning_entries"
			q := url.Values{}
			if cmd.Flags().Changed("deal-id") {
				q.Set("deal_id", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("period") {
				q.Set("period", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("project-id") {
				q.Set("project_id", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("user-id") {
				q.Set("user_id", fmt.Sprint(q7))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "deal-id", "", "Single ID or comma-separated list.")
	f.StringVar(&q1, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q2, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q3, "per-page", 0, "Page size.")
	f.StringVar(&q4, "period", "", "Date range in `YYYY-MM-DD:YYYY-MM-DD` format (e.g. `2020-04-01:2020-07-31`).")
	f.StringVar(&q5, "project-id", "", "Single ID or comma-separated list.")
	f.StringVar(&q6, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	f.StringVar(&q7, "user-id", "", "Single ID or comma-separated list.")
	return cmd
}

func newPlanningEntriesPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 int
	var v3 string
	var v4 float64
	var v5 int
	var v6 string
	var v7 string
	var v8 int
	var v9 bool
	var v10 string
	var v11 int
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Planungseintrag teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/planning_entries/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("color") {
				body["color"] = v0
			}
			if cmd.Flags().Changed("comment") {
				body["comment"] = v1
			}
			if cmd.Flags().Changed("deal-id") {
				body["deal_id"] = v2
			}
			if cmd.Flags().Changed("ends-on") {
				body["ends_on"] = v3
			}
			if cmd.Flags().Changed("hours-per-day") {
				body["hours_per_day"] = v4
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v5
			}
			if cmd.Flags().Changed("starts-on") {
				body["starts_on"] = v6
			}
			if cmd.Flags().Changed("symbol") {
				body["symbol"] = v7
			}
			if cmd.Flags().Changed("task-id") {
				body["task_id"] = v8
			}
			if cmd.Flags().Changed("tentative") {
				body["tentative"] = v9
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v10
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v11
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "color", "", "")
	f.StringVar(&v1, "comment", "", "")
	f.IntVar(&v2, "deal-id", 0, "")
	f.StringVar(&v3, "ends-on", "", "")
	f.Float64Var(&v4, "hours-per-day", 0, "")
	f.IntVar(&v5, "project-id", 0, "")
	f.StringVar(&v6, "starts-on", "", "")
	f.StringVar(&v7, "symbol", "", "")
	f.IntVar(&v8, "task-id", 0, "")
	f.BoolVar(&v9, "tentative", false, "")
	f.StringVar(&v10, "title", "", "")
	f.IntVar(&v11, "user-id", 0, "Optional and only accepted when caller can modify user assignment.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newPlanningEntriesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 int
	var v3 string
	var v4 float64
	var v5 int
	var v6 string
	var v7 string
	var v8 int
	var v9 bool
	var v10 string
	var v11 int
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Planungseintrag aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/planning_entries/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("color") {
				body["color"] = v0
			}
			if cmd.Flags().Changed("comment") {
				body["comment"] = v1
			}
			if cmd.Flags().Changed("deal-id") {
				body["deal_id"] = v2
			}
			if cmd.Flags().Changed("ends-on") {
				body["ends_on"] = v3
			}
			if cmd.Flags().Changed("hours-per-day") {
				body["hours_per_day"] = v4
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v5
			}
			if cmd.Flags().Changed("starts-on") {
				body["starts_on"] = v6
			}
			if cmd.Flags().Changed("symbol") {
				body["symbol"] = v7
			}
			if cmd.Flags().Changed("task-id") {
				body["task_id"] = v8
			}
			if cmd.Flags().Changed("tentative") {
				body["tentative"] = v9
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v10
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v11
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "color", "", "")
	f.StringVar(&v1, "comment", "", "")
	f.IntVar(&v2, "deal-id", 0, "")
	f.StringVar(&v3, "ends-on", "", "")
	f.Float64Var(&v4, "hours-per-day", 0, "")
	f.IntVar(&v5, "project-id", 0, "")
	f.StringVar(&v6, "starts-on", "", "")
	f.StringVar(&v7, "symbol", "", "")
	f.IntVar(&v8, "task-id", 0, "")
	f.BoolVar(&v9, "tentative", false, "")
	f.StringVar(&v10, "title", "", "")
	f.IntVar(&v11, "user-id", 0, "Optional and only accepted when caller can modify user assignment.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
