// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newProfileCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "profile",
		Short: "Profile verwalten",
	}
	cmd.AddCommand(
		newProfileGetCmd(app),
	)
	return cmd
}

func newProfileGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Profil abrufen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/profile"
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}
