// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newProjectPaymentSchedulesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "project-payment-schedules",
		Short: "Abrechnungspläne verwalten",
	}
	cmd.AddCommand(
		newProjectPaymentSchedulesCreateCmd(app),
		newProjectPaymentSchedulesDeleteCmd(app),
		newProjectPaymentSchedulesGetCmd(app),
		newProjectPaymentSchedulesListCmd(app),
		newProjectPaymentSchedulesListAllCmd(app),
		newProjectPaymentSchedulesPatchCmd(app),
		newProjectPaymentSchedulesUpdateCmd(app),
	)
	return cmd
}

func newProjectPaymentSchedulesCreateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 string
	var v3 float64
	var v4 int
	var v5 string
	var data string
	cmd := &cobra.Command{
		Use:   "create <project-id>",
		Short: "Abrechnungsplan erstellen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/payment_schedules"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("checked") {
				body["checked"] = v0
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v1
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v2
			}
			if cmd.Flags().Changed("net-total") {
				body["net_total"] = v3
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v4
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "checked", false, "")
	f.StringVar(&v1, "date", "", "")
	f.StringVar(&v2, "description", "", "")
	f.Float64Var(&v3, "net-total", 0, "")
	f.IntVar(&v4, "project-id", 0, "")
	f.StringVar(&v5, "title", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newProjectPaymentSchedulesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <project-id> <id>",
		Short: "Abrechnungsplan löschen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/payment_schedules/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newProjectPaymentSchedulesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <project-id> <id>",
		Short: "Abrechnungsplan abrufen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/payment_schedules/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newProjectPaymentSchedulesListCmd(app *cli.App) *cobra.Command {
	var q0 bool
	var q1 int
	var q2 string
	var q3 string
	var q4 int
	var q5 int
	var q6 string
	var q7 string
	cmd := &cobra.Command{
		Use:   "list <project-id>",
		Short: "Abrechnungspläne auflisten",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/payment_schedules"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			q := url.Values{}
			if cmd.Flags().Changed("checked") {
				q.Set("checked", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("company-id") {
				q.Set("company_id", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("from") {
				q.Set("from", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("to") {
				q.Set("to", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q7))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&q0, "checked", false, "")
	f.IntVar(&q1, "company-id", 0, "")
	f.StringVar(&q2, "from", "", "Payment schedule date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q3, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q4, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q5, "per-page", 0, "Page size.")
	f.StringVar(&q6, "to", "", "Payment schedule date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q7, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newProjectPaymentSchedulesListAllCmd(app *cli.App) *cobra.Command {
	var q0 bool
	var q1 int
	var q2 string
	var q3 string
	var q4 int
	var q5 int
	var q6 int
	var q7 string
	var q8 string
	cmd := &cobra.Command{
		Use:   "list-all",
		Short: "Abrechnungspläne aller Projekte auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/payment_schedules"
			q := url.Values{}
			if cmd.Flags().Changed("checked") {
				q.Set("checked", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("company-id") {
				q.Set("company_id", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("from") {
				q.Set("from", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("project-id") {
				q.Set("project_id", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("to") {
				q.Set("to", fmt.Sprint(q7))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q8))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&q0, "checked", false, "")
	f.IntVar(&q1, "company-id", 0, "")
	f.StringVar(&q2, "from", "", "Payment schedule date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q3, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q4, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q5, "per-page", 0, "Page size.")
	f.IntVar(&q6, "project-id", 0, "")
	f.StringVar(&q7, "to", "", "Payment schedule date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q8, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newProjectPaymentSchedulesPatchCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 string
	var v3 float64
	var v4 int
	var v5 string
	var data string
	cmd := &cobra.Command{
		Use:   "patch <project-id> <id>",
		Short: "Abrechnungsplan teilweise aktualisieren",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/payment_schedules/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("checked") {
				body["checked"] = v0
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v1
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v2
			}
			if cmd.Flags().Changed("net-total") {
				body["net_total"] = v3
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v4
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "checked", false, "")
	f.StringVar(&v1, "date", "", "")
	f.StringVar(&v2, "description", "", "")
	f.Float64Var(&v3, "net-total", 0, "")
	f.IntVar(&v4, "project-id", 0, "")
	f.StringVar(&v5, "title", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newProjectPaymentSchedulesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 string
	var v3 float64
	var v4 int
	var v5 string
	var data string
	cmd := &cobra.Command{
		Use:   "update <project-id> <id>",
		Short: "Abrechnungsplan aktualisieren",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/payment_schedules/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("checked") {
				body["checked"] = v0
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v1
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v2
			}
			if cmd.Flags().Changed("net-total") {
				body["net_total"] = v3
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v4
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "checked", false, "")
	f.StringVar(&v1, "date", "", "")
	f.StringVar(&v2, "description", "", "")
	f.Float64Var(&v3, "net-total", 0, "")
	f.IntVar(&v4, "project-id", 0, "")
	f.StringVar(&v5, "title", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
