// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newProjectGroupsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "project-groups",
		Short: "Projektgruppen verwalten",
	}
	cmd.AddCommand(
		newProjectGroupsGetCmd(app),
		newProjectGroupsListCmd(app),
	)
	return cmd
}

func newProjectGroupsGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Projektgruppe abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/groups/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newProjectGroupsListCmd(app *cli.App) *cobra.Command {
	var q0 int
	var q1 string
	var q2 string
	var q3 int
	var q4 int
	var q5 string
	var q6 int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Projektgruppen auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/groups"
			q := url.Values{}
			if cmd.Flags().Changed("company-id") {
				q.Set("company_id", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("custom-properties") {
				q.Set("custom_properties", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("user-id") {
				q.Set("user_id", fmt.Sprint(q6))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "company-id", 0, "")
	f.StringVar(&q1, "custom-properties", "", "Filter by custom field values.")
	f.StringVar(&q2, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q3, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q4, "per-page", 0, "Page size.")
	f.StringVar(&q5, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	f.IntVar(&q6, "user-id", 0, "")
	return cmd
}
