// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newProjectsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "projects",
		Short: "Projekte verwalten",
	}
	cmd.AddCommand(
		newProjectsArchiveCmd(app),
		newProjectsAssignProjectGroupCmd(app),
		newProjectsAssignedListCmd(app),
		newProjectsCreateCmd(app),
		newProjectsDeleteCmd(app),
		newProjectsDisableShareCmd(app),
		newProjectsGetCmd(app),
		newProjectsListCmd(app),
		newProjectsPatchCmd(app),
		newProjectsReportGetCmd(app),
		newProjectsShareCmd(app),
		newProjectsUnarchiveCmd(app),
		newProjectsUnassignProjectGroupCmd(app),
		newProjectsUpdateCmd(app),
	)
	return cmd
}

func newProjectsArchiveCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "archive <id>",
		Short: "Projekt archivieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{id}/archive"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
			})
		},
	}
	return cmd
}

func newProjectsAssignProjectGroupCmd(app *cli.App) *cobra.Command {
	var v0 int
	var data string
	cmd := &cobra.Command{
		Use:   "assign-project-group <id>",
		Short: "Projekt einer Projektgruppe zuordnen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{id}/assign_project_group"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("project-group-id") {
				body["project_group_id"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&v0, "project-group-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newProjectsAssignedListCmd(app *cli.App) *cobra.Command {
	var q0 bool
	cmd := &cobra.Command{
		Use:   "assigned-list",
		Short: "Mir zugewiesene Projekte auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/assigned"
			q := url.Values{}
			if cmd.Flags().Changed("active") {
				q.Set("active", fmt.Sprint(q0))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&q0, "active", false, "")
	return cmd
}

func newProjectsCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 int
	var v2 string
	var v3 string
	var v4 string
	var v5 string
	var v6 float64
	var v7 float64
	var v8 float64
	var v9 int
	var v10 int
	var v11 int
	var v12 string
	var v13 int
	var v14 int
	var v15 string
	var v16 bool
	var v17 float64
	var v18 string
	var v19 string
	var v20 int
	var v21 string
	var v22 int
	var v23 bool
	var v24 int
	var v25 string
	var v26 string
	var v27 int
	var v28 bool
	var v29 bool
	var v30 string
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Projekt erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billing-address") {
				body["billing_address"] = v0
			}
			if cmd.Flags().Changed("billing-contact-id") {
				body["billing_contact_id"] = v1
			}
			if cmd.Flags().Changed("billing-email-cc") {
				body["billing_email_cc"] = v2
			}
			if cmd.Flags().Changed("billing-email-to") {
				body["billing_email_to"] = v3
			}
			if cmd.Flags().Changed("billing-notes") {
				body["billing_notes"] = v4
			}
			if cmd.Flags().Changed("billing-variant") {
				body["billing_variant"] = v5
			}
			if cmd.Flags().Changed("budget") {
				body["budget"] = v6
			}
			if cmd.Flags().Changed("budget-expenses") {
				body["budget_expenses"] = v7
			}
			if cmd.Flags().Changed("budget-monthly") {
				body["budget_monthly"] = v8
			}
			if cmd.Flags().Changed("co-leader-id") {
				body["co_leader_id"] = v9
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v10
			}
			if cmd.Flags().Changed("contact-id") {
				body["contact_id"] = v11
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v12
			}
			if cmd.Flags().Changed("customer-id") {
				body["customer_id"] = v13
			}
			if cmd.Flags().Changed("deal-id") {
				body["deal_id"] = v14
			}
			if cmd.Flags().Changed("finish-date") {
				body["finish_date"] = v15
			}
			if cmd.Flags().Changed("fixed-price") {
				body["fixed_price"] = v16
			}
			if cmd.Flags().Changed("hourly-rate") {
				body["hourly_rate"] = v17
			}
			if cmd.Flags().Changed("identifier") {
				body["identifier"] = v18
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v19
			}
			if cmd.Flags().Changed("leader-id") {
				body["leader_id"] = v20
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v21
			}
			if cmd.Flags().Changed("project-group-id") {
				body["project_group_id"] = v22
			}
			if cmd.Flags().Changed("retainer") {
				body["retainer"] = v23
			}
			if cmd.Flags().Changed("retainer-billing-date") {
				body["retainer_billing_date"] = v24
			}
			if cmd.Flags().Changed("retainer-billing-description") {
				body["retainer_billing_description"] = v25
			}
			if cmd.Flags().Changed("retainer-billing-title") {
				body["retainer_billing_title"] = v26
			}
			if cmd.Flags().Changed("secondary-contact-id") {
				body["secondary_contact_id"] = v27
			}
			if cmd.Flags().Changed("setting-include-time-report") {
				body["setting_include_time_report"] = v28
			}
			if cmd.Flags().Changed("skip-favorite") {
				body["skip_favorite"] = v29
			}
			if cmd.Flags().Changed("start-date") {
				body["start_date"] = v30
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "billing-address", "", "Billing address for generated documents.")
	f.IntVar(&v1, "billing-contact-id", 0, "Billing contact ID.")
	f.StringVar(&v2, "billing-email-cc", "", "Default CC email(s), semicolon-separated.")
	f.StringVar(&v3, "billing-email-to", "", "Default recipient email(s), semicolon-separated.")
	f.StringVar(&v4, "billing-notes", "", "Notes printed or used during billing.")
	f.StringVar(&v5, "billing-variant", "", "Pricing mode for hourly rates.")
	f.Float64Var(&v6, "budget", 0, "Project budget in project currency.")
	f.Float64Var(&v7, "budget-expenses", 0, "Expense budget in project currency.")
	f.Float64Var(&v8, "budget-monthly", 0, "Monthly budget for retainers.")
	f.IntVar(&v9, "co-leader-id", 0, "Secondary responsible user ID.")
	f.IntVar(&v10, "company-id", 0, "Customer company ID.")
	f.IntVar(&v11, "contact-id", 0, "Main external contact ID.")
	f.StringVar(&v12, "currency", "", "Project currency. Mandatory on create and immutable afterwards.")
	f.IntVar(&v13, "customer-id", 0, "Deprecated alias of `company_id`.")
	f.IntVar(&v14, "deal-id", 0, "Linked deal ID.")
	f.StringVar(&v15, "finish-date", "", "Project finish date.")
	f.BoolVar(&v16, "fixed-price", false, "Whether the project is fixed price.")
	f.Float64Var(&v17, "hourly-rate", 0, "Effective hourly rate for project pricing.")
	f.StringVar(&v18, "identifier", "", "Project number/identifier. Required when number ranges are manual.")
	f.StringVar(&v19, "info", "", "Internal project notes.")
	f.IntVar(&v20, "leader-id", 0, "Main responsible user ID.")
	f.StringVar(&v21, "name", "", "Project name.")
	f.IntVar(&v22, "project-group-id", 0, "Linked project group ID.")
	f.BoolVar(&v23, "retainer", false, "Whether project is billed as retainer.")
	f.IntVar(&v24, "retainer-billing-date", 0, "Retainer billing day in month (1-31).")
	f.StringVar(&v25, "retainer-billing-description", "", "Default description for generated retainer items.")
	f.StringVar(&v26, "retainer-billing-title", "", "Default title for generated retainer items.")
	f.IntVar(&v27, "secondary-contact-id", 0, "Secondary external contact ID.")
	f.BoolVar(&v28, "setting-include-time-report", false, "Include time report in billing output.")
	f.BoolVar(&v29, "skip-favorite", false, "Do not add this project to favorites for the creator.")
	f.StringVar(&v30, "start-date", "", "Project start date.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newProjectsDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Projekt löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newProjectsDisableShareCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "disable-share <id>",
		Short: "Projektbericht-Freigabe deaktivieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{id}/disable_share"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
			})
		},
	}
	return cmd
}

func newProjectsGetCmd(app *cli.App) *cobra.Command {
	var q0 bool
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Projekt abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			q := url.Values{}
			if cmd.Flags().Changed("include-company") {
				q.Set("include_company", fmt.Sprint(q0))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&q0, "include-company", false, "")
	return cmd
}

func newProjectsListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 string
	var q3 string
	var q4 string
	var q5 string
	var q6 string
	var q7 bool
	var q8 bool
	var q9 string
	var q10 int
	var q11 int
	var q12 string
	var q13 bool
	var q14 string
	var q15 string
	var q16 string
	var q17 string
	var q18 string
	var q19 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Projekte auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects"
			q := url.Values{}
			if cmd.Flags().Changed("company-id") {
				q.Set("company_id", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("created-from") {
				q.Set("created_from", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("created-to") {
				q.Set("created_to", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("custom-properties") {
				q.Set("custom_properties", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("deal-id") {
				q.Set("deal_id", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("identifier") {
				q.Set("identifier", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("include-archived") {
				q.Set("include_archived", fmt.Sprint(q7))
			}
			if cmd.Flags().Changed("include-company") {
				q.Set("include_company", fmt.Sprint(q8))
			}
			if cmd.Flags().Changed("leader-id") {
				q.Set("leader_id", fmt.Sprint(q9))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q10))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q11))
			}
			if cmd.Flags().Changed("project-group-id") {
				q.Set("project_group_id", fmt.Sprint(q12))
			}
			if cmd.Flags().Changed("retainer") {
				q.Set("retainer", fmt.Sprint(q13))
			}
			if cmd.Flags().Changed("sort-by") {
				q.Set("sort_by", fmt.Sprint(q14))
			}
			if cmd.Flags().Changed("tags") {
				q.Set("tags", fmt.Sprint(q15))
			}
			if cmd.Flags().Changed("term") {
				q.Set("term", fmt.Sprint(q16))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q17))
			}
			if cmd.Flags().Changed("updated-from") {
				q.Set("updated_from", fmt.Sprint(q18))
			}
			if cmd.Flags().Changed("updated-to") {
				q.Set("updated_to", fmt.Sprint(q19))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "company-id", "", "Single ID or comma-separated list.")
	f.StringVar(&q1, "created-from", "", "Creation date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q2, "created-to", "", "Creation date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q3, "custom-properties", "", "Filter by custom field values.")
	f.StringVar(&q4, "deal-id", "", "Single ID or comma-separated list.")
	f.StringVar(&q5, "identifier", "", "Single identifier or comma-separated list.")
	f.StringVar(&q6, "ids", "", "Comma-separated IDs.")
	f.BoolVar(&q7, "include-archived", false, "")
	f.BoolVar(&q8, "include-company", false, "Return full customer company payload instead of `{id,name}`.")
	f.StringVar(&q9, "leader-id", "", "Single ID or comma-separated list.")
	f.IntVar(&q10, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q11, "per-page", 0, "Page size.")
	f.StringVar(&q12, "project-group-id", "", "Single ID or comma-separated list.")
	f.BoolVar(&q13, "retainer", false, "")
	f.StringVar(&q14, "sort-by", "", "Field and optional direction, e.g. `title desc`.")
	f.StringVar(&q15, "tags", "", "Comma-separated list of tag names.")
	f.StringVar(&q16, "term", "", "Searches project name, project identifier and customer company name.")
	f.StringVar(&q17, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	f.StringVar(&q18, "updated-from", "", "Update date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q19, "updated-to", "", "Update date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	return cmd
}

func newProjectsPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 int
	var v2 string
	var v3 string
	var v4 string
	var v5 string
	var v6 float64
	var v7 float64
	var v8 float64
	var v9 int
	var v10 int
	var v11 int
	var v12 string
	var v13 int
	var v14 int
	var v15 string
	var v16 bool
	var v17 float64
	var v18 string
	var v19 string
	var v20 int
	var v21 string
	var v22 int
	var v23 bool
	var v24 int
	var v25 string
	var v26 string
	var v27 int
	var v28 bool
	var v29 bool
	var v30 string
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Projekt teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billing-address") {
				body["billing_address"] = v0
			}
			if cmd.Flags().Changed("billing-contact-id") {
				body["billing_contact_id"] = v1
			}
			if cmd.Flags().Changed("billing-email-cc") {
				body["billing_email_cc"] = v2
			}
			if cmd.Flags().Changed("billing-email-to") {
				body["billing_email_to"] = v3
			}
			if cmd.Flags().Changed("billing-notes") {
				body["billing_notes"] = v4
			}
			if cmd.Flags().Changed("billing-variant") {
				body["billing_variant"] = v5
			}
			if cmd.Flags().Changed("budget") {
				body["budget"] = v6
			}
			if cmd.Flags().Changed("budget-expenses") {
				body["budget_expenses"] = v7
			}
			if cmd.Flags().Changed("budget-monthly") {
				body["budget_monthly"] = v8
			}
			if cmd.Flags().Changed("co-leader-id") {
				body["co_leader_id"] = v9
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v10
			}
			if cmd.Flags().Changed("contact-id") {
				body["contact_id"] = v11
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v12
			}
			if cmd.Flags().Changed("customer-id") {
				body["customer_id"] = v13
			}
			if cmd.Flags().Changed("deal-id") {
				body["deal_id"] = v14
			}
			if cmd.Flags().Changed("finish-date") {
				body["finish_date"] = v15
			}
			if cmd.Flags().Changed("fixed-price") {
				body["fixed_price"] = v16
			}
			if cmd.Flags().Changed("hourly-rate") {
				body["hourly_rate"] = v17
			}
			if cmd.Flags().Changed("identifier") {
				body["identifier"] = v18
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v19
			}
			if cmd.Flags().Changed("leader-id") {
				body["leader_id"] = v20
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v21
			}
			if cmd.Flags().Changed("project-group-id") {
				body["project_group_id"] = v22
			}
			if cmd.Flags().Changed("retainer") {
				body["retainer"] = v23
			}
			if cmd.Flags().Changed("retainer-billing-date") {
				body["retainer_billing_date"] = v24
			}
			if cmd.Flags().Changed("retainer-billing-description") {
				body["retainer_billing_description"] = v25
			}
			if cmd.Flags().Changed("retainer-billing-title") {
				body["retainer_billing_title"] = v26
			}
			if cmd.Flags().Changed("secondary-contact-id") {
				body["secondary_contact_id"] = v27
			}
			if cmd.Flags().Changed("setting-include-time-report") {
				body["setting_include_time_report"] = v28
			}
			if cmd.Flags().Changed("skip-favorite") {
				body["skip_favorite"] = v29
			}
			if cmd.Flags().Changed("start-date") {
				body["start_date"] = v30
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "billing-address", "", "Billing address for generated documents.")
	f.IntVar(&v1, "billing-contact-id", 0, "Billing contact ID.")
	f.StringVar(&v2, "billing-email-cc", "", "Default CC email(s), semicolon-separated.")
	f.StringVar(&v3, "billing-email-to", "", "Default recipient email(s), semicolon-separated.")
	f.StringVar(&v4, "billing-notes", "", "Notes printed or used during billing.")
	f.StringVar(&v5, "billing-variant", "", "Pricing mode for hourly rates.")
	f.Float64Var(&v6, "budget", 0, "Project budget in project currency.")
	f.Float64Var(&v7, "budget-expenses", 0, "Expense budget in project currency.")
	f.Float64Var(&v8, "budget-monthly", 0, "Monthly budget for retainers.")
	f.IntVar(&v9, "co-leader-id", 0, "Secondary responsible user ID.")
	f.IntVar(&v10, "company-id", 0, "Customer company ID.")
	f.IntVar(&v11, "contact-id", 0, "Main external contact ID.")
	f.StringVar(&v12, "currency", "", "Project currency. Mandatory on create and immutable afterwards.")
	f.IntVar(&v13, "customer-id", 0, "Deprecated alias of `company_id`.")
	f.IntVar(&v14, "deal-id", 0, "Linked deal ID.")
	f.StringVar(&v15, "finish-date", "", "Project finish date.")
	f.BoolVar(&v16, "fixed-price", false, "Whether the project is fixed price.")
	f.Float64Var(&v17, "hourly-rate", 0, "Effective hourly rate for project pricing.")
	f.StringVar(&v18, "identifier", "", "Project number/identifier. Required when number ranges are manual.")
	f.StringVar(&v19, "info", "", "Internal project notes.")
	f.IntVar(&v20, "leader-id", 0, "Main responsible user ID.")
	f.StringVar(&v21, "name", "", "Project name.")
	f.IntVar(&v22, "project-group-id", 0, "Linked project group ID.")
	f.BoolVar(&v23, "retainer", false, "Whether project is billed as retainer.")
	f.IntVar(&v24, "retainer-billing-date", 0, "Retainer billing day in month (1-31).")
	f.StringVar(&v25, "retainer-billing-description", "", "Default description for generated retainer items.")
	f.StringVar(&v26, "retainer-billing-title", "", "Default title for generated retainer items.")
	f.IntVar(&v27, "secondary-contact-id", 0, "Secondary external contact ID.")
	f.BoolVar(&v28, "setting-include-time-report", false, "Include time report in billing output.")
	f.BoolVar(&v29, "skip-favorite", false, "Do not add this project to favorites for the creator.")
	f.StringVar(&v30, "start-date", "", "Project start date.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newProjectsReportGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "report-get <id>",
		Short: "Projektbericht abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{id}/report"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newProjectsShareCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "share <id>",
		Short: "Projektbericht-Freigabe aktivieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{id}/share"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
			})
		},
	}
	return cmd
}

func newProjectsUnarchiveCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "unarchive <id>",
		Short: "Projekt aus dem Archiv holen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{id}/unarchive"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
			})
		},
	}
	return cmd
}

func newProjectsUnassignProjectGroupCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "unassign-project-group <id>",
		Short: "Projekt aus Projektgruppe entfernen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{id}/unassign_project_group"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
			})
		},
	}
	return cmd
}

func newProjectsUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 int
	var v2 string
	var v3 string
	var v4 string
	var v5 string
	var v6 float64
	var v7 float64
	var v8 float64
	var v9 int
	var v10 int
	var v11 int
	var v12 string
	var v13 int
	var v14 int
	var v15 string
	var v16 bool
	var v17 float64
	var v18 string
	var v19 string
	var v20 int
	var v21 string
	var v22 int
	var v23 bool
	var v24 int
	var v25 string
	var v26 string
	var v27 int
	var v28 bool
	var v29 bool
	var v30 string
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Projekt aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billing-address") {
				body["billing_address"] = v0
			}
			if cmd.Flags().Changed("billing-contact-id") {
				body["billing_contact_id"] = v1
			}
			if cmd.Flags().Changed("billing-email-cc") {
				body["billing_email_cc"] = v2
			}
			if cmd.Flags().Changed("billing-email-to") {
				body["billing_email_to"] = v3
			}
			if cmd.Flags().Changed("billing-notes") {
				body["billing_notes"] = v4
			}
			if cmd.Flags().Changed("billing-variant") {
				body["billing_variant"] = v5
			}
			if cmd.Flags().Changed("budget") {
				body["budget"] = v6
			}
			if cmd.Flags().Changed("budget-expenses") {
				body["budget_expenses"] = v7
			}
			if cmd.Flags().Changed("budget-monthly") {
				body["budget_monthly"] = v8
			}
			if cmd.Flags().Changed("co-leader-id") {
				body["co_leader_id"] = v9
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v10
			}
			if cmd.Flags().Changed("contact-id") {
				body["contact_id"] = v11
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v12
			}
			if cmd.Flags().Changed("customer-id") {
				body["customer_id"] = v13
			}
			if cmd.Flags().Changed("deal-id") {
				body["deal_id"] = v14
			}
			if cmd.Flags().Changed("finish-date") {
				body["finish_date"] = v15
			}
			if cmd.Flags().Changed("fixed-price") {
				body["fixed_price"] = v16
			}
			if cmd.Flags().Changed("hourly-rate") {
				body["hourly_rate"] = v17
			}
			if cmd.Flags().Changed("identifier") {
				body["identifier"] = v18
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v19
			}
			if cmd.Flags().Changed("leader-id") {
				body["leader_id"] = v20
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v21
			}
			if cmd.Flags().Changed("project-group-id") {
				body["project_group_id"] = v22
			}
			if cmd.Flags().Changed("retainer") {
				body["retainer"] = v23
			}
			if cmd.Flags().Changed("retainer-billing-date") {
				body["retainer_billing_date"] = v24
			}
			if cmd.Flags().Changed("retainer-billing-description") {
				body["retainer_billing_description"] = v25
			}
			if cmd.Flags().Changed("retainer-billing-title") {
				body["retainer_billing_title"] = v26
			}
			if cmd.Flags().Changed("secondary-contact-id") {
				body["secondary_contact_id"] = v27
			}
			if cmd.Flags().Changed("setting-include-time-report") {
				body["setting_include_time_report"] = v28
			}
			if cmd.Flags().Changed("skip-favorite") {
				body["skip_favorite"] = v29
			}
			if cmd.Flags().Changed("start-date") {
				body["start_date"] = v30
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "billing-address", "", "Billing address for generated documents.")
	f.IntVar(&v1, "billing-contact-id", 0, "Billing contact ID.")
	f.StringVar(&v2, "billing-email-cc", "", "Default CC email(s), semicolon-separated.")
	f.StringVar(&v3, "billing-email-to", "", "Default recipient email(s), semicolon-separated.")
	f.StringVar(&v4, "billing-notes", "", "Notes printed or used during billing.")
	f.StringVar(&v5, "billing-variant", "", "Pricing mode for hourly rates.")
	f.Float64Var(&v6, "budget", 0, "Project budget in project currency.")
	f.Float64Var(&v7, "budget-expenses", 0, "Expense budget in project currency.")
	f.Float64Var(&v8, "budget-monthly", 0, "Monthly budget for retainers.")
	f.IntVar(&v9, "co-leader-id", 0, "Secondary responsible user ID.")
	f.IntVar(&v10, "company-id", 0, "Customer company ID.")
	f.IntVar(&v11, "contact-id", 0, "Main external contact ID.")
	f.StringVar(&v12, "currency", "", "Project currency. Mandatory on create and immutable afterwards.")
	f.IntVar(&v13, "customer-id", 0, "Deprecated alias of `company_id`.")
	f.IntVar(&v14, "deal-id", 0, "Linked deal ID.")
	f.StringVar(&v15, "finish-date", "", "Project finish date.")
	f.BoolVar(&v16, "fixed-price", false, "Whether the project is fixed price.")
	f.Float64Var(&v17, "hourly-rate", 0, "Effective hourly rate for project pricing.")
	f.StringVar(&v18, "identifier", "", "Project number/identifier. Required when number ranges are manual.")
	f.StringVar(&v19, "info", "", "Internal project notes.")
	f.IntVar(&v20, "leader-id", 0, "Main responsible user ID.")
	f.StringVar(&v21, "name", "", "Project name.")
	f.IntVar(&v22, "project-group-id", 0, "Linked project group ID.")
	f.BoolVar(&v23, "retainer", false, "Whether project is billed as retainer.")
	f.IntVar(&v24, "retainer-billing-date", 0, "Retainer billing day in month (1-31).")
	f.StringVar(&v25, "retainer-billing-description", "", "Default description for generated retainer items.")
	f.StringVar(&v26, "retainer-billing-title", "", "Default title for generated retainer items.")
	f.IntVar(&v27, "secondary-contact-id", 0, "Secondary external contact ID.")
	f.BoolVar(&v28, "setting-include-time-report", false, "Include time report in billing output.")
	f.BoolVar(&v29, "skip-favorite", false, "Do not add this project to favorites for the creator.")
	f.StringVar(&v30, "start-date", "", "Project start date.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
