// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newPurchaseBookkeepingExportsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "purchase-bookkeeping-exports",
		Short: "Buchhaltungsexporte verwalten",
	}
	cmd.AddCommand(
		newPurchaseBookkeepingExportsCreateCmd(app),
		newPurchaseBookkeepingExportsGetCmd(app),
		newPurchaseBookkeepingExportsListCmd(app),
	)
	return cmd
}

func newPurchaseBookkeepingExportsCreateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 bool
	var v3 bool
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Buchhaltungsexport erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/bookkeeping_exports"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("archive-after-export") {
				body["archive_after_export"] = v0
			}
			if cmd.Flags().Changed("comment") {
				body["comment"] = v1
			}
			if cmd.Flags().Changed("trigger-submission") {
				body["trigger_submission"] = v2
			}
			if cmd.Flags().Changed("with-direct-online-submission") {
				body["with_direct_online_submission"] = v3
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "archive-after-export", false, "")
	f.StringVar(&v1, "comment", "", "")
	f.BoolVar(&v2, "trigger-submission", false, "")
	f.BoolVar(&v3, "with-direct-online-submission", false, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newPurchaseBookkeepingExportsGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Buchhaltungsexport abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/bookkeeping_exports/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newPurchaseBookkeepingExportsListCmd(app *cli.App) *cobra.Command {
	var q0 int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Buchhaltungsexporte auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/bookkeeping_exports"
			q := url.Values{}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q0))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "page", 0, "Page number, starting at 1.")
	return cmd
}
