// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newPurchasesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "purchases",
		Short: "Ausgaben verwalten",
	}
	cmd.AddCommand(
		newPurchasesAssignToProjectCmd(app),
		newPurchasesCreateCmd(app),
		newPurchasesDeleteCmd(app),
		newPurchasesGetCmd(app),
		newPurchasesListCmd(app),
		newPurchasesPatchCmd(app),
		newPurchasesStoreDocumentCmd(app),
		newPurchasesUpdateCmd(app),
		newPurchasesUpdateStatusCmd(app),
	)
	return cmd
}

func newPurchasesAssignToProjectCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 bool
	var v2 int
	var v3 int
	var v4 bool
	var v5 int
	var v6 float64
	var data string
	cmd := &cobra.Command{
		Use:   "assign-to-project <id>",
		Short: "Ausgabenposition einem Projekt zuordnen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/{id}/assign_to_project"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("budget-relevant") {
				body["budget_relevant"] = v1
			}
			if cmd.Flags().Changed("expense-id") {
				body["expense_id"] = v2
			}
			if cmd.Flags().Changed("item-id") {
				body["item_id"] = v3
			}
			if cmd.Flags().Changed("notify-project-leader") {
				body["notify_project_leader"] = v4
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v5
			}
			if cmd.Flags().Changed("surcharge") {
				body["surcharge"] = v6
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "")
	f.BoolVar(&v1, "budget-relevant", false, "")
	f.IntVar(&v2, "expense-id", 0, "Existing expense ID to attach to.")
	f.IntVar(&v3, "item-id", 0, "Single purchase item ID.")
	f.BoolVar(&v4, "notify-project-leader", false, "")
	f.IntVar(&v5, "project-id", 0, "")
	f.Float64Var(&v6, "surcharge", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newPurchasesCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 float64
	var v2 string
	var v3 int
	var v4 int
	var v5 string
	var v6 string
	var v7 string
	var v8 string
	var v9 int
	var v10 string
	var v11 string
	var v12 int
	var v13 string
	var v14 string
	var v15 string
	var v16 string
	var v17 string
	var v18 int
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Ausgabe erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("bank-account-number") {
				body["bank_account_number"] = v0
			}
			if cmd.Flags().Changed("cash-discount-rate") {
				body["cash_discount_rate"] = v1
			}
			if cmd.Flags().Changed("cash-discount-until") {
				body["cash_discount_until"] = v2
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v3
			}
			if cmd.Flags().Changed("cost-center-id") {
				body["cost_center_id"] = v4
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v5
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v6
			}
			if cmd.Flags().Changed("due-date") {
				body["due_date"] = v7
			}
			if cmd.Flags().Changed("iban") {
				body["iban"] = v8
			}
			if cmd.Flags().Changed("inbound-email-id") {
				body["inbound_email_id"] = v9
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v10
			}
			if cmd.Flags().Changed("payment-method") {
				body["payment_method"] = v11
			}
			if cmd.Flags().Changed("purchase-draft-id") {
				body["purchase_draft_id"] = v12
			}
			if cmd.Flags().Changed("receipt-identifier") {
				body["receipt_identifier"] = v13
			}
			if cmd.Flags().Changed("reference") {
				body["reference"] = v14
			}
			if cmd.Flags().Changed("service-period-from") {
				body["service_period_from"] = v15
			}
			if cmd.Flags().Changed("service-period-to") {
				body["service_period_to"] = v16
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v17
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v18
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "bank-account-number", "", "")
	f.Float64Var(&v1, "cash-discount-rate", 0, "")
	f.StringVar(&v2, "cash-discount-until", "", "")
	f.IntVar(&v3, "company-id", 0, "")
	f.IntVar(&v4, "cost-center-id", 0, "")
	f.StringVar(&v5, "currency", "", "")
	f.StringVar(&v6, "date", "", "")
	f.StringVar(&v7, "due-date", "", "")
	f.StringVar(&v8, "iban", "", "")
	f.IntVar(&v9, "inbound-email-id", 0, "")
	f.StringVar(&v10, "info", "", "")
	f.StringVar(&v11, "payment-method", "", "")
	f.IntVar(&v12, "purchase-draft-id", 0, "")
	f.StringVar(&v13, "receipt-identifier", "", "")
	f.StringVar(&v14, "reference", "", "")
	f.StringVar(&v15, "service-period-from", "", "")
	f.StringVar(&v16, "service-period-to", "", "")
	f.StringVar(&v17, "title", "", "")
	f.IntVar(&v18, "user-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newPurchasesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Ausgabe löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newPurchasesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Ausgabe abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newPurchasesListCmd(app *cli.App) *cobra.Command {
	var q0 int
	var q1 int
	var q2 string
	var q3 string
	var q4 string
	var q5 string
	var q6 string
	var q7 bool
	var q8 int
	var q9 bool
	var q10 string
	var q11 int
	var q12 string
	var q13 string
	var q14 string
	var q15 string
	var q16 string
	var q17 bool
	var q18 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Ausgaben auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases"
			q := url.Values{}
			if cmd.Flags().Changed("category-id") {
				q.Set("category_id", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("company-id") {
				q.Set("company_id", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("custom-properties") {
				q.Set("custom_properties", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("date") {
				q.Set("date", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("id") {
				q.Set("id", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("identifier") {
				q.Set("identifier", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("not-booked") {
				q.Set("not_booked", fmt.Sprint(q7))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q8))
			}
			if cmd.Flags().Changed("partially-paid") {
				q.Set("partially_paid", fmt.Sprint(q9))
			}
			if cmd.Flags().Changed("payment-method") {
				q.Set("payment_method", fmt.Sprint(q10))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q11))
			}
			if cmd.Flags().Changed("receipt-identifier") {
				q.Set("receipt_identifier", fmt.Sprint(q12))
			}
			if cmd.Flags().Changed("status") {
				q.Set("status", fmt.Sprint(q13))
			}
			if cmd.Flags().Changed("tag-ids") {
				q.Set("tag_ids", fmt.Sprint(q14))
			}
			if cmd.Flags().Changed("tags") {
				q.Set("tags", fmt.Sprint(q15))
			}
			if cmd.Flags().Changed("term") {
				q.Set("term", fmt.Sprint(q16))
			}
			if cmd.Flags().Changed("unpaid") {
				q.Set("unpaid", fmt.Sprint(q17))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q18))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "category-id", 0, "")
	f.IntVar(&q1, "company-id", 0, "Supplier company ID. Use `0` for purchases without supplier.")
	f.StringVar(&q2, "custom-properties", "", "Filter by custom field values.")
	f.StringVar(&q3, "date", "", "Date range, e.g. `2020-02-01:2020-02-22`.")
	f.StringVar(&q4, "id", "", "Legacy alias for filtering by purchase ID (single ID or comma-separated list).")
	f.StringVar(&q5, "identifier", "", "")
	f.StringVar(&q6, "ids", "", "Comma-separated IDs.")
	f.BoolVar(&q7, "not-booked", false, "")
	f.IntVar(&q8, "page", 0, "Page number, starting at 1.")
	f.BoolVar(&q9, "partially-paid", false, "")
	f.StringVar(&q10, "payment-method", "", "")
	f.IntVar(&q11, "per-page", 0, "Page size.")
	f.StringVar(&q12, "receipt-identifier", "", "")
	f.StringVar(&q13, "status", "", "")
	f.StringVar(&q14, "tag-ids", "", "Comma-separated list of tag IDs.")
	f.StringVar(&q15, "tags", "", "Comma-separated list of tag names.")
	f.StringVar(&q16, "term", "", "")
	f.BoolVar(&q17, "unpaid", false, "")
	f.StringVar(&q18, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newPurchasesPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 float64
	var v2 string
	var v3 int
	var v4 int
	var v5 string
	var v6 string
	var v7 string
	var v8 string
	var v9 int
	var v10 string
	var v11 string
	var v12 int
	var v13 string
	var v14 string
	var v15 string
	var v16 string
	var v17 string
	var v18 int
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Ausgabe teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("bank-account-number") {
				body["bank_account_number"] = v0
			}
			if cmd.Flags().Changed("cash-discount-rate") {
				body["cash_discount_rate"] = v1
			}
			if cmd.Flags().Changed("cash-discount-until") {
				body["cash_discount_until"] = v2
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v3
			}
			if cmd.Flags().Changed("cost-center-id") {
				body["cost_center_id"] = v4
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v5
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v6
			}
			if cmd.Flags().Changed("due-date") {
				body["due_date"] = v7
			}
			if cmd.Flags().Changed("iban") {
				body["iban"] = v8
			}
			if cmd.Flags().Changed("inbound-email-id") {
				body["inbound_email_id"] = v9
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v10
			}
			if cmd.Flags().Changed("payment-method") {
				body["payment_method"] = v11
			}
			if cmd.Flags().Changed("purchase-draft-id") {
				body["purchase_draft_id"] = v12
			}
			if cmd.Flags().Changed("receipt-identifier") {
				body["receipt_identifier"] = v13
			}
			if cmd.Flags().Changed("reference") {
				body["reference"] = v14
			}
			if cmd.Flags().Changed("service-period-from") {
				body["service_period_from"] = v15
			}
			if cmd.Flags().Changed("service-period-to") {
				body["service_period_to"] = v16
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v17
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v18
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "bank-account-number", "", "")
	f.Float64Var(&v1, "cash-discount-rate", 0, "")
	f.StringVar(&v2, "cash-discount-until", "", "")
	f.IntVar(&v3, "company-id", 0, "")
	f.IntVar(&v4, "cost-center-id", 0, "")
	f.StringVar(&v5, "currency", "", "")
	f.StringVar(&v6, "date", "", "")
	f.StringVar(&v7, "due-date", "", "")
	f.StringVar(&v8, "iban", "", "")
	f.IntVar(&v9, "inbound-email-id", 0, "")
	f.StringVar(&v10, "info", "", "")
	f.StringVar(&v11, "payment-method", "", "")
	f.IntVar(&v12, "purchase-draft-id", 0, "")
	f.StringVar(&v13, "receipt-identifier", "", "")
	f.StringVar(&v14, "reference", "", "")
	f.StringVar(&v15, "service-period-from", "", "")
	f.StringVar(&v16, "service-period-to", "", "")
	f.StringVar(&v17, "title", "", "")
	f.IntVar(&v18, "user-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newPurchasesStoreDocumentCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "store-document <id>",
		Short: "Ausgabenbeleg ablegen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/{id}/store_document"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
			})
		},
	}
	return cmd
}

func newPurchasesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 float64
	var v2 string
	var v3 int
	var v4 int
	var v5 string
	var v6 string
	var v7 string
	var v8 string
	var v9 int
	var v10 string
	var v11 string
	var v12 int
	var v13 string
	var v14 string
	var v15 string
	var v16 string
	var v17 string
	var v18 int
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Ausgabe aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("bank-account-number") {
				body["bank_account_number"] = v0
			}
			if cmd.Flags().Changed("cash-discount-rate") {
				body["cash_discount_rate"] = v1
			}
			if cmd.Flags().Changed("cash-discount-until") {
				body["cash_discount_until"] = v2
			}
			if cmd.Flags().Changed("company-id") {
				body["company_id"] = v3
			}
			if cmd.Flags().Changed("cost-center-id") {
				body["cost_center_id"] = v4
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v5
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v6
			}
			if cmd.Flags().Changed("due-date") {
				body["due_date"] = v7
			}
			if cmd.Flags().Changed("iban") {
				body["iban"] = v8
			}
			if cmd.Flags().Changed("inbound-email-id") {
				body["inbound_email_id"] = v9
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v10
			}
			if cmd.Flags().Changed("payment-method") {
				body["payment_method"] = v11
			}
			if cmd.Flags().Changed("purchase-draft-id") {
				body["purchase_draft_id"] = v12
			}
			if cmd.Flags().Changed("receipt-identifier") {
				body["receipt_identifier"] = v13
			}
			if cmd.Flags().Changed("reference") {
				body["reference"] = v14
			}
			if cmd.Flags().Changed("service-period-from") {
				body["service_period_from"] = v15
			}
			if cmd.Flags().Changed("service-period-to") {
				body["service_period_to"] = v16
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v17
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v18
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "bank-account-number", "", "")
	f.Float64Var(&v1, "cash-discount-rate", 0, "")
	f.StringVar(&v2, "cash-discount-until", "", "")
	f.IntVar(&v3, "company-id", 0, "")
	f.IntVar(&v4, "cost-center-id", 0, "")
	f.StringVar(&v5, "currency", "", "")
	f.StringVar(&v6, "date", "", "")
	f.StringVar(&v7, "due-date", "", "")
	f.StringVar(&v8, "iban", "", "")
	f.IntVar(&v9, "inbound-email-id", 0, "")
	f.StringVar(&v10, "info", "", "")
	f.StringVar(&v11, "payment-method", "", "")
	f.IntVar(&v12, "purchase-draft-id", 0, "")
	f.StringVar(&v13, "receipt-identifier", "", "")
	f.StringVar(&v14, "reference", "", "")
	f.StringVar(&v15, "service-period-from", "", "")
	f.StringVar(&v16, "service-period-to", "", "")
	f.StringVar(&v17, "title", "", "")
	f.IntVar(&v18, "user-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newPurchasesUpdateStatusCmd(app *cli.App) *cobra.Command {
	var v0 string
	var data string
	cmd := &cobra.Command{
		Use:   "update-status <id>",
		Short: "Ausgabenstatus aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/{id}/update_status"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("status") {
				body["status"] = v0
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "status", "", "Supports legacy `approved` (mapped to internal `archived`) and direct `archived`.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
