// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newPurchaseBudgetsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "purchase-budgets",
		Short: "Ausgabenbudgets verwalten",
	}
	cmd.AddCommand(
		newPurchaseBudgetsListCmd(app),
	)
	return cmd
}

func newPurchaseBudgetsListCmd(app *cli.App) *cobra.Command {
	var q0 int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Ausgabenbudgets auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/budgets"
			q := url.Values{}
			if cmd.Flags().Changed("year") {
				q.Set("year", fmt.Sprint(q0))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "year", 0, "")
	return cmd
}
