// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newPurchasePaymentsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "purchase-payments",
		Short: "Zahlungen verwalten",
	}
	cmd.AddCommand(
		newPurchasePaymentsBulkCreateCmd(app),
		newPurchasePaymentsCreateCmd(app),
		newPurchasePaymentsDeleteCmd(app),
		newPurchasePaymentsGetCmd(app),
		newPurchasePaymentsListCmd(app),
		newPurchasePaymentsPatchCmd(app),
		newPurchasePaymentsUpdateCmd(app),
	)
	return cmd
}

func newPurchasePaymentsBulkCreateCmd(app *cli.App) *cobra.Command {
	var data string
	cmd := &cobra.Command{
		Use:   "bulk-create",
		Short: "Zahlungen als Stapel erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/payments/bulk"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newPurchasePaymentsCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var v3 bool
	var v4 int
	var v5 int
	var v6 float64
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Zahlung erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/payments"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v0
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v1
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v2
			}
			if cmd.Flags().Changed("partially-paid") {
				body["partially_paid"] = v3
			}
			if cmd.Flags().Changed("payment-account-id") {
				body["payment_account_id"] = v4
			}
			if cmd.Flags().Changed("purchase-id") {
				body["purchase_id"] = v5
			}
			if cmd.Flags().Changed("total") {
				body["total"] = v6
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "currency", "", "")
	f.StringVar(&v1, "date", "", "")
	f.StringVar(&v2, "description", "", "")
	f.BoolVar(&v3, "partially-paid", false, "Indicates whether the purchase is partially paid.")
	f.IntVar(&v4, "payment-account-id", 0, "")
	f.IntVar(&v5, "purchase-id", 0, "")
	f.Float64Var(&v6, "total", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newPurchasePaymentsDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Zahlung löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/payments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newPurchasePaymentsGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Zahlung abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/payments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newPurchasePaymentsListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 string
	var q3 int
	var q4 string
	var q5 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Zahlungen auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/payments"
			q := url.Values{}
			if cmd.Flags().Changed("date-from") {
				q.Set("date_from", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("date-to") {
				q.Set("date_to", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("purchase-id") {
				q.Set("purchase_id", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q5))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "date-from", "", "Payment date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q1, "date-to", "", "Payment date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q2, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q3, "page", 0, "Page number, starting at 1.")
	f.StringVar(&q4, "purchase-id", "", "Single ID or comma-separated list.")
	f.StringVar(&q5, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newPurchasePaymentsPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var v3 bool
	var v4 int
	var v5 int
	var v6 float64
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Zahlung teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/payments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v0
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v1
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v2
			}
			if cmd.Flags().Changed("partially-paid") {
				body["partially_paid"] = v3
			}
			if cmd.Flags().Changed("payment-account-id") {
				body["payment_account_id"] = v4
			}
			if cmd.Flags().Changed("purchase-id") {
				body["purchase_id"] = v5
			}
			if cmd.Flags().Changed("total") {
				body["total"] = v6
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "currency", "", "")
	f.StringVar(&v1, "date", "", "")
	f.StringVar(&v2, "description", "", "")
	f.BoolVar(&v3, "partially-paid", false, "Indicates whether the purchase is partially paid.")
	f.IntVar(&v4, "payment-account-id", 0, "")
	f.IntVar(&v5, "purchase-id", 0, "")
	f.Float64Var(&v6, "total", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newPurchasePaymentsUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var v3 bool
	var v4 int
	var v5 int
	var v6 float64
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Zahlung aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/purchases/payments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v0
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v1
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v2
			}
			if cmd.Flags().Changed("partially-paid") {
				body["partially_paid"] = v3
			}
			if cmd.Flags().Changed("payment-account-id") {
				body["payment_account_id"] = v4
			}
			if cmd.Flags().Changed("purchase-id") {
				body["purchase_id"] = v5
			}
			if cmd.Flags().Changed("total") {
				body["total"] = v6
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "currency", "", "")
	f.StringVar(&v1, "date", "", "")
	f.StringVar(&v2, "description", "", "")
	f.BoolVar(&v3, "partially-paid", false, "Indicates whether the purchase is partially paid.")
	f.IntVar(&v4, "payment-account-id", 0, "")
	f.IntVar(&v5, "purchase-id", 0, "")
	f.Float64Var(&v6, "total", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
