// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newReceiptsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "receipts",
		Short: "Belege verwalten",
	}
	cmd.AddCommand(
		newReceiptsCreateCmd(app),
		newReceiptsDeleteCmd(app),
		newReceiptsGetCmd(app),
		newReceiptsListCmd(app),
		newReceiptsPatchCmd(app),
		newReceiptsUpdateCmd(app),
	)
	return cmd
}

func newReceiptsCreateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 string
	var v3 string
	var v4 int
	var v5 string
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Beleg erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/receipts"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v1
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v2
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v3
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v4
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "")
	f.StringVar(&v1, "currency", "", "")
	f.StringVar(&v2, "date", "", "")
	f.StringVar(&v3, "info", "", "")
	f.IntVar(&v4, "project-id", 0, "")
	f.StringVar(&v5, "title", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newReceiptsDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Beleg löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/receipts/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newReceiptsGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Beleg abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/receipts/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newReceiptsListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 int
	var q3 int
	var q4 int
	var q5 int
	var q6 string
	var q7 bool
	var q8 string
	var q9 string
	var q10 int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Belege auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/receipts"
			q := url.Values{}
			if cmd.Flags().Changed("from") {
				q.Set("from", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("project-id") {
				q.Set("project_id", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("purchase-category-id") {
				q.Set("purchase_category_id", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("refund-request-id") {
				q.Set("refund_request_id", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("submitted") {
				q.Set("submitted", fmt.Sprint(q7))
			}
			if cmd.Flags().Changed("to") {
				q.Set("to", fmt.Sprint(q8))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q9))
			}
			if cmd.Flags().Changed("user-id") {
				q.Set("user_id", fmt.Sprint(q10))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "from", "", "Receipt date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q1, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q2, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q3, "per-page", 0, "Page size.")
	f.IntVar(&q4, "project-id", 0, "")
	f.IntVar(&q5, "purchase-category-id", 0, "")
	f.StringVar(&q6, "refund-request-id", "", "Single ID or comma-separated list.")
	f.BoolVar(&q7, "submitted", false, "`true` for submitted/closed receipts, `false` for pending.")
	f.StringVar(&q8, "to", "", "Receipt date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q9, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	f.IntVar(&q10, "user-id", 0, "")
	return cmd
}

func newReceiptsPatchCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 string
	var v3 string
	var v4 int
	var v5 string
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Beleg teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/receipts/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v1
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v2
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v3
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v4
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "")
	f.StringVar(&v1, "currency", "", "")
	f.StringVar(&v2, "date", "", "")
	f.StringVar(&v3, "info", "", "")
	f.IntVar(&v4, "project-id", 0, "")
	f.StringVar(&v5, "title", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newReceiptsUpdateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 string
	var v3 string
	var v4 int
	var v5 string
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Beleg aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/receipts/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("currency") {
				body["currency"] = v1
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v2
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v3
			}
			if cmd.Flags().Changed("project-id") {
				body["project_id"] = v4
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "")
	f.StringVar(&v1, "currency", "", "")
	f.StringVar(&v2, "date", "", "")
	f.StringVar(&v3, "info", "", "")
	f.IntVar(&v4, "project-id", 0, "")
	f.StringVar(&v5, "title", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
