// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newRecurringExpensesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "recurring-expenses",
		Short: "Wiederkehrende Ausgaben verwalten",
	}
	cmd.AddCommand(
		newRecurringExpensesCreateCmd(app),
		newRecurringExpensesDeleteCmd(app),
		newRecurringExpensesGetCmd(app),
		newRecurringExpensesListCmd(app),
		newRecurringExpensesListAllCmd(app),
		newRecurringExpensesPatchCmd(app),
		newRecurringExpensesRecurCmd(app),
		newRecurringExpensesUpdateCmd(app),
	)
	return cmd
}

func newRecurringExpensesCreateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 bool
	var v2 bool
	var v3 string
	var v4 string
	var v5 string
	var v6 bool
	var v7 float64
	var v8 string
	var v9 string
	var v10 string
	var v11 string
	var v12 float64
	var v13 float64
	var v14 int
	var data string
	cmd := &cobra.Command{
		Use:   "create <project-id>",
		Short: "Wiederkehrende Ausgabe erstellen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/recurring_expenses"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("billing-in-advance") {
				body["billing_in_advance"] = v1
			}
			if cmd.Flags().Changed("budget-relevant") {
				body["budget_relevant"] = v2
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v3
			}
			if cmd.Flags().Changed("finish-date") {
				body["finish_date"] = v4
			}
			if cmd.Flags().Changed("period") {
				body["period"] = v5
			}
			if cmd.Flags().Changed("purchase-assignment-locked") {
				body["purchase_assignment_locked"] = v6
			}
			if cmd.Flags().Changed("quantity") {
				body["quantity"] = v7
			}
			if cmd.Flags().Changed("service-period-direction") {
				body["service_period_direction"] = v8
			}
			if cmd.Flags().Changed("start-date") {
				body["start_date"] = v9
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v10
			}
			if cmd.Flags().Changed("unit") {
				body["unit"] = v11
			}
			if cmd.Flags().Changed("unit-cost") {
				body["unit_cost"] = v12
			}
			if cmd.Flags().Changed("unit-price") {
				body["unit_price"] = v13
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v14
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "")
	f.BoolVar(&v1, "billing-in-advance", false, "Deprecated alias for `service_period_direction` (true=forward, false=backward).")
	f.BoolVar(&v2, "budget-relevant", false, "")
	f.StringVar(&v3, "description", "", "")
	f.StringVar(&v4, "finish-date", "", "")
	f.StringVar(&v5, "period", "", "")
	f.BoolVar(&v6, "purchase-assignment-locked", false, "")
	f.Float64Var(&v7, "quantity", 0, "")
	f.StringVar(&v8, "service-period-direction", "", "")
	f.StringVar(&v9, "start-date", "", "")
	f.StringVar(&v10, "title", "", "")
	f.StringVar(&v11, "unit", "", "")
	f.Float64Var(&v12, "unit-cost", 0, "")
	f.Float64Var(&v13, "unit-price", 0, "")
	f.IntVar(&v14, "user-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newRecurringExpensesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <project-id> <id>",
		Short: "Wiederkehrende Ausgabe löschen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/recurring_expenses/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newRecurringExpensesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <project-id> <id>",
		Short: "Wiederkehrende Ausgabe abrufen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/recurring_expenses/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newRecurringExpensesListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 int
	var q3 int
	var q4 string
	var q5 string
	cmd := &cobra.Command{
		Use:   "list <project-id>",
		Short: "Wiederkehrende Ausgaben auflisten",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/recurring_expenses"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			q := url.Values{}
			if cmd.Flags().Changed("custom-properties") {
				q.Set("custom_properties", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("sort-by") {
				q.Set("sort_by", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q5))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "custom-properties", "", "Filter by custom field values.")
	f.StringVar(&q1, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q2, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q3, "per-page", 0, "Page size.")
	f.StringVar(&q4, "sort-by", "", "Field and optional direction, e.g. `title desc`.")
	f.StringVar(&q5, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newRecurringExpensesListAllCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 int
	var q3 int
	var q4 int
	var q5 string
	var q6 string
	cmd := &cobra.Command{
		Use:   "list-all",
		Short: "Wiederkehrende Ausgaben auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/recurring_expenses"
			q := url.Values{}
			if cmd.Flags().Changed("custom-properties") {
				q.Set("custom_properties", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("project-id") {
				q.Set("project_id", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("sort-by") {
				q.Set("sort_by", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q6))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "custom-properties", "", "Filter by custom field values.")
	f.StringVar(&q1, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q2, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q3, "per-page", 0, "Page size.")
	f.IntVar(&q4, "project-id", 0, "")
	f.StringVar(&q5, "sort-by", "", "Field and optional direction, e.g. `title desc`.")
	f.StringVar(&q6, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newRecurringExpensesPatchCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 bool
	var v2 bool
	var v3 string
	var v4 string
	var v5 string
	var v6 bool
	var v7 float64
	var v8 string
	var v9 string
	var v10 string
	var v11 string
	var v12 float64
	var v13 float64
	var v14 int
	var data string
	cmd := &cobra.Command{
		Use:   "patch <project-id> <id>",
		Short: "Wiederkehrende Ausgabe teilweise aktualisieren",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/recurring_expenses/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("billing-in-advance") {
				body["billing_in_advance"] = v1
			}
			if cmd.Flags().Changed("budget-relevant") {
				body["budget_relevant"] = v2
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v3
			}
			if cmd.Flags().Changed("finish-date") {
				body["finish_date"] = v4
			}
			if cmd.Flags().Changed("period") {
				body["period"] = v5
			}
			if cmd.Flags().Changed("purchase-assignment-locked") {
				body["purchase_assignment_locked"] = v6
			}
			if cmd.Flags().Changed("quantity") {
				body["quantity"] = v7
			}
			if cmd.Flags().Changed("service-period-direction") {
				body["service_period_direction"] = v8
			}
			if cmd.Flags().Changed("start-date") {
				body["start_date"] = v9
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v10
			}
			if cmd.Flags().Changed("unit") {
				body["unit"] = v11
			}
			if cmd.Flags().Changed("unit-cost") {
				body["unit_cost"] = v12
			}
			if cmd.Flags().Changed("unit-price") {
				body["unit_price"] = v13
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v14
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "")
	f.BoolVar(&v1, "billing-in-advance", false, "Deprecated alias for `service_period_direction` (true=forward, false=backward).")
	f.BoolVar(&v2, "budget-relevant", false, "")
	f.StringVar(&v3, "description", "", "")
	f.StringVar(&v4, "finish-date", "", "")
	f.StringVar(&v5, "period", "", "")
	f.BoolVar(&v6, "purchase-assignment-locked", false, "")
	f.Float64Var(&v7, "quantity", 0, "")
	f.StringVar(&v8, "service-period-direction", "", "")
	f.StringVar(&v9, "start-date", "", "")
	f.StringVar(&v10, "title", "", "")
	f.StringVar(&v11, "unit", "", "")
	f.Float64Var(&v12, "unit-cost", 0, "")
	f.Float64Var(&v13, "unit-price", 0, "")
	f.IntVar(&v14, "user-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newRecurringExpensesRecurCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "recur <project-id> <id>",
		Short: "Wiederkehrende Ausgabe erneut anlegen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/recurring_expenses/{id}/recur"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
			})
		},
	}
	return cmd
}

func newRecurringExpensesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 bool
	var v2 bool
	var v3 string
	var v4 string
	var v5 string
	var v6 bool
	var v7 float64
	var v8 string
	var v9 string
	var v10 string
	var v11 string
	var v12 float64
	var v13 float64
	var v14 int
	var data string
	cmd := &cobra.Command{
		Use:   "update <project-id> <id>",
		Short: "Wiederkehrende Ausgabe aktualisieren",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/recurring_expenses/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v0
			}
			if cmd.Flags().Changed("billing-in-advance") {
				body["billing_in_advance"] = v1
			}
			if cmd.Flags().Changed("budget-relevant") {
				body["budget_relevant"] = v2
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v3
			}
			if cmd.Flags().Changed("finish-date") {
				body["finish_date"] = v4
			}
			if cmd.Flags().Changed("period") {
				body["period"] = v5
			}
			if cmd.Flags().Changed("purchase-assignment-locked") {
				body["purchase_assignment_locked"] = v6
			}
			if cmd.Flags().Changed("quantity") {
				body["quantity"] = v7
			}
			if cmd.Flags().Changed("service-period-direction") {
				body["service_period_direction"] = v8
			}
			if cmd.Flags().Changed("start-date") {
				body["start_date"] = v9
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v10
			}
			if cmd.Flags().Changed("unit") {
				body["unit"] = v11
			}
			if cmd.Flags().Changed("unit-cost") {
				body["unit_cost"] = v12
			}
			if cmd.Flags().Changed("unit-price") {
				body["unit_price"] = v13
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v14
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "billable", false, "")
	f.BoolVar(&v1, "billing-in-advance", false, "Deprecated alias for `service_period_direction` (true=forward, false=backward).")
	f.BoolVar(&v2, "budget-relevant", false, "")
	f.StringVar(&v3, "description", "", "")
	f.StringVar(&v4, "finish-date", "", "")
	f.StringVar(&v5, "period", "", "")
	f.BoolVar(&v6, "purchase-assignment-locked", false, "")
	f.Float64Var(&v7, "quantity", 0, "")
	f.StringVar(&v8, "service-period-direction", "", "")
	f.StringVar(&v9, "start-date", "", "")
	f.StringVar(&v10, "title", "", "")
	f.StringVar(&v11, "unit", "", "")
	f.Float64Var(&v12, "unit-cost", 0, "")
	f.Float64Var(&v13, "unit-price", 0, "")
	f.IntVar(&v14, "user-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
