// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newReportsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "reports",
		Short: "Berichte verwalten",
	}
	cmd.AddCommand(
		newReportsAbsencesGetCmd(app),
		newReportsCashflowGetCmd(app),
		newReportsFinanceGetCmd(app),
		newReportsPlannedVsTrackedGetCmd(app),
		newReportsUtilizationGetCmd(app),
	)
	return cmd
}

func newReportsAbsencesGetCmd(app *cli.App) *cobra.Command {
	var q0 bool
	var q1 int
	cmd := &cobra.Command{
		Use:   "absences-get",
		Short: "Abwesenheitsbericht abrufen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/report/absences"
			q := url.Values{}
			if cmd.Flags().Changed("active") {
				q.Set("active", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("year") {
				q.Set("year", fmt.Sprint(q1))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&q0, "active", false, "")
	f.IntVar(&q1, "year", 0, "")
	return cmd
}

func newReportsCashflowGetCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 []string
	var q2 int
	var q3 int
	var q4 string
	var q5 string
	cmd := &cobra.Command{
		Use:   "cashflow-get",
		Short: "Cashflow-Bericht abrufen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/report/cashflow"
			q := url.Values{}
			if cmd.Flags().Changed("from") {
				q.Set("from", fmt.Sprint(q0))
			}
			for _, v := range q1 {
				q.Add("kinds", v)
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("term") {
				q.Set("term", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("to") {
				q.Set("to", fmt.Sprint(q5))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "from", "", "Report range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringArrayVar(&q1, "kinds", nil, "")
	f.IntVar(&q2, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q3, "per-page", 0, "Page size.")
	f.StringVar(&q4, "term", "", "")
	f.StringVar(&q5, "to", "", "Report range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	return cmd
}

func newReportsFinanceGetCmd(app *cli.App) *cobra.Command {
	var q0 int
	var q1 string
	var q2 []string
	var q3 int
	var q4 int
	var q5 string
	var q6 string
	cmd := &cobra.Command{
		Use:   "finance-get",
		Short: "Finanzbericht abrufen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/report/finance"
			q := url.Values{}
			if cmd.Flags().Changed("company-id") {
				q.Set("company_id", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("from") {
				q.Set("from", fmt.Sprint(q1))
			}
			for _, v := range q2 {
				q.Add("kinds", v)
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("term") {
				q.Set("term", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("to") {
				q.Set("to", fmt.Sprint(q6))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "company-id", 0, "")
	f.StringVar(&q1, "from", "", "Report range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringArrayVar(&q2, "kinds", nil, "")
	f.IntVar(&q3, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q4, "per-page", 0, "Page size.")
	f.StringVar(&q5, "term", "", "")
	f.StringVar(&q6, "to", "", "Report range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	return cmd
}

func newReportsPlannedVsTrackedGetCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 int
	var q2 int
	var q3 int
	var q4 string
	var q5 string
	cmd := &cobra.Command{
		Use:   "planned-vs-tracked-get",
		Short: "Bericht „Geplant vs. Erfasst“ abrufen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/report/planned_vs_tracked"
			q := url.Values{}
			if cmd.Flags().Changed("from") {
				q.Set("from", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("project-id") {
				q.Set("project_id", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("to") {
				q.Set("to", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("user-ids") {
				q.Set("user_ids", fmt.Sprint(q5))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "from", "", "Report range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.IntVar(&q1, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q2, "per-page", 0, "Page size.")
	f.IntVar(&q3, "project-id", 0, "")
	f.StringVar(&q4, "to", "", "Report range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q5, "user-ids", "", "List of user IDs as repeated params or comma-separated string.")
	return cmd
}

func newReportsUtilizationGetCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	cmd := &cobra.Command{
		Use:   "utilization-get",
		Short: "Auslastungsbericht abrufen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/report/utilization"
			q := url.Values{}
			if cmd.Flags().Changed("from") {
				q.Set("from", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("to") {
				q.Set("to", fmt.Sprint(q1))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "from", "", "Report range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q1, "to", "", "Report range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	return cmd
}
