// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newSchedulesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "schedules",
		Short: "Abwesenheiten verwalten",
	}
	cmd.AddCommand(
		newSchedulesCreateCmd(app),
		newSchedulesDeleteCmd(app),
		newSchedulesGetCmd(app),
		newSchedulesListCmd(app),
		newSchedulesPatchCmd(app),
		newSchedulesUpdateCmd(app),
	)
	return cmd
}

func newSchedulesCreateCmd(app *cli.App) *cobra.Command {
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Abwesenheit erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/schedules"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newSchedulesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Abwesenheit löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/schedules/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newSchedulesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Abwesenheit abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/schedules/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newSchedulesListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 int
	var q2 string
	var q3 string
	var q4 int
	var q5 int
	var q6 string
	var q7 string
	var q8 int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Abwesenheiten auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/schedules"
			q := url.Values{}
			if cmd.Flags().Changed("absence-code") {
				q.Set("absence_code", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("absence-request-id") {
				q.Set("absence_request_id", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("from") {
				q.Set("from", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("to") {
				q.Set("to", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q7))
			}
			if cmd.Flags().Changed("user-id") {
				q.Set("user_id", fmt.Sprint(q8))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "absence-code", "", "")
	f.IntVar(&q1, "absence-request-id", 0, "")
	f.StringVar(&q2, "from", "", "Schedule range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q3, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q4, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q5, "per-page", 0, "Page size.")
	f.StringVar(&q6, "to", "", "Schedule range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q7, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	f.IntVar(&q8, "user-id", 0, "")
	return cmd
}

func newSchedulesPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 bool
	var v2 string
	var v3 string
	var v4 bool
	var v5 string
	var v6 int
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Abwesenheit teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/schedules/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("absence-code") {
				body["absence_code"] = v0
			}
			if cmd.Flags().Changed("am") {
				body["am"] = v1
			}
			if cmd.Flags().Changed("comment") {
				body["comment"] = v2
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v3
			}
			if cmd.Flags().Changed("pm") {
				body["pm"] = v4
			}
			if cmd.Flags().Changed("symbol") {
				body["symbol"] = v5
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v6
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "absence-code", "", "")
	f.BoolVar(&v1, "am", false, "")
	f.StringVar(&v2, "comment", "", "")
	f.StringVar(&v3, "date", "", "")
	f.BoolVar(&v4, "pm", false, "")
	f.StringVar(&v5, "symbol", "", "")
	f.IntVar(&v6, "user-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newSchedulesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 bool
	var v2 string
	var v3 string
	var v4 bool
	var v5 string
	var v6 int
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Abwesenheit aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/schedules/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("absence-code") {
				body["absence_code"] = v0
			}
			if cmd.Flags().Changed("am") {
				body["am"] = v1
			}
			if cmd.Flags().Changed("comment") {
				body["comment"] = v2
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v3
			}
			if cmd.Flags().Changed("pm") {
				body["pm"] = v4
			}
			if cmd.Flags().Changed("symbol") {
				body["symbol"] = v5
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v6
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "absence-code", "", "")
	f.BoolVar(&v1, "am", false, "")
	f.StringVar(&v2, "comment", "", "")
	f.StringVar(&v3, "date", "", "")
	f.BoolVar(&v4, "pm", false, "")
	f.StringVar(&v5, "symbol", "", "")
	f.IntVar(&v6, "user-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
