// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newSessionCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "session",
		Short: "Sitzungen verwalten",
	}
	cmd.AddCommand(
		newSessionCreateCmd(app),
		newSessionGetCmd(app),
	)
	return cmd
}

func newSessionCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Sitzung erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/session"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("email") {
				body["email"] = v0
			}
			if cmd.Flags().Changed("password") {
				body["password"] = v1
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "email", "", "User email within the account referenced by the subdomain.")
	f.StringVar(&v1, "password", "", "User password.")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newSessionGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Sitzung abrufen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/session"
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}
