// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newTaggingsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "taggings",
		Short: "Labels verwalten",
	}
	cmd.AddCommand(
		newTaggingsDeleteCmd(app),
		newTaggingsListCmd(app),
		newTaggingsPatchCmd(app),
		newTaggingsUpdateCmd(app),
	)
	return cmd
}

func newTaggingsDeleteCmd(app *cli.App) *cobra.Command {
	var data string
	cmd := &cobra.Command{
		Use:   "delete <taggable-type> <taggable-id>",
		Short: "Label löschen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/taggings/{taggable_type}/{taggable_id}"
			path = strings.Replace(path, "{taggable_type}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{taggable_id}", url.PathEscape(args[1]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newTaggingsListCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list <taggable-type> <taggable-id>",
		Short: "Labels auflisten",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/taggings/{taggable_type}/{taggable_id}"
			path = strings.Replace(path, "{taggable_type}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{taggable_id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newTaggingsPatchCmd(app *cli.App) *cobra.Command {
	var data string
	cmd := &cobra.Command{
		Use:   "patch <taggable-type> <taggable-id>",
		Short: "Label teilweise aktualisieren",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/taggings/{taggable_type}/{taggable_id}"
			path = strings.Replace(path, "{taggable_type}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{taggable_id}", url.PathEscape(args[1]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newTaggingsUpdateCmd(app *cli.App) *cobra.Command {
	var data string
	cmd := &cobra.Command{
		Use:   "update <taggable-type> <taggable-id>",
		Short: "Label aktualisieren",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/taggings/{taggable_type}/{taggable_id}"
			path = strings.Replace(path, "{taggable_type}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{taggable_id}", url.PathEscape(args[1]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
