// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newTagsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tags",
		Short: "Labels verwalten",
	}
	cmd.AddCommand(
		newTagsCreateCmd(app),
		newTagsDeleteCmd(app),
		newTagsGetCmd(app),
		newTagsListCmd(app),
		newTagsPatchCmd(app),
		newTagsUpdateCmd(app),
	)
	return cmd
}

func newTagsCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 string
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Label erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/tags"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("color") {
				body["color"] = v0
			}
			if cmd.Flags().Changed("context") {
				body["context"] = v1
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v2
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "color", "", "")
	f.StringVar(&v1, "context", "", "`Project` is mapped to internal `Assignment`.")
	f.StringVar(&v2, "name", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newTagsDeleteCmd(app *cli.App) *cobra.Command {
	var q0 int
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Label löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/tags/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			q := url.Values{}
			if cmd.Flags().Changed("merge-tag-id") {
				q.Set("merge_tag_id", fmt.Sprint(q0))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "merge-tag-id", 0, "Optional tag ID to merge existing taggings into.")
	return cmd
}

func newTagsGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Label abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/tags/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newTagsListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 int
	var q3 int
	var q4 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Labels auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/tags"
			q := url.Values{}
			if cmd.Flags().Changed("context") {
				q.Set("context", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q4))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "context", "", "Tag context.")
	f.StringVar(&q1, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q2, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q3, "per-page", 0, "Page size.")
	f.StringVar(&q4, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newTagsPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Label teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/tags/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("color") {
				body["color"] = v0
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v1
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "color", "", "")
	f.StringVar(&v1, "name", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newTagsUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Label aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/tags/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("color") {
				body["color"] = v0
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v1
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "color", "", "")
	f.StringVar(&v1, "name", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
