// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newTasksCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tasks",
		Short: "Leistungen verwalten",
	}
	cmd.AddCommand(
		newTasksCreateCmd(app),
		newTasksDeleteCmd(app),
		newTasksDestroyAllCmd(app),
		newTasksGetCmd(app),
		newTasksListCmd(app),
		newTasksPatchCmd(app),
		newTasksUpdateCmd(app),
	)
	return cmd
}

func newTasksCreateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 bool
	var v2 float64
	var v3 string
	var v4 float64
	var v5 int
	var v6 string
	var data string
	cmd := &cobra.Command{
		Use:   "create <project-id>",
		Short: "Leistung erstellen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/tasks"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("active") {
				body["active"] = v0
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v1
			}
			if cmd.Flags().Changed("budget") {
				body["budget"] = v2
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v3
			}
			if cmd.Flags().Changed("hourly-rate") {
				body["hourly_rate"] = v4
			}
			if cmd.Flags().Changed("index") {
				body["index"] = v5
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v6
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "active", false, "")
	f.BoolVar(&v1, "billable", false, "")
	f.Float64Var(&v2, "budget", 0, "")
	f.StringVar(&v3, "description", "", "")
	f.Float64Var(&v4, "hourly-rate", 0, "")
	f.IntVar(&v5, "index", 0, "")
	f.StringVar(&v6, "name", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newTasksDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <project-id> <id>",
		Short: "Leistung löschen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/tasks/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newTasksDestroyAllCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "destroy-all <project-id>",
		Short: "Alle Projekt-Leistungen löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/tasks/destroy_all"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newTasksGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <project-id> <id>",
		Short: "Leistung abrufen",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/tasks/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newTasksListCmd(app *cli.App) *cobra.Command {
	var q0 int
	var q1 int
	var q2 string
	cmd := &cobra.Command{
		Use:   "list <project-id>",
		Short: "Leistungen auflisten",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/tasks"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			q := url.Values{}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q2))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q1, "per-page", 0, "Page size.")
	f.StringVar(&q2, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newTasksPatchCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 bool
	var v2 float64
	var v3 string
	var v4 float64
	var v5 int
	var v6 string
	var data string
	cmd := &cobra.Command{
		Use:   "patch <project-id> <id>",
		Short: "Leistung teilweise aktualisieren",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/tasks/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("active") {
				body["active"] = v0
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v1
			}
			if cmd.Flags().Changed("budget") {
				body["budget"] = v2
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v3
			}
			if cmd.Flags().Changed("hourly-rate") {
				body["hourly_rate"] = v4
			}
			if cmd.Flags().Changed("index") {
				body["index"] = v5
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v6
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "active", false, "")
	f.BoolVar(&v1, "billable", false, "")
	f.Float64Var(&v2, "budget", 0, "")
	f.StringVar(&v3, "description", "", "")
	f.Float64Var(&v4, "hourly-rate", 0, "")
	f.IntVar(&v5, "index", 0, "")
	f.StringVar(&v6, "name", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newTasksUpdateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 bool
	var v2 float64
	var v3 string
	var v4 float64
	var v5 int
	var v6 string
	var data string
	cmd := &cobra.Command{
		Use:   "update <project-id> <id>",
		Short: "Leistung aktualisieren",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/projects/{project_id}/tasks/{id}"
			path = strings.Replace(path, "{project_id}", url.PathEscape(args[0]), 1)
			path = strings.Replace(path, "{id}", url.PathEscape(args[1]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("active") {
				body["active"] = v0
			}
			if cmd.Flags().Changed("billable") {
				body["billable"] = v1
			}
			if cmd.Flags().Changed("budget") {
				body["budget"] = v2
			}
			if cmd.Flags().Changed("description") {
				body["description"] = v3
			}
			if cmd.Flags().Changed("hourly-rate") {
				body["hourly_rate"] = v4
			}
			if cmd.Flags().Changed("index") {
				body["index"] = v5
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v6
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "active", false, "")
	f.BoolVar(&v1, "billable", false, "")
	f.Float64Var(&v2, "budget", 0, "")
	f.StringVar(&v3, "description", "", "")
	f.Float64Var(&v4, "hourly-rate", 0, "")
	f.IntVar(&v5, "index", 0, "")
	f.StringVar(&v6, "name", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
