// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newUserRolesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "user-roles",
		Short: "Benutzerrollen verwalten",
	}
	cmd.AddCommand(
		newUserRolesListCmd(app),
	)
	return cmd
}

func newUserRolesListCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Benutzerrollen auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/roles"
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}
