// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newUsersCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "users",
		Short: "Personen verwalten",
	}
	cmd.AddCommand(
		newUsersCreateCmd(app),
		newUsersDeleteCmd(app),
		newUsersGetCmd(app),
		newUsersListCmd(app),
		newUsersPatchCmd(app),
		newUsersPerformanceReportGetCmd(app),
		newUsersUpdateCmd(app),
	)
	return cmd
}

func newUsersCreateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 string
	var v3 string
	var v4 bool
	var v5 string
	var v6 string
	var v7 string
	var v8 string
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 string
	var v14 int
	var v15 int
	var v16 bool
	var v17 string
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Person erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("active") {
				body["active"] = v0
			}
			if cmd.Flags().Changed("bday") {
				body["bday"] = v1
			}
			if cmd.Flags().Changed("credit-number") {
				body["credit_number"] = v2
			}
			if cmd.Flags().Changed("email") {
				body["email"] = v3
			}
			if cmd.Flags().Changed("external") {
				body["external"] = v4
			}
			if cmd.Flags().Changed("firstname") {
				body["firstname"] = v5
			}
			if cmd.Flags().Changed("home-address") {
				body["home_address"] = v6
			}
			if cmd.Flags().Changed("iban") {
				body["iban"] = v7
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v8
			}
			if cmd.Flags().Changed("language") {
				body["language"] = v9
			}
			if cmd.Flags().Changed("lastname") {
				body["lastname"] = v10
			}
			if cmd.Flags().Changed("mobile-phone") {
				body["mobile_phone"] = v11
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v12
			}
			if cmd.Flags().Changed("password") {
				body["password"] = v13
			}
			if cmd.Flags().Changed("role-id") {
				body["role_id"] = v14
			}
			if cmd.Flags().Changed("unit-id") {
				body["unit_id"] = v15
			}
			if cmd.Flags().Changed("welcome-email") {
				body["welcome_email"] = v16
			}
			if cmd.Flags().Changed("work-phone") {
				body["work_phone"] = v17
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "active", false, "")
	f.StringVar(&v1, "bday", "", "")
	f.StringVar(&v2, "credit-number", "", "Bookkeeping credit account number for supplier transactions (for refunds).")
	f.StringVar(&v3, "email", "", "")
	f.BoolVar(&v4, "external", false, "")
	f.StringVar(&v5, "firstname", "", "")
	f.StringVar(&v6, "home-address", "", "")
	f.StringVar(&v7, "iban", "", "")
	f.StringVar(&v8, "info", "", "")
	f.StringVar(&v9, "language", "", "")
	f.StringVar(&v10, "lastname", "", "Alias for `name`.")
	f.StringVar(&v11, "mobile-phone", "", "")
	f.StringVar(&v12, "name", "", "")
	f.StringVar(&v13, "password", "", "")
	f.IntVar(&v14, "role-id", 0, "")
	f.IntVar(&v15, "unit-id", 0, "")
	f.BoolVar(&v16, "welcome-email", false, "Applied on create, defaults to `true`.")
	f.StringVar(&v17, "work-phone", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newUsersDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Person löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newUsersGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Person abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newUsersListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 string
	var q3 bool
	var q4 int
	var q5 int
	var q6 string
	var q7 string
	var q8 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Personen auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users"
			q := url.Values{}
			if cmd.Flags().Changed("custom-properties") {
				q.Set("custom_properties", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("email") {
				q.Set("email", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("include-archived") {
				q.Set("include_archived", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("sort-by") {
				q.Set("sort_by", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("tags") {
				q.Set("tags", fmt.Sprint(q7))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q8))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "custom-properties", "", "Filter by custom field values.")
	f.StringVar(&q1, "email", "", "Filter by exact email address (e.g. `max.muster@example.com`).")
	f.StringVar(&q2, "ids", "", "Comma-separated IDs.")
	f.BoolVar(&q3, "include-archived", false, "")
	f.IntVar(&q4, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q5, "per-page", 0, "Page size.")
	f.StringVar(&q6, "sort-by", "", "Field and optional direction, e.g. `title desc`.")
	f.StringVar(&q7, "tags", "", "Comma-separated user tag names.")
	f.StringVar(&q8, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}

func newUsersPatchCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 string
	var v3 string
	var v4 bool
	var v5 string
	var v6 string
	var v7 string
	var v8 string
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 string
	var v14 int
	var v15 int
	var v16 bool
	var v17 string
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Person teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("active") {
				body["active"] = v0
			}
			if cmd.Flags().Changed("bday") {
				body["bday"] = v1
			}
			if cmd.Flags().Changed("credit-number") {
				body["credit_number"] = v2
			}
			if cmd.Flags().Changed("email") {
				body["email"] = v3
			}
			if cmd.Flags().Changed("external") {
				body["external"] = v4
			}
			if cmd.Flags().Changed("firstname") {
				body["firstname"] = v5
			}
			if cmd.Flags().Changed("home-address") {
				body["home_address"] = v6
			}
			if cmd.Flags().Changed("iban") {
				body["iban"] = v7
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v8
			}
			if cmd.Flags().Changed("language") {
				body["language"] = v9
			}
			if cmd.Flags().Changed("lastname") {
				body["lastname"] = v10
			}
			if cmd.Flags().Changed("mobile-phone") {
				body["mobile_phone"] = v11
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v12
			}
			if cmd.Flags().Changed("password") {
				body["password"] = v13
			}
			if cmd.Flags().Changed("role-id") {
				body["role_id"] = v14
			}
			if cmd.Flags().Changed("unit-id") {
				body["unit_id"] = v15
			}
			if cmd.Flags().Changed("welcome-email") {
				body["welcome_email"] = v16
			}
			if cmd.Flags().Changed("work-phone") {
				body["work_phone"] = v17
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "active", false, "")
	f.StringVar(&v1, "bday", "", "")
	f.StringVar(&v2, "credit-number", "", "Bookkeeping credit account number for supplier transactions (for refunds).")
	f.StringVar(&v3, "email", "", "")
	f.BoolVar(&v4, "external", false, "")
	f.StringVar(&v5, "firstname", "", "")
	f.StringVar(&v6, "home-address", "", "")
	f.StringVar(&v7, "iban", "", "")
	f.StringVar(&v8, "info", "", "")
	f.StringVar(&v9, "language", "", "")
	f.StringVar(&v10, "lastname", "", "Alias for `name`.")
	f.StringVar(&v11, "mobile-phone", "", "")
	f.StringVar(&v12, "name", "", "")
	f.StringVar(&v13, "password", "", "")
	f.IntVar(&v14, "role-id", 0, "")
	f.IntVar(&v15, "unit-id", 0, "")
	f.BoolVar(&v16, "welcome-email", false, "Applied on create, defaults to `true`.")
	f.StringVar(&v17, "work-phone", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newUsersPerformanceReportGetCmd(app *cli.App) *cobra.Command {
	var q0 int
	cmd := &cobra.Command{
		Use:   "performance-report-get <id>",
		Short: "Leistungsbericht der Person abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/{id}/performance_report"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			q := url.Values{}
			if cmd.Flags().Changed("year") {
				q.Set("year", fmt.Sprint(q0))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&q0, "year", 0, "Report year. Must be between 2000 and 2100.")
	return cmd
}

func newUsersUpdateCmd(app *cli.App) *cobra.Command {
	var v0 bool
	var v1 string
	var v2 string
	var v3 string
	var v4 bool
	var v5 string
	var v6 string
	var v7 string
	var v8 string
	var v9 string
	var v10 string
	var v11 string
	var v12 string
	var v13 string
	var v14 int
	var v15 int
	var v16 bool
	var v17 string
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Person aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("active") {
				body["active"] = v0
			}
			if cmd.Flags().Changed("bday") {
				body["bday"] = v1
			}
			if cmd.Flags().Changed("credit-number") {
				body["credit_number"] = v2
			}
			if cmd.Flags().Changed("email") {
				body["email"] = v3
			}
			if cmd.Flags().Changed("external") {
				body["external"] = v4
			}
			if cmd.Flags().Changed("firstname") {
				body["firstname"] = v5
			}
			if cmd.Flags().Changed("home-address") {
				body["home_address"] = v6
			}
			if cmd.Flags().Changed("iban") {
				body["iban"] = v7
			}
			if cmd.Flags().Changed("info") {
				body["info"] = v8
			}
			if cmd.Flags().Changed("language") {
				body["language"] = v9
			}
			if cmd.Flags().Changed("lastname") {
				body["lastname"] = v10
			}
			if cmd.Flags().Changed("mobile-phone") {
				body["mobile_phone"] = v11
			}
			if cmd.Flags().Changed("name") {
				body["name"] = v12
			}
			if cmd.Flags().Changed("password") {
				body["password"] = v13
			}
			if cmd.Flags().Changed("role-id") {
				body["role_id"] = v14
			}
			if cmd.Flags().Changed("unit-id") {
				body["unit_id"] = v15
			}
			if cmd.Flags().Changed("welcome-email") {
				body["welcome_email"] = v16
			}
			if cmd.Flags().Changed("work-phone") {
				body["work_phone"] = v17
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&v0, "active", false, "")
	f.StringVar(&v1, "bday", "", "")
	f.StringVar(&v2, "credit-number", "", "Bookkeeping credit account number for supplier transactions (for refunds).")
	f.StringVar(&v3, "email", "", "")
	f.BoolVar(&v4, "external", false, "")
	f.StringVar(&v5, "firstname", "", "")
	f.StringVar(&v6, "home-address", "", "")
	f.StringVar(&v7, "iban", "", "")
	f.StringVar(&v8, "info", "", "")
	f.StringVar(&v9, "language", "", "")
	f.StringVar(&v10, "lastname", "", "Alias for `name`.")
	f.StringVar(&v11, "mobile-phone", "", "")
	f.StringVar(&v12, "name", "", "")
	f.StringVar(&v13, "password", "", "")
	f.IntVar(&v14, "role-id", 0, "")
	f.IntVar(&v15, "unit-id", 0, "")
	f.BoolVar(&v16, "welcome-email", false, "Applied on create, defaults to `true`.")
	f.StringVar(&v17, "work-phone", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
