// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newUserHolidaysCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "user-holidays",
		Short: "Urlaubsansprüche verwalten",
	}
	cmd.AddCommand(
		newUserHolidaysCreateCmd(app),
		newUserHolidaysDeleteCmd(app),
		newUserHolidaysGetCmd(app),
		newUserHolidaysListCmd(app),
		newUserHolidaysPatchCmd(app),
		newUserHolidaysUpdateCmd(app),
	)
	return cmd
}

func newUserHolidaysCreateCmd(app *cli.App) *cobra.Command {
	var v0 int
	var v1 float64
	var v2 float64
	var v3 string
	var v4 int
	var v5 int
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Urlaubsanspruch erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/holidays"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("creator-id") {
				body["creator_id"] = v0
			}
			if cmd.Flags().Changed("days") {
				body["days"] = v1
			}
			if cmd.Flags().Changed("hours") {
				body["hours"] = v2
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v3
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v4
			}
			if cmd.Flags().Changed("year") {
				body["year"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&v0, "creator-id", 0, "")
	f.Float64Var(&v1, "days", 0, "")
	f.Float64Var(&v2, "hours", 0, "")
	f.StringVar(&v3, "title", "", "")
	f.IntVar(&v4, "user-id", 0, "")
	f.IntVar(&v5, "year", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newUserHolidaysDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Urlaubsanspruch löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/holidays/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newUserHolidaysGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Urlaubsanspruch abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/holidays/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newUserHolidaysListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 int
	var q2 int
	var q3 string
	var q4 int
	var q5 int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Urlaubsansprüche auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/holidays"
			q := url.Values{}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("user-id") {
				q.Set("user_id", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("year") {
				q.Set("year", fmt.Sprint(q5))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q1, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q2, "per-page", 0, "Page size.")
	f.StringVar(&q3, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	f.IntVar(&q4, "user-id", 0, "")
	f.IntVar(&q5, "year", 0, "")
	return cmd
}

func newUserHolidaysPatchCmd(app *cli.App) *cobra.Command {
	var v0 int
	var v1 float64
	var v2 float64
	var v3 string
	var v4 int
	var v5 int
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Urlaubsanspruch teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/holidays/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("creator-id") {
				body["creator_id"] = v0
			}
			if cmd.Flags().Changed("days") {
				body["days"] = v1
			}
			if cmd.Flags().Changed("hours") {
				body["hours"] = v2
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v3
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v4
			}
			if cmd.Flags().Changed("year") {
				body["year"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&v0, "creator-id", 0, "")
	f.Float64Var(&v1, "days", 0, "")
	f.Float64Var(&v2, "hours", 0, "")
	f.StringVar(&v3, "title", "", "")
	f.IntVar(&v4, "user-id", 0, "")
	f.IntVar(&v5, "year", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newUserHolidaysUpdateCmd(app *cli.App) *cobra.Command {
	var v0 int
	var v1 float64
	var v2 float64
	var v3 string
	var v4 int
	var v5 int
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Urlaubsanspruch aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/holidays/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("creator-id") {
				body["creator_id"] = v0
			}
			if cmd.Flags().Changed("days") {
				body["days"] = v1
			}
			if cmd.Flags().Changed("hours") {
				body["hours"] = v2
			}
			if cmd.Flags().Changed("title") {
				body["title"] = v3
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v4
			}
			if cmd.Flags().Changed("year") {
				body["year"] = v5
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.IntVar(&v0, "creator-id", 0, "")
	f.Float64Var(&v1, "days", 0, "")
	f.Float64Var(&v2, "hours", 0, "")
	f.StringVar(&v3, "title", "", "")
	f.IntVar(&v4, "user-id", 0, "")
	f.IntVar(&v5, "year", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
