// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newUserPresencesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "user-presences",
		Short: "Arbeitszeiten verwalten",
	}
	cmd.AddCommand(
		newUserPresencesCreateCmd(app),
		newUserPresencesDeleteCmd(app),
		newUserPresencesGetCmd(app),
		newUserPresencesListCmd(app),
		newUserPresencesPatchCmd(app),
		newUserPresencesTouchCmd(app),
		newUserPresencesUpdateCmd(app),
	)
	return cmd
}

func newUserPresencesCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 bool
	var v3 string
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Arbeitszeit erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/presences"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v0
			}
			if cmd.Flags().Changed("from") {
				body["from"] = v1
			}
			if cmd.Flags().Changed("is-home-office") {
				body["is_home_office"] = v2
			}
			if cmd.Flags().Changed("to") {
				body["to"] = v3
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "date", "", "")
	f.StringVar(&v1, "from", "", "")
	f.BoolVar(&v2, "is-home-office", false, "")
	f.StringVar(&v3, "to", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newUserPresencesDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Arbeitszeit löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/presences/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newUserPresencesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Arbeitszeit abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/presences/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newUserPresencesListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 bool
	var q3 int
	var q4 int
	var q5 string
	var q6 string
	var q7 int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Arbeitszeiten auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/presences"
			q := url.Values{}
			if cmd.Flags().Changed("from") {
				q.Set("from", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("is-home-office") {
				q.Set("is_home_office", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("to") {
				q.Set("to", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q6))
			}
			if cmd.Flags().Changed("user-id") {
				q.Set("user_id", fmt.Sprint(q7))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "from", "", "Presence date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q1, "ids", "", "Comma-separated IDs.")
	f.BoolVar(&q2, "is-home-office", false, "")
	f.IntVar(&q3, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q4, "per-page", 0, "Page size.")
	f.StringVar(&q5, "to", "", "Presence date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q6, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	f.IntVar(&q7, "user-id", 0, "")
	return cmd
}

func newUserPresencesPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 bool
	var v3 string
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Arbeitszeit teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/presences/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v0
			}
			if cmd.Flags().Changed("from") {
				body["from"] = v1
			}
			if cmd.Flags().Changed("is-home-office") {
				body["is_home_office"] = v2
			}
			if cmd.Flags().Changed("to") {
				body["to"] = v3
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "date", "", "")
	f.StringVar(&v1, "from", "", "")
	f.BoolVar(&v2, "is-home-office", false, "")
	f.StringVar(&v3, "to", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newUserPresencesTouchCmd(app *cli.App) *cobra.Command {
	var q0 bool
	var q1 bool
	cmd := &cobra.Command{
		Use:   "touch",
		Short: "Arbeitszeit erfassen (touch)",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/presences/touch"
			q := url.Values{}
			if cmd.Flags().Changed("is-home-office") {
				q.Set("is_home_office", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("override") {
				q.Set("override", fmt.Sprint(q1))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&q0, "is-home-office", false, "")
	f.BoolVar(&q1, "override", false, "")
	return cmd
}

func newUserPresencesUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 bool
	var v3 string
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Arbeitszeit aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/presences/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("date") {
				body["date"] = v0
			}
			if cmd.Flags().Changed("from") {
				body["from"] = v1
			}
			if cmd.Flags().Changed("is-home-office") {
				body["is_home_office"] = v2
			}
			if cmd.Flags().Changed("to") {
				body["to"] = v3
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "date", "", "")
	f.StringVar(&v1, "from", "", "")
	f.BoolVar(&v2, "is-home-office", false, "")
	f.StringVar(&v3, "to", "", "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
