// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newUserEmploymentsCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "user-employments",
		Short: "Wochenmodelle verwalten",
	}
	cmd.AddCommand(
		newUserEmploymentsCreateCmd(app),
		newUserEmploymentsDeleteCmd(app),
		newUserEmploymentsGetCmd(app),
		newUserEmploymentsListCmd(app),
		newUserEmploymentsPatchCmd(app),
		newUserEmploymentsUpdateCmd(app),
	)
	return cmd
}

func newUserEmploymentsCreateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 int
	var data string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Wochenmodell erstellen",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/employments"
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("from") {
				body["from"] = v0
			}
			if cmd.Flags().Changed("to") {
				body["to"] = v1
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v2
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "POST",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "from", "", "")
	f.StringVar(&v1, "to", "", "")
	f.IntVar(&v2, "user-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newUserEmploymentsDeleteCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Wochenmodell löschen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/employments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "DELETE",
				Path:   path,
			})
		},
	}
	return cmd
}

func newUserEmploymentsGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Wochenmodell abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/employments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newUserEmploymentsListCmd(app *cli.App) *cobra.Command {
	var q0 string
	var q1 string
	var q2 int
	var q3 int
	var q4 string
	var q5 string
	var q6 int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Wochenmodelle auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/employments"
			q := url.Values{}
			if cmd.Flags().Changed("from") {
				q.Set("from", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("to") {
				q.Set("to", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("user-id") {
				q.Set("user_id", fmt.Sprint(q6))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&q0, "from", "", "Employment date range start. Format: YYYY-MM-DD (e.g. `2026-01-01`).")
	f.StringVar(&q1, "ids", "", "Comma-separated IDs.")
	f.IntVar(&q2, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q3, "per-page", 0, "Page size.")
	f.StringVar(&q4, "to", "", "Employment date range end. Format: YYYY-MM-DD (e.g. `2026-01-31`).")
	f.StringVar(&q5, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	f.IntVar(&q6, "user-id", 0, "")
	return cmd
}

func newUserEmploymentsPatchCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 int
	var data string
	cmd := &cobra.Command{
		Use:   "patch <id>",
		Short: "Wochenmodell teilweise aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/employments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("from") {
				body["from"] = v0
			}
			if cmd.Flags().Changed("to") {
				body["to"] = v1
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v2
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PATCH",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "from", "", "")
	f.StringVar(&v1, "to", "", "")
	f.IntVar(&v2, "user-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}

func newUserEmploymentsUpdateCmd(app *cli.App) *cobra.Command {
	var v0 string
	var v1 string
	var v2 int
	var data string
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Wochenmodell aktualisieren",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/users/employments/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			body, err := cli.ParseData(data)
			if err != nil {
				return err
			}
			if cmd.Flags().Changed("from") {
				body["from"] = v0
			}
			if cmd.Flags().Changed("to") {
				body["to"] = v1
			}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = v2
			}
			raw, err := cli.EncodeBody(body)
			if err != nil {
				return err
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "PUT",
				Path:   path,
				Body:   raw,
			})
		},
	}
	f := cmd.Flags()
	f.StringVar(&v0, "from", "", "")
	f.StringVar(&v1, "to", "", "")
	f.IntVar(&v2, "user-id", 0, "")
	f.StringVar(&data, "data", "", "request body as JSON object")
	return cmd
}
