// Code generated by tools/gen; DO NOT EDIT.

package commands

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/whatwedo/moco-cli/internal/cli"
	"github.com/whatwedo/moco-cli/internal/client"
)

func newVatCodeSalesCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "vat-code-sales",
		Short: "Steuercodes verwalten",
	}
	cmd.AddCommand(
		newVatCodeSalesGetCmd(app),
		newVatCodeSalesListCmd(app),
	)
	return cmd
}

func newVatCodeSalesGetCmd(app *cli.App) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Steuercode abrufen",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/vat_code_sales/{id}"
			path = strings.Replace(path, "{id}", url.PathEscape(args[0]), 1)
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
			})
		},
	}
	return cmd
}

func newVatCodeSalesListCmd(app *cli.App) *cobra.Command {
	var q0 bool
	var q1 string
	var q2 bool
	var q3 int
	var q4 int
	var q5 bool
	var q6 string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "Steuercodes auflisten",
		Args:  cobra.ExactArgs(0),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/vat_code_sales"
			q := url.Values{}
			if cmd.Flags().Changed("active") {
				q.Set("active", fmt.Sprint(q0))
			}
			if cmd.Flags().Changed("ids") {
				q.Set("ids", fmt.Sprint(q1))
			}
			if cmd.Flags().Changed("intra-eu") {
				q.Set("intra_eu", fmt.Sprint(q2))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", fmt.Sprint(q3))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", fmt.Sprint(q4))
			}
			if cmd.Flags().Changed("reverse-charge") {
				q.Set("reverse_charge", fmt.Sprint(q5))
			}
			if cmd.Flags().Changed("updated-after") {
				q.Set("updated_after", fmt.Sprint(q6))
			}
			return app.Execute(cmd.Context(), client.Request{
				Method: "GET",
				Path:   path,
				Query:  q,
			})
		},
	}
	f := cmd.Flags()
	f.BoolVar(&q0, "active", false, "")
	f.StringVar(&q1, "ids", "", "Comma-separated IDs.")
	f.BoolVar(&q2, "intra-eu", false, "")
	f.IntVar(&q3, "page", 0, "Page number, starting at 1.")
	f.IntVar(&q4, "per-page", 0, "Page size.")
	f.BoolVar(&q5, "reverse-charge", false, "")
	f.StringVar(&q6, "updated-after", "", "ISO 8601 UTC timestamp (e.g. `2026-01-31T14:30:00Z`).")
	return cmd
}
